
title_search_success_response = {'Title': 'Aliens', 'Year': '1986', 'Rated': 'R', 'Released': '18 Jul 1986',
                                 'Runtime': '137 min', 'Genre': 'Action, Adventure, Sci-Fi, Thriller',
                                 'Director': 'James Cameron',
                                 'Writer': "James Cameron (story by), David Giler (story by), Walter Hill (story by), Dan O'Bannon (based on characters created by), Ronald Shusett (based on characters created by), James Cameron (screenplay by)",
                                 'Actors': 'Sigourney Weaver, Carrie Henn, Michael Biehn, Paul Reiser',
                                 'Plot': 'Ellen Ripley is rescued by a deep salvage team after being in hypersleep for 57 years. The moon that the Nostromo visited has been colonized, but contact is lost. This time, colonial marines have impressive firepower, but will that be enough?',
                                 'Language': 'English', 'Country': 'USA, UK',
                                 'Awards': 'Won 2 Oscars. Another 18 wins & 23 nominations.',
                                 'Poster': 'https://m.media-amazon.com/images/M/MV5BZGU2OGY5ZTYtMWNhYy00NjZiLWI0NjUtZmNhY2JhNDRmODU3XkEyXkFqcGdeQXVyNzkwMjQ5NzM@._V1_SX300.jpg',
                                 'Ratings': [{'Source': 'Internet Movie Database', 'Value': '8.3/10'},
                                             {'Source': 'Rotten Tomatoes', 'Value': '99%'},
                                             {'Source': 'Metacritic', 'Value': '84/100'}], 'Metascore': '84',
                                 'imdbRating': '8.3', 'imdbVotes': '619,149', 'imdbID': 'tt0090605', 'Type': 'movie',
                                 'DVD': '01 Jun 1999', 'BoxOffice': 'N/A', 'Production': '20th Century Fox',
                                 'Website': 'N/A', 'Response': 'True'}
