search_success_reponse = {'businesses': [
    {'id': 'HfhdIN-04MB5R2xoqXvnlw', 'alias': 'aberdour-post-office-burntisland', 'name': 'Aberdour Post Office',
     'image_url': 'https://s3-media3.fl.yelpcdn.com/bphoto/uG6iZi4VHyVqsZXi8MyA0g/o.jpg', 'is_closed': False,
     'url': 'https://www.yelp.co.uk/biz/aberdour-post-office-burntisland?adjust_creative=s4TB2oNJKW1zRFSbBUC-hw&utm_campaign=yelp_api_v3&utm_medium=api_v3_business_search&utm_source=s4TB2oNJKW1zRFSbBUC-hw',
     'review_count': 1, 'categories': [{'alias': 'postoffices', 'title': 'Post Offices'}], 'rating': 3.0,
     'coordinates': {'latitude': 56.0535474, 'longitude': -3.3019557}, 'transactions': [],
     'location': {'address1': '43 High Street', 'address2': '', 'address3': 'Aberdour', 'city': 'Burntisland',
                  'zip_code': 'KY3 0SJ', 'country': 'GB', 'state': 'FIF',
                  'display_address': ['43 High Street', 'Aberdour', 'Burntisland KY3 0SJ']}, 'phone': '+441383860317',
     'display_phone': '01383 860317', 'distance': 3394.4855662467594},
    {'id': 'dGsMxWFRyfALQry0oeyGlw', 'alias': 'ferry-road-post-office-edinburgh', 'name': 'Ferry Road Post Office',
     'image_url': '', 'is_closed': False,
     'url': 'https://www.yelp.co.uk/biz/ferry-road-post-office-edinburgh?adjust_creative=s4TB2oNJKW1zRFSbBUC-hw&utm_campaign=yelp_api_v3&utm_medium=api_v3_business_search&utm_source=s4TB2oNJKW1zRFSbBUC-hw',
     'review_count': 1, 'categories': [{'alias': 'postoffices', 'title': 'Post Offices'},
                                       {'alias': 'couriers', 'title': 'Couriers & Delivery Services'}], 'rating': 4.0,
     'coordinates': {'latitude': 55.9743947, 'longitude': -3.1847039}, 'transactions': [],
     'location': {'address1': '119 Ferry Road', 'address2': None, 'address3': None, 'city': 'Edinburgh',
                  'zip_code': 'EH6 4ET', 'country': 'GB', 'state': 'EDH',
                  'display_address': ['119 Ferry Road', 'Edinburgh EH6 4ET']}, 'phone': '+441315546817',
     'display_phone': '0131 554 6817', 'distance': 10515.918854905809},
    {'id': 'iqi51fDcMp8NRVarIdvd6Q', 'alias': 'stock-bridge-post-office-edinburgh', 'name': 'Stock Bridge Post Office',
     'image_url': 'https://s3-media3.fl.yelpcdn.com/bphoto/qJUrYO_i86reodxh0k2Ewg/o.jpg', 'is_closed': False,
     'url': 'https://www.yelp.co.uk/biz/stock-bridge-post-office-edinburgh?adjust_creative=s4TB2oNJKW1zRFSbBUC-hw&utm_campaign=yelp_api_v3&utm_medium=api_v3_business_search&utm_source=s4TB2oNJKW1zRFSbBUC-hw',
     'review_count': 3, 'categories': [{'alias': 'postoffices', 'title': 'Post Offices'}], 'rating': 4.0,
     'coordinates': {'latitude': 55.9592774, 'longitude': -3.2128019}, 'transactions': [],
     'location': {'address1': '70-72 Raeburn Place', 'address2': None, 'address3': None, 'city': 'Edinburgh',
                  'zip_code': 'EH4 1HJ', 'country': 'GB', 'state': 'EDH',
                  'display_address': ['70-72 Raeburn Place', 'Edinburgh EH4 1HJ']}, 'phone': '+448457223344',
     'display_phone': '0845 722 3344', 'distance': 12323.170126789819},
    {'id': 'J08SITh-WVUJzE11Wx4MKQ', 'alias': 'blackhall-sub-post-office-edinburgh',
     'name': 'Blackhall Sub Post Office',
     'image_url': 'https://s3-media2.fl.yelpcdn.com/bphoto/fhn7xCH16VwMWJ1Fcd8MLw/o.jpg', 'is_closed': False,
     'url': 'https://www.yelp.co.uk/biz/blackhall-sub-post-office-edinburgh?adjust_creative=s4TB2oNJKW1zRFSbBUC-hw&utm_campaign=yelp_api_v3&utm_medium=api_v3_business_search&utm_source=s4TB2oNJKW1zRFSbBUC-hw',
     'review_count': 1, 'categories': [{'alias': 'postoffices', 'title': 'Post Offices'}], 'rating': 5.0,
     'coordinates': {'latitude': 55.9573819, 'longitude': -3.2496302}, 'transactions': [],
     'location': {'address1': '11 Marischal Place', 'address2': None, 'address3': None, 'city': 'Edinburgh',
                  'zip_code': 'EH4 3NF', 'country': 'GB', 'state': 'EDH',
                  'display_address': ['11 Marischal Place', 'Edinburgh EH4 3NF']}, 'phone': '+441313152005',
     'display_phone': '0131 315 2005', 'distance': 13051.585152724369},
    {'id': 'ox3YZLSCg2lhqfteJbBA0A', 'alias': 'newhaven-road-post-office-edinburgh',
     'name': 'Newhaven Road Post Office', 'image_url': '', 'is_closed': False,
     'url': 'https://www.yelp.co.uk/biz/newhaven-road-post-office-edinburgh?adjust_creative=s4TB2oNJKW1zRFSbBUC-hw&utm_campaign=yelp_api_v3&utm_medium=api_v3_business_search&utm_source=s4TB2oNJKW1zRFSbBUC-hw',
     'review_count': 2, 'categories': [{'alias': 'postoffices', 'title': 'Post Offices'}], 'rating': 2.5,
     'coordinates': {'latitude': 55.9784590528066, 'longitude': -3.193222186057}, 'transactions': [],
     'location': {'address1': '218 Newhaven Road', 'address2': None, 'address3': None, 'city': 'Edinburgh',
                  'zip_code': 'EH6 4QE', 'country': 'GB', 'state': 'EDH',
                  'display_address': ['218 Newhaven Road', 'Edinburgh EH6 4QE']}, 'phone': '+441315523625',
     'display_phone': '0131 552 3625', 'distance': 10078.592928674645},
    {'id': 'GwsTnGMEebzwDoW9pn61BQ', 'alias': 'elm-row-post-office-edinburgh', 'name': 'Elm Row Post Office',
     'image_url': 'https://s3-media3.fl.yelpcdn.com/bphoto/2dkxO_Ig8WJxvELF86RNcg/o.jpg', 'is_closed': False,
     'url': 'https://www.yelp.co.uk/biz/elm-row-post-office-edinburgh?adjust_creative=s4TB2oNJKW1zRFSbBUC-hw&utm_campaign=yelp_api_v3&utm_medium=api_v3_business_search&utm_source=s4TB2oNJKW1zRFSbBUC-hw',
     'review_count': 3, 'categories': [{'alias': 'postoffices', 'title': 'Post Offices'}], 'rating': 1.5,
     'coordinates': {'latitude': 55.9584655761719, 'longitude': -3.1835629940033}, 'transactions': [],
     'location': {'address1': '20 Elm Row', 'address2': '', 'address3': '', 'city': 'Edinburgh', 'zip_code': 'EH7 4AA',
                  'country': 'GB', 'state': 'EDH', 'display_address': ['20 Elm Row', 'Edinburgh EH7 4AA']},
     'phone': '+441315573887', 'display_phone': '0131 557 3887', 'distance': 12287.281422967997},
    {'id': 'v-vc6sbwnnSeMsdWHS-rHg', 'alias': 'blackhall-post-office-edinburgh', 'name': 'Blackhall Post Office',
     'image_url': '', 'is_closed': False,
     'url': 'https://www.yelp.co.uk/biz/blackhall-post-office-edinburgh?adjust_creative=s4TB2oNJKW1zRFSbBUC-hw&utm_campaign=yelp_api_v3&utm_medium=api_v3_business_search&utm_source=s4TB2oNJKW1zRFSbBUC-hw',
     'review_count': 1, 'categories': [{'alias': 'postoffices', 'title': 'Post Offices'}], 'rating': 5.0,
     'coordinates': {'latitude': 55.957389, 'longitude': -3.249649}, 'transactions': [],
     'location': {'address1': '11 Marischal Place', 'address2': '', 'address3': '', 'city': 'Edinburgh',
                  'zip_code': 'EH4 3NF', 'country': 'GB', 'state': 'EDH',
                  'display_address': ['11 Marischal Place', 'Edinburgh EH4 3NF']}, 'phone': '+441313152005',
     'display_phone': '0131 315 2005', 'distance': 13051.585152724369},
    {'id': 'eBEJm7sn8-IbU9FOlrZOiw', 'alias': 'davidsons-mains-sub-post-office-edinburgh',
     'name': 'Davidsons Mains Sub Post Office',
     'image_url': 'https://s3-media2.fl.yelpcdn.com/bphoto/-QhN5N08lSIk-m5aXskWsw/o.jpg', 'is_closed': False,
     'url': 'https://www.yelp.co.uk/biz/davidsons-mains-sub-post-office-edinburgh?adjust_creative=s4TB2oNJKW1zRFSbBUC-hw&utm_campaign=yelp_api_v3&utm_medium=api_v3_business_search&utm_source=s4TB2oNJKW1zRFSbBUC-hw',
     'review_count': 3, 'categories': [{'alias': 'postoffices', 'title': 'Post Offices'}], 'rating': 3.0,
     'coordinates': {'latitude': 55.9650956, 'longitude': -3.2694593}, 'transactions': [],
     'location': {'address1': '49 Corbiehill Road', 'address2': None, 'address3': None, 'city': 'Edinburgh',
                  'zip_code': 'EH4 5AT', 'country': 'GB', 'state': 'EDH',
                  'display_address': ['49 Corbiehill Road', 'Edinburgh EH4 5AT']}, 'phone': '+441313365346',
     'display_phone': '0131 336 5346', 'distance': 12699.981803495699},
    {'id': 'wA2DT_zhSEcRQDU6mFUtww', 'alias': 'royal-mail-edinburgh-east-delivery-office-edinburgh',
     'name': 'Royal Mail Edinburgh East Delivery Office', 'image_url': '', 'is_closed': False,
     'url': 'https://www.yelp.co.uk/biz/royal-mail-edinburgh-east-delivery-office-edinburgh?adjust_creative=s4TB2oNJKW1zRFSbBUC-hw&utm_campaign=yelp_api_v3&utm_medium=api_v3_business_search&utm_source=s4TB2oNJKW1zRFSbBUC-hw',
     'review_count': 3, 'categories': [{'alias': 'postoffices', 'title': 'Post Offices'}], 'rating': 2.5,
     'coordinates': {'latitude': 55.9559421, 'longitude': -3.1239751}, 'transactions': [],
     'location': {'address1': '7-11 East Telferton', 'address2': 'Telferton Industrial Estate', 'address3': '',
                  'city': 'Edinburgh', 'zip_code': 'EH7 6XD', 'country': 'GB', 'state': 'EDH',
                  'display_address': ['7-11 East Telferton', 'Telferton Industrial Estate', 'Edinburgh EH7 6XD']},
     'phone': '+443456021021', 'display_phone': '0345 602 1021', 'distance': 13118.597714472027}], 'total': 9,
                          'region': {'center': {'longitude': -3.184490203857422, 'latitude': 56.068966659801724}}}
