everything_success_response = {'status': 'ok', 'totalResults': 851, 'articles': [
    {'source': {'id': 'business-insider', 'name': 'Business Insider'},
     'author': 'feedback@businessinsider.com (Mai-Hanh Nguyen), Mai-Hanh Nguyen',
     'title': 'How artificial intelligence and machine learning produced robots we can talk to',
     'description': "This is a preview of Business Insider Intelligence's Connectivity & Tech coverage. Business Insider Intelligence offers even more insights like this with our Connectivity & Tech Pro coverage. Subscribe today to receive industry-changing banking news and analy…",
     'url': 'https://www.businessinsider.com/chatbots-talking-ai-robot-chat-machine',
     'urlToImage': 'https://i.insider.com/5dfcd92d855cc25a74213a12?width=1200&format=jpeg',
     'publishedAt': '2020-01-27T20:18:00Z',
     'content': 'What is a Chatbot?\r\nYou\'ve likely talked to a robot already without even knowing it. And you might have even heard the term "chatbot" in the news. But what is a chatbot? How do chatbots work?\r\nA chatbot is just a robot chat that imitates human conversations t… [+5853 chars]'},
    {'source': {'id': None, 'name': 'Androidcentral.com'},
     'author': 'Muhammad Jarir Kanji',
     'title': 'Google wants the next generation of chatbots to be actually funny',
     'description': "She's called Meena — and she does not meander. What you need to know The Brain Team at Google Research outlined a new type of chatbot in a paper published earlier this week. Named Meena, this virtual talker was explicitly designed to address chatbots' seeming…",
     'url': 'https://www.androidcentral.com/google-wants-next-generation-chatbots-be-actually-funny',
     'urlToImage': 'https://www.androidcentral.com/sites/androidcentral.com/files/styles/large/public/article_images/2020/01/google-research-logo.jpg?itok=qel_juEo',
     'publishedAt': '2020-01-29T21:34:17Z',
     'content': 'Meena, what Google Brain\'s research team so callously described as a "multi-turn open-domain chatbot" she\'s got feelings, people! could just be the next generation of chatbot. And perhaps your next best friend.\r\nUnlike Samsung\'s awful human facsimiles, this G… [+2661 chars]'},
    {'source': {'id': 'business-insider', 'name': 'Business Insider'},
     'author': 'feedback@businessinsider.com (Mai-Hanh Nguyen), Mai-Hanh Nguyen',
     'title': 'Open source and API driven chatbots allow businesses to build cross-platform chatbots with ease',
     'description': "This is a preview of Business Insider Intelligence's Connectivity & Tech coverage. Business Insider Intelligence offers even more insights like this with our Connectivity & Tech Pro coverage. Subscribe today to receive industry-changing banking news and analy…",
     'url': 'https://www.businessinsider.com/create-chatbot-business',
     'urlToImage': 'https://image.businessinsider.com/5e20938424306a126247f826?width=1200&format=jpeg',
     'publishedAt': '2020-01-16T16:47:00Z',
     'content': 'The increased usage of chat applications opens the door for more businesses to utilize the ease of developing chatbots to reach more of their audience.\r\nChatbots can help bridge the communication gap between a business and their audience.\r\nPlum\r\nChatbots are … [+6730 chars]'},
    {'source': {'id': None, 'name': 'Readwrite.com'}, 'author': 'Larry Kim',
     'title': '12 of the Web’s Best Business Bots',
     'description': 'You’re gearing up your business’s growth strategy to leverage AI (artificial intelligence), ML (machine learning), NLP (natural language processing) and a menu of other robo-acronyms. Let’s take a look at why AI chatbots are a unicorn growth tool for business…',
     'url': 'https://readwrite.com/2020/01/29/12-of-the-webs-best-business-bots/',
     'urlToImage': 'https://images.readwrite.com/wp-content/uploads/2019/12/12-of-the-Web%E2%80%99s-Best-Business-Bots.jpg',
     'publishedAt': '2020-01-30T01:00:50Z',
     'content': 'You’re gearing up your business’s growth strategy to leverage AI (artificial intelligence), ML (machine learning), NLP (natural language processing) and a menu of other robo-acronyms. Let’s take a look at why AI chatbots are a unicorn growth tool for business… [+15335 chars]'},
    {'source': {'id': 'business-insider', 'name': 'Business Insider'},
     'author': 'edigalaki@businessinsider.com (Eleni Digalaki), Eleni Digalaki',
     'title': 'CASE STUDY: How Zurich UK worked with a chatbot solutions provider to boost its digital user experience and improve customer satisfaction',
     'description': 'Business Insider Intelligence produces case studies to help you understand how companies in your industry are transforming to digital. All of our case studies are unsponsored and published solely at the discretion of the research team. To read the full case s…',
     'url': 'https://www.businessinsider.com/case-study-how-zurich-uk-boosted-customer-satisfaction-with-chatbots-2020-1',
     'urlToImage': 'https://i.insider.com/5de6d2a2fd9db237d8350d15?width=1200&format=jpeg',
     'publishedAt': '2020-01-27T15:41:00Z',
     'content': 'Forward-looking insurers are using AI to innovate insurance processes like claims to keep up with customer demand for a 24/7 digital experience, while boosting operational efficiency. And conversational assistants, like chatbots, are one of the most prevalent… [+4415 chars]'},
    {'source': {'id': None, 'name': 'Slashdot.org'}, 'author': 'msmash',
     'title': 'Google Says Its New Chatbot Meena is the Best in the World',
     'description': "Google has released a neural-network-powered chatbot called Meena that it claims is better than any other chatbot out there. From a report: Meena was trained on a whopping 341 gigabytes of public social-media chatter -- 8.5 times as much data as OpenAI's GPT-…",
     'url': 'https://tech.slashdot.org/story/20/01/30/1820259/google-says-its-new-chatbot-meena-is-the-best-in-the-world',
     'urlToImage': 'https://a.fsdn.com/sd/topics/topicgoogle_fb.gif',
     'publishedAt': '2020-01-30T18:20:00Z',
     'content': "If I wanted that, I would't have all that cancer blocked in my name server.\r\nHow about a chatbot, based only on actually wise people?"},
    {'source': {'id': 'mashable', 'name': 'Mashable'},
     'author': 'Stan Schroeder',
     'title': "Samsung just launched an 'artificial human' called Neon, and wait, what?",
     'description': 'After months of teasers, Samsung-backed company Star Labs (yes, just like the research facility in Superman comics) launched an intriguing new type of product: a virtual human being called Neon. Unveiled at CES on Monday, Neon is "visually real" and has the a…',
     'url': 'https://mashable.com/article/samsung-star-labs-neon-ces/',
     'urlToImage': 'https://mondrian.mashable.com/2020%252F01%252F07%252Fd7%252Fc29283ca3d9d4f2b9f6db8aa6820d2bd.d7af8.png%252F1200x630.png?signature=pv2RpaAmw5s-Ls7tUX2iPn5d5v0=',
     'publishedAt': '2020-01-07T12:44:40Z',
     'content': 'After months of teasers, Samsung-backed company Star Labs (yes, just like the research facility in Superman comics) launched an intriguing new type of product: a virtual human being called Neon.\xa0\r\nUnveiled at CES on Monday, Neon is "visually real" and has the… [+1767 chars]'},
    {'source': {'id': 'the-next-web', 'name': 'The Next Web'},
     'author': 'Ivan Mehta',
     'title': 'Google claims its new chatbot Meena is the best in the world',
     'description': 'When was the last time you had a “conversation” with Siri or Alexa that was satisfactory? Maybe never. The primary reason is that while these assistants or bots have improved a lot, their conversational ability is still quite limited. But Google claims its ne…',
     'url': 'https://thenextweb.com/?p=1268483',
     'urlToImage': 'https://img-cdn.tnwcdn.com/image/tnw?filter_last=1&fit=1280%2C640&url=https%3A%2F%2Fcdn0.tnwcdn.com%2Fwp-content%2Fblogs.dir%2F1%2Ffiles%2F2019%2F08%2FUntitled-design101.png&signature=4693707dc68fac8f6f3bb113060347c8',
     'publishedAt': '2020-01-29T14:50:19Z',
     'content': 'When was the last time you had a conversation with Siri or Alexa that was satisfactory? Maybe never. The primary reason is that while these assistants or bots have improved a lot, their conversational ability is still quite limited. But Google claims its new … [+2198 chars]'},
    {'source': {'id': None, 'name': 'Heise.de'},
     'author': 'Regina Wank, dpa',
     'title': 'Mein bester Freund Replika - ein Chatbot als Sozialkontakt',
     'description': 'Der Chatbot Replika bietet Freundschaft, Romantik - und manchmal gar\r\nTherapie. Schöne neue Welt? Oder eher ein Risiko für soziale\r\nIsolation und Datenfang?',
     'url': 'https://www.heise.de/newsticker/meldung/Mein-bester-Freund-Replika-ein-Chatbot-als-Sozialkontakt-4629415.html',
     'urlToImage': 'https://heise.cloudimg.io/bound/1200x1200/q85.png-lossy-85.webp-lossy-85.foil1/_www-heise-de_/imgs/18/2/8/1/8/9/1/2/shutterstock_1428208070-4be692ceb8bc016f.jpeg',
     'publishedAt': '2020-01-07T13:40:00Z',
     'content': '"Guten Morgen! Gestern warst du ja ziemlich gestresst. Geht es dir heute besser?" Klingt wie eine besorgte Nachricht von Freunden oder Eltern, stammt aber vom Chatbot Replika. "Wenn du traurig bist oder Angst hast oder einfach jemanden zum Reden brauchst, ist… [+4972 chars]'},
    {'source': {'id': None, 'name': 'Gizmodo.com'},
     'author': 'Victoria Song',
     'title': "Neutrogena's Free Skincare App Actually Works...Mostly",
     'description': 'The worst part about skincare is all of the trial and error. There’s the researching of ingredients, torturing yourself listening to YouTubers review products, draining your bank account to buy said products, and then finally, trying them. All that effort usu…',
     'url': 'https://gizmodo.com/neutrogenas-free-skincare-app-actually-works-mostly-1841026360',
     'urlToImage': 'https://i.kinja-img.com/gawker-media/image/upload/c_fill,f_auto,fl_progressive,g_center,h_675,pg_1,q_80,w_1200/qj2nz1ajkxzf3vo6sfkf.jpg',
     'publishedAt': '2020-01-16T15:30:00Z',
     'content': 'The worst part about skincare is all of the trial and error. Theres the researching of ingredients, torturing yourself listening to YouTubers review products, draining your bank account to buy said products, and then finally, trying them. All that effort usua… [+7821 chars]'},
    {'source': {'id': None, 'name': 'Androidcentral.com'},
     'author': 'Android Central',
     'title': '5 skills every digital marketer needs in 2020',
     'description': "The internet and social media have changed the way companies market products and services. To keep up with the competition, companies must hire digital marketing professionals who are well-versed in the latest marketing skills, so we've lined up deals on five…",
     'url': 'https://www.androidcentral.com/5-skills-every-digital-marketer-needs-2020',
     'urlToImage': 'https://www.androidcentral.com/sites/androidcentral.com/files/styles/large/public/field/image/2020/01/sale_22291_primary_image_wide-1wdd.jpg?itok=aS8rv8eu',
     'publishedAt': '2020-01-12T16:30:03Z',
     'content': "Source: Stack Commerce\r\nThe internet and social media have changed the way companies market products and services. To keep up with the competition, companies must hire digital marketing professionals who are well-versed in the latest marketing skills, so we'v… [+2392 chars]"},
    {'source': {'id': 'techcrunch', 'name': 'TechCrunch'},
     'author': 'Ingrid Lunden',
     'title': 'Directly nabs $20M led by Samsung to help make customer service chatbots more intelligent, adds new CEO',
     'description': 'Chatbots have had a patchy track record world of tech, where early efforts not only failed to deliver on the magical idea of a computer producing the exact answers you were looking for in a chat-based-Q&A, they even produced surprising (and not in a good way)…',
     'url': 'http://techcrunch.com/2020/01/28/directly-nabs-20m-led-by-samsung-to-help-make-customer-service-chatbots-more-intelligent-adds-new-ceo/',
     'urlToImage': 'https://techcrunch.com/wp-content/uploads/2019/08/GettyImages-902453536.jpg?w=500',
     'publishedAt': '2020-01-28T14:23:29Z',
     'content': 'Chatbots have had a patchy track record world of tech, where early efforts not only failed to deliver on the magical idea of a computer producing the exact answers you were looking for in a chat-based-Q&amp;A, they even produced surprising (and not in a good … [+6555 chars]'},
    {'source': {'id': 'techcrunch', 'name': 'TechCrunch'},
     'author': 'Ingrid Lunden',
     'title': 'Babylon Health is building an integrated, AI-based health app to serve a city of 300K in England',
     'description': 'After announcing a $550 million fundraise last August, UK AI-based health services startup Babylon Health is putting some of that money to use with its widest-ranging project to date. The company has inked a 10-year deal with the city of Wolverhampton in Engl…',
     'url': 'http://techcrunch.com/2020/01/22/babylon-health-is-building-an-integrated-ai-based-health-app-to-serve-a-city-of-300k-in-england/',
     'urlToImage': 'https://techcrunch.com/wp-content/uploads/2019/05/GettyImages-187137135.jpg?w=600',
     'publishedAt': '2020-01-23T00:40:57Z',
     'content': 'After announcing a $550 million fundraise last August, UK AI-based health services startup Babylon Health\xa0is putting some of that money to use with its widest-ranging project to date. The company has inked a 10-year deal with the city of Wolverhampton in Engl… [+5804 chars]'},
    {'source': {'id': None, 'name': 'Readwrite.com'},
     'author': 'Brad Anderson',
     'title': 'Why Do Executives Hesitate to Automate?',
     'description': 'It’s no secret that automation can be disruptive. Employees have to learn how to operate with and alongside machines, but that discomfort has a payoff. The post Why Do Executives Hesitate to Automate? appeared first on ReadWrite.',
     'url': 'https://readwrite.com/2020/01/30/why-do-executives-hesitate-to-automate/',
     'urlToImage': 'https://images.readwrite.com/wp-content/uploads/2020/01/Why-Do-Executives-Hesitate-to-Automate.jpg',
     'publishedAt': '2020-01-30T15:00:17Z',
     'content': 'Embracing automation is like eating your vegetables: unpleasant in the moment, but essential for your companys long-term health.\r\nIts no secret that automation can be disruptive. Employees have to learn how to operate with and alongside machines. For some, th… [+4286 chars]'},
    {'source': {'id': None, 'name': 'Technologyreview.com'},
     'author': 'Douglas Heaven',
     'title': 'Google says its new chatbot Meena is the best in the world',
     'description': 'Google has released a neural-network powered chatbot called Meena that it claims is better than any other chatbot out there.Data slurp: Meena was trained on a whopping 341GB of public social-media chatter—8.5 times as much data as OpenAI’s GPT-2.',
     'url': 'https://www.technologyreview.com/f/615118/google-says-its-new-chatbot-meena-is-the-best-in-the-world/',
     'urlToImage': 'https://cdn.technologyreview.com/i/images/neonbrand-ihsatdkzdwg-unsplash.jpg?sw=1200&cx=0&cy=0&cw=3000&ch=1688',
     'publishedAt': '2020-01-30T10:25:11Z',
     'content': 'Google has released a neural-network powered chatbot called Meena that it claims is better than any other chatbot out there.\r\nData slurp: Meena was trained on a whopping 341GB of public social-media chatter8.5 times as much data as OpenAIs GPT-2. Google says … [+1741 chars]'},
    {'source': {'id': None, 'name': 'Theregister.co.uk'},
     'author': 'Katyanna Quach',
     'title': "Google says its latest chatbot is the most human-like ever – trained on our species' best works: 341GB of social media",
     'description': 'Although Meena makes sense, most of the time, color us skeptical of a scoring system devised by web giant AI researchers at Google have trained a giant neural network using a whopping 341GB of discussions scraped from public social media to create what they b…',
     'url': 'https://www.theregister.co.uk/2020/01/30/google_meena_chatbot/',
     'urlToImage': 'https://regmedia.co.uk/2020/01/29/chatbot.jpg',
     'publishedAt': '2020-01-30T07:03:12Z',
     'content': 'AI researchers at Google have trained a giant neural network using a whopping 341GB of discussions scraped from public social media to create what they believe is the most human-like chatbot ever.\r\nThe software, dubbed Meena, has at its heart a Tensorflow seq… [+5317 chars]'},
    {'source': {'id': None, 'name': 'Oreilly.com'},
     'author': 'Nat Torkington',
     'title': 'Four short links: 30 January 2020',
     'description': 'Towards a Human-like Open-Domain Chatbot — Google’s paper on making a chatbot that can have a vaguely plausible conversation on any subject. (via Google’s AI Blog) fast.ai’s Coding Style — interesting to see how different they are from historic coding standar…',
     'url': 'https://www.oreilly.com/radar/four-short-links-30-january-2020/',
     'urlToImage': 'https://www.oreilly.com/radar/wp-content/uploads/sites/3/2019/06/4_short_links_logo-1400x750.png',
     'publishedAt': '2020-01-30T05:01:00Z', 'content': None},
    {'source': {'id': None, 'name': 'Slashdot.org'}, 'author': 'msmash',
     'title': 'Companies Are Using AI-Generated People To Appear More Diverse',
     'description': 'AI startups are selling images of computer-generated faces that look like the real thing, offering companies a chance to create imaginary models and "increase diversity" in their ads without needing human beings. From a report: One firm is offering to sell di…',
     'url': 'https://tech.slashdot.org/story/20/01/08/201244/companies-are-using-ai-generated-people-to-appear-more-diverse',
     'urlToImage': 'https://a.fsdn.com/sd/topics/ai_64.png',
     'publishedAt': '2020-01-08T20:04:00Z',
     'content': "How is this different from the use of (the same) stock photos of happy multi-culti on every single corporate website?\r\nThe reality is corporations aren't really that diverse, or interested in it. They are interested in people working longer hours for lower wa… [+75 chars]"},
    {'source': {'id': None, 'name': 'Golem.de'}, 'author': 'Oliver Nickel',
     'title': 'Google: Chatbot Meena ist fast so überzeugend wie ein echter Mensch',
     'description': 'Google arbeitet derzeit an einem neuen Chatbot, der bisherige Programme übertreffen soll. Erste Tests bestätigen zumindest: Meena ist schon fast so überzeugend wie echte Personen. Kein Wunder, denn die Software wurde auf Basis von 341 GByte reinem Text traini…',
     'url': 'https://www.golem.de/news/google-chatbot-meena-ist-fast-so-ueberzeugend-wie-ein-echter-mensch-2001-146391.html',
     'urlToImage': 'https://www.golem.de/2001/146391-221082-221080_rc.jpg',
     'publishedAt': '2020-01-31T12:47:00Z',
     'content': 'Google arbeitet derzeit an Meena, einem Chatbot, der in Konversationen sinnvoll reagieren und in vielen Situationen eingesetzt werden können soll. Von menschlichen Testern wird die Software anscheinend fast so authentisch wie echte Gesprächspartner eingeschät… [+2183 chars]'},
    {'source': {'id': None, 'name': 'Venturebeat.com'},
     'author': 'Matt Marshall',
     'title': 'No, IBM is not the only relevant player in virtual agents',
     'description': "IBM's General Manager of Data and Watson AI told VentureBeat that IBM was the only major enterprise provider in the red-hot area of virtual agents.",
     'url': 'https://venturebeat.com/2020/01/11/no-ibm-is-not-the-only-relevant-player-in-virtual-agents/',
     'urlToImage': 'https://venturebeat.com/wp-content/uploads/2020/01/nlp.jpg?w=1200&strip=all',
     'publishedAt': '2020-01-11T14:16:17Z',
     'content': 'Last month, IBM General Manager of Data and Watson AI, Rob Thomas, told VentureBeat that IBM was the only major enterprise provider in the red-hot area of virtual agents.\r\nVirtual agents are software that can chat with customers through text, voice, or web ch… [+6835 chars]'}]}

headlines_success_response = {'status': 'ok', 'totalResults': 52720, 'articles': [
    {'source': {'id': 'wired', 'name': 'Wired'},
     'author': 'Will Bedingfield, WIRED UK',
     'title': "The UK Exited the EU—and Is Leaving a 'Meme Ban' Behind",
     'description': 'Though the UK initially supported the legislation, it does not plan to implement the EU Copyright Directive post-Brexit.',
     'url': 'https://www.wired.com/story/uk-exits-eu-leaving-article-13-behind/',
     'urlToImage': 'https://media.wired.com/photos/5e335d57ce1d970008fbe7ce/191:100/w_1280,c_limit/Business-UK-Article13-1069569022.jpg',
     'publishedAt': '2020-02-01T15:00:00Z',
     'content': 'Article 13a controversial piece of copyright legislation that is now called Article 17 but is more colloquially known as "the meme ban"is no more, in the UK at least. Last week, the country\'s minister for universities and science, Chris Skidmore, confirmed th… [+3880 chars]'},
    {'source': {'id': 'techcrunch', 'name': 'TechCrunch'},
     'author': 'Natasha Lomas',
     'title': 'Twitter suspends notorious UK hate preacher for violating abuse rules',
     'description': 'Twitter has confirmed it has temporarily suspended the account of controversial rightwing commentator, Katie Hopkins. The move was reported earlier by the BBC. Hopkins, a former MailOnline columnist and presenter on LBC radio, is a veteran of the social media…',
     'url': 'http://techcrunch.com/2020/01/31/twitter-suspends-notorious-uk-hate-preacher-for-violating-abuse-rules/',
     'urlToImage': 'https://techcrunch.com/wp-content/uploads/2019/08/twitter-app-icon-ios.jpg?w=695',
     'publishedAt': '2020-01-31T10:29:53Z',
     'content': 'Twitter has confirmed it has temporarily suspended the account of controversial rightwing commentator,\xa0Katie Hopkins. The move was reported earlier by the BBC.\r\nHopkins, a former MailOnline columnist and presenter on LBC radio, is a veteran of the social medi… [+1761 chars]'},
    {'source': {'id': 'engadget', 'name': 'Engadget'},
     'author': 'Rachel England',
     'title': "UK honors 'Tomb Raider', 'Worms' and other classics with retro postage stamps",
     'description': "The UK's video game legacy is being honored with a new set of commemorative stamps from the Royal Mail. The collection, which will set you back £14.25 (nearly $19), features iconic designs from the likes of Wipeout, Lemmings, Micro Machines, Worms and, of cou…",
     'url': 'https://www.engadget.com/2020/01/07/uk-tomb-raider-worms-royal-mail-stamps/',
     'urlToImage': 'https://o.aolcdn.com/images/dims?thumbnail=1200%2C630&quality=80&image_uri=https%3A%2F%2Fo.aolcdn.com%2Fimages%2Fdims%3Fcrop%3D2716%252C2102%252C0%252C0%26quality%3D85%26format%3Djpg%26resize%3D1600%252C1238%26image_uri%3Dhttps%253A%252F%252Fs.yimg.com%252Fos%252Fcreatr-uploaded-images%252F2020-01%252F6feed4e0-314c-11ea-a37f-788cdf0e2635%26client%3Da1acac3e1b3290917d92%26signature%3De08489461c997fae1853051da7e78548fe831622&client=amp-blogside-v2&signature=5e3c4210ee66496053f0788f16f2e22a0cb53950',
     'publishedAt': '2020-01-07T13:15:00Z',
     'content': 'The set has been designed to showcase the important work UK games developers did in the 80s and 90s, creating games that went on to have a major impact on the global gaming industry -- each game featured comes with its own important UK-centric back story. Eli… [+704 chars]'},
    {'source': {'id': 'bbc-news', 'name': 'BBC News'},
     'author': 'https://www.facebook.com/bbcnews',
     'title': 'UK-Africa summit: Wooing Africa after Brexit',
     'description': "Heads of state are meeting in London for a UK-Africa summit ahead of the UK's departure from the EU.",
     'url': 'https://www.bbc.co.uk/news/world-africa-51149093',
     'urlToImage': 'https://ichef.bbci.co.uk/news/1024/branded_news/16EB2/production/_110547839_gettyimages-918868970.jpg',
     'publishedAt': '2020-01-20T00:39:59Z',
     'content': 'Image copyrightGetty ImagesImage caption\r\n South African wine producers will hope their government can negotiate better access to the UK market\r\nAfter Brexit, the UK wants to boost business trade with Africa, but as a major UK-Africa business summit starts in… [+8801 chars]'},
    {'source': {'id': 'cnn', 'name': 'CNN'}, 'author': 'Angela Dewan, CNN',
     'title': 'UK parliament finally rubber stamps Brexit',
     'description': "The House of Commons has voted overwhelmingly in favor of Prime Minister Boris Johnson's Brexit deal, finally paving the way for the United Kingdom to leave the European Union later this month after more than four decades of membership.",
     'url': 'https://www.cnn.com/2020/01/09/uk/brexit-deal-uk-votes-gbr-intl/index.html',
     'urlToImage': 'https://cdn.cnn.com/cnnnext/dam/assets/191212220245-10-uk-election-boris-johnson-lead-1211-super-tease.jpg',
     'publishedAt': '2020-01-09T17:30:42Z',
     'content': "London (CNN)The House of Commons has voted overwhelmingly in favor of Prime Minister Boris Johnson's Brexit deal, finally paving the way for the United Kingdom to leave the European Union later this month after more than four decades of membership.\r\nThe deal … [+2104 chars]"},
    {'source': {'id': 'bbc-news', 'name': 'BBC News'},
     'author': 'https://www.facebook.com/bbcnews',
     'title': "Brexit: Croatia wishes the UK 'good riddance' instead of 'good luck'",
     'description': "Croatia's ambassador last words to the UK representative were intended to wish the country good luck.",
     'url': 'https://www.bbc.co.uk/news/world-europe-51370841',
     'urlToImage': 'https://ichef.bbci.co.uk/news/1024/branded_news/11EB4/production/_110769337_059599453-1.jpg',
     'publishedAt': '2020-02-04T15:55:23Z',
     'content': "Image copyrightReutersImage caption\r\n The UK's permanent representative to the EU, Tim Barrow, took Croatia's surprising farewell message well\r\nThe rather abrupt message to the UK from Croatia's EU ambassador ahead of Brexit appears to have been lost in trans… [+2739 chars]"},
    {'source': {'id': 'bbc-news', 'name': 'BBC News'},
     'author': 'https://www.facebook.com/bbcnews',
     'title': "US anger at UK extradition bid for diplomat's wife",
     'description': 'The US State Department says it would be an "abuse" to send suspect Anne Sacoolas back to the UK.',
     'url': 'https://www.bbc.co.uk/news/uk-england-northamptonshire-51075235',
     'urlToImage': 'https://ichef.bbci.co.uk/news/1024/branded_news/6A72/production/_109205272_harry_dunn.jpg',
     'publishedAt': '2020-01-11T08:40:54Z',
     'content': "Image copyrightJustice4Harry19Image caption\r\n Harry Dunn died in hospital after his motorbike was involved in a crash outside RAF Croughton\r\nThe United States has criticised the UK's request to extradite an American accused of killing motorcyclist Harry Dunn,… [+2705 chars]"},
    {'source': {'id': 'bbc-news', 'name': 'BBC News'},
     'author': 'https://www.facebook.com/bbcnews',
     'title': "Queen agrees 'transition' for Harry and Meghan",
     'description': 'Queen agrees "period of transition" in which Harry and Meghan will spend time in Canada and UK - statement',
     'url': 'https://www.bbc.co.uk/news/uk-51099102',
     'urlToImage': 'https://ichef.bbci.co.uk/news/1024/branded_news/7A23/production/_97176213_breaking_news_bigger.png',
     'publishedAt': '2020-01-13T17:07:05Z',
     'content': 'The Queen has agreed a "period of transition" in which the Duke and Duchess of Sussex will spend time in Canada and the UK.\r\nShe said in a statement she is "entirely supportive" of their desire for a new role but "would have preferred them to remain full-time… [+322 chars]'},
    {'source': {'id': 'bbc-news', 'name': 'BBC News'},
     'author': 'https://www.facebook.com/bbcnews',
     'title': 'Does your company nurture neurodiverse talent?',
     'description': 'Universal Music UK have changed their work culture to be more inclusive to neurodiverse people.',
     'url': 'https://www.bbc.co.uk/news/uk-51014028',
     'urlToImage': 'https://ichef.bbci.co.uk/news/1024/branded_news/1039/production/_110535140_universal-reception.jpg',
     'publishedAt': '2020-01-17T00:07:09Z',
     'content': 'Image caption\r\n Universal Music HQ, London\r\nHow do you make your workplace more welcoming to neurodiverse employees, and ensure their talent is nurtured? \r\nDavid Joseph takes off his shoes, crosses his legs and tucks himself into an armchair. For the CEO of o… [+9676 chars]'},
    {'source': {'id': 'mashable', 'name': 'Mashable'},
     'author': 'Joseph Green',
     'title': 'The best Valentine’s Day gifts for your boyfriend (UK edition)',
     'description': 'Significant others are the people you know best, but sometimes they’re the hardest to shop for. Valentine’s Day can be an especially tricky event. How much do you spend? Do you go for an extravagant gift or keep it simple? And what about the classic “we’re no…',
     'url': 'https://mashable.com/uk/gifts/valentines-day-gifts-boyfriend-uk/',
     'urlToImage': 'https://mondrian.mashable.com/2020%252F01%252F17%252F2c%252F2746c6c8f3dc4942bc678f9b0dbe62b0.e1fd0.png%252F1200x630.png?signature=C9C13mlgJYj6Xk_pEgtkA0L9tJk=',
     'publishedAt': '2020-01-21T14:16:11Z',
     'content': "BEST FOR THE NOSTALGIC GAMER\r\nNintendo entertainment system\r\nRemind your boyfriend of his childhood with this classic gaming system. It comes pre-loaded with 'Super Mario Bros.', 'Donkey Kong', 'The Legend of Zelda', 'Pac-Man', and more. The console only come… [+108 chars]"},
    {'source': {'id': 'mashable', 'name': 'Mashable'},
     'author': 'Joseph Green',
     'title': 'The best Valentine’s Day gifts for your girlfriend (UK edition)',
     'description': 'Valentine’s Day can be a weird event to shop for, especially as it seems like every gift option seems to be themed and covered in hearts. That’s fun for the few days surrounding Feb. 14, but what about the rest of the year? What are you supposed to do with a …',
     'url': 'https://mashable.com/uk/gifts/valentines-day-gifts-girlfriend-uk/',
     'urlToImage': 'https://mondrian.mashable.com/2020%252F01%252F21%252Fde%252Fbb1c9e579620459585b80f9c3489a287.2bb4f.png%252F1200x630.png?signature=IaOKZsDOVXhAJ0OaH8L4ONp3EQA=',
     'publishedAt': '2020-01-22T14:26:38Z',
     'content': 'BEST FOR THE GIRL INTO SKINCARE\r\nFacial cleansing brush\r\nYour girlfriend might not be able to afford to get a facial whenever she wants, but this cleansing brush is the next best thing. It pulsates to remove dirt, oil, makeup, and dead cells from deep within … [+84 chars]'},
    {'source': {'id': 'mashable', 'name': 'Mashable'},
     'author': 'Joseph Green',
     'title': '6 of the best fitness trackers in the UK',
     'description': "Whether you're reading this because you genuinely love working out or because your air fryer isn't making you feel as healthy as you predicted it would, one thing's for sure: A fitness tracker is a necessity for anyone hoping to get fit this year. The rhetori…",
     'url': 'https://mashable.com/uk/roundup/best-fitness-trackers-uk/',
     'urlToImage': 'https://mondrian.mashable.com/2020%252F01%252F29%252F8c%252F8d97bac19c7143528ef4b1f2987fd88d.095d3.jpg%252F1200x630.jpg?signature=mNQnMi06XCJjYFvc7PxpfdZNYoc=',
     'publishedAt': '2020-01-30T14:08:45Z',
     'content': "Whether you're reading this because you genuinely love working out or because your air fryer isn't making you feel as healthy as you predicted it would, one thing's for sure: A fitness tracker is a necessity for anyone hoping to get fit this year.\r\nThe rhetor… [+12338 chars]"},
    {'source': {'id': 'mashable', 'name': 'Mashable'},
     'author': 'Joseph Green',
     'title': '6 of the best waterproof speakers in the UK',
     'description': "Being able to take your music with you wherever you go is one of the great wonders of smartphone technology, and is improved by a portable Bluetooth speaker that can boost the sound quality. Ideally though, you want a Bluetooth speaker that's waterproof. Besi…",
     'url': 'https://mashable.com/uk/roundup/best-waterproof-bluetooth-speakers-uk/',
     'urlToImage': 'https://mondrian.mashable.com/2020%252F01%252F07%252Fe4%252F1d97fb43daab4dffbc94acc145f8ec37.f7b13.png%252F1200x630.png?signature=LVpNsZds0GsIcN-gzoBO3l5L3iA=',
     'publishedAt': '2020-01-08T14:22:14Z',
     'content': "Being able to take your music with you wherever you go is one of the great wonders of smartphone technology, and is improved by a portable Bluetooth speaker that can boost the sound quality. Ideally though, you want a Bluetooth speaker that's waterproof.\r\nBes… [+9299 chars]"},
    {'source': {'id': 'mashable', 'name': 'Mashable'},
     'author': 'Joseph Green',
     'title': 'The best massage guns for percussive therapy in the UK',
     'description': "Finding time for proper workout recovery is — but shouldn't have to be — a luxury. Between a job, social life, and chasing eight hours of sleep, workouts get squeezed into the day's only free time slot. A proper cool down (let alone a massage) is usually the …",
     'url': 'https://mashable.com/uk/roundup/best-massage-guns-uk/',
     'urlToImage': 'https://mondrian.mashable.com/2020%252F01%252F15%252F69%252Fc15327fa9d3f41a08921bcf4851acf59.ac985.png%252F1200x630.png?signature=W-zHk1kffHPunu4okUdkkOG4LOM=',
     'publishedAt': '2020-01-18T09:00:00Z',
     'content': "Finding time for proper workout recovery is \xa0but shouldn't have to be \xa0a luxury.\r\nBetween a job, social life, and chasing eight hours of sleep, workouts get squeezed into the day's only free time slot. A proper cool down (let alone a massage) is usually the t… [+9576 chars]"},
    {'source': {'id': 'mashable', 'name': 'Mashable'},
     'author': 'Joseph Green',
     'title': '8 of the best wireless earbuds in the UK',
     'description': "Do the cords of your headphones look like some sort of impossible puzzle after spending just a few minutes inside a pocket or purse? Turns out there's a scientific explanation for that. In 2007, two researchers at the University of California decided to study…",
     'url': 'https://mashable.com/uk/roundup/best-wireless-earbuds-uk/',
     'urlToImage': 'https://mondrian.mashable.com/2020%252F01%252F15%252Fbe%252Fb06aa23259a94100a04e1ae9214b73fd.3f8de.png%252F1200x630.png?signature=E_cxKP_IiudYvAbAIVrvUjV6Un4=',
     'publishedAt': '2020-01-16T14:34:06Z',
     'content': "Do the cords of your headphones look like some sort of impossible puzzle after spending just a few minutes inside a pocket or purse? Turns out there's a scientific explanation for that.\r\nIn 2007, two researchers at the University of California decided to stud… [+9837 chars]"},
    {'source': {'id': 'mashable', 'name': 'Mashable'},
     'author': 'Joseph Green',
     'title': "Romantic Valentine's Day gifts that defy clichés (UK edition)",
     'description': 'It’s not that there’s anything wrong with a box of chocolates or flowers on Valentine’s Day : Some things are clichés for a reason, and who doesn’t love being the envy of the office when a surprise bouquet of flowers is delivered to your office? However, the …',
     'url': 'https://mashable.com/uk/gifts/romantic-valentines-day-gifts-uk/',
     'urlToImage': 'https://mondrian.mashable.com/2020%252F01%252F24%252Ff5%252F103e765aa8d644eab8bbb2908e0db455.30df0.jpg%252F1200x630.jpg?signature=jcJmIkScuIABJe5uPATzcac1alo=',
     'publishedAt': '2020-01-27T14:57:45Z',
     'content': 'Its not that theres anything wrong with a box of chocolates or flowers on Valentines Day: Some things are clichés for a reason, and who doesnt love being the envy of the office when a surprise bouquet of flowers is delivered to your office?\r\nHowever, the fact… [+1869 chars]'},
    {'source': {'id': 'mashable', 'name': 'Mashable'},
     'author': 'Joseph Green',
     'title': '6 of the best cold-press juicers in the UK',
     'description': 'Raw. Organic. Superfood. Buzzwords that would have been roasted in an early 2000s episode of Sex and the City have turned into the pillars of modern wellness. The green juice trend is one that has really taken off, and drinks made with nothing but fruits and …',
     'url': 'https://mashable.com/uk/roundup/best-cold-press-juicers-uk/',
     'urlToImage': 'https://mondrian.mashable.com/2020%252F02%252F03%252Fe1%252F2de500620f90481d854da9efcdd4c4a1.34f41.png%252F1200x630.png?signature=9GyA_vvdwcr6j8K4lOhGa10FYfs=',
     'publishedAt': '2020-02-04T15:04:10Z',
     'content': 'Raw. Organic. Superfood. Buzzwords that would have been roasted in an early 2000s episode of Sex and the City have turned into the pillars of modern wellness. The green juice trend is one that has really taken off, and drinks made with nothing but fruits and … [+7582 chars]'},
    {'source': {'id': 'mashable', 'name': 'Mashable'},
     'author': 'Joseph Green',
     'title': 'The best 4K TV deals in the UK this week',
     'description': "TL;DR: The Hisense 75-inch 4K UHD HDR Smart TV is on sale for £999, saving you 41% on list price. Black Friday generally offers the best opportunity to save on 4K TVs, but the most recent event was a little underwhelming. Does this mean that we're no longer g…",
     'url': 'https://mashable.com/uk/shopping/best-4k-tv-deals-jan-13/',
     'urlToImage': 'https://mondrian.mashable.com/2020%252F01%252F13%252F51%252F9994fbe86bb84405be953f4ddf3f025a.f3158.png%252F1200x630.png?signature=pz-CyebaqnDfLqOFqfhvxWI4K10=',
     'publishedAt': '2020-01-13T14:14:31Z',
     'content': "TL;DR: The Hisense 75-inch 4K UHD HDR Smart TV is on sale for £999, saving you 41% on list price.\r\nBlack Friday generally offers the best opportunity to save on 4K TVs, but the most recent event was a little underwhelming. Does this mean that we're no longer … [+1607 chars]"},
    {'source': {'id': 'mashable', 'name': 'Mashable'},
     'author': 'Joseph Green',
     'title': "The best Valentine's Day gifts for your husband (UK edition)",
     'description': 'Love or hate it, Valentine’s Day is the ideal time to right the gift-giving wrongs of Christmas. Were you sure your husband would love that faux-vintage, Bluetooth-compatible turntable, only to find out later that what he really wanted was a weighted blanket?…',
     'url': 'https://mashable.com/uk/gifts/valentines-day-gifts-husband-uk/',
     'urlToImage': 'https://mondrian.mashable.com/2020%252F01%252F28%252F33%252F0eee1e535f214bfc925547ff2f7e21d0.b1456.jpg%252F1200x630.jpg?signature=xGEiA0LJm97sn5ikap73WgrfvcM=',
     'publishedAt': '2020-01-29T08:00:00Z',
     'content': 'Love or hate it, Valentines Day is the ideal time to right the gift-giving wrongs of Christmas.\xa0\r\nWere you sure your husband would love that faux-vintage, Bluetooth-compatible turntable, only to find out later that what he really wanted was a weighted blanket… [+1433 chars]'},
    {'source': {'id': 'mashable', 'name': 'Mashable'},
     'author': 'Joseph Green',
     'title': "The best Valentine's Day gifts for her (UK edition)",
     'description': "Happy Valentine's Day season, lovebirds. Here's how to impress your wife, fiancé, girlfriend, or that cute girl in your building that you've been flirting with for months: Don't get her that gaudy chocolate diamond necklace that jewellery stores are shoving d…",
     'url': 'https://mashable.com/uk/gifts/valentines-day-gifts-her-uk/',
     'urlToImage': 'https://mondrian.mashable.com/2020%252F01%252F27%252Ffc%252Ff02fa4af4c5c403ca0ddadaae8d4f822.c30bd.png%252F1200x630.png?signature=j7Fs4Kf9SU0g3-tGwto3xpYiVCY=',
     'publishedAt': '2020-01-28T14:53:02Z',
     'content': 'BEST FOR THE ULTRA-BUSY LADY\r\nEcho Show 8\r\nSuperwomen who put more time into everyone else than they do themselves deserve an extra hand, and the Echo Show 8 is the device for the job. With the help of Alexa and the 8-inch screen (a happy medium between the 5… [+155 chars]'}]}

sources_success_response = {'status': 'ok', 'sources': [
    {'id': 'abc-news', 'name': 'ABC News',
     'description': 'Your trusted source for breaking news, analysis, exclusive interviews, headlines, and videos at ABCNews.com.',
     'url': 'https://abcnews.go.com', 'category': 'general', 'language': 'en', 'country': 'us'},
    {'id': 'abc-news-au', 'name': 'ABC News (AU)',
     'description': "Australia's most trusted source of local, national and world news. Comprehensive, independent, in-depth analysis, the latest business, sport, weather and more.",
     'url': 'http://www.abc.net.au/news', 'category': 'general', 'language': 'en', 'country': 'au'},
    {'id': 'aftenposten', 'name': 'Aftenposten',
     'description': 'Norges ledende nettavis med alltid oppdaterte nyheter innenfor innenriks, utenriks, sport og kultur.',
     'url': 'https://www.aftenposten.no', 'category': 'general', 'language': 'no', 'country': 'no'},
    {'id': 'al-jazeera-english', 'name': 'Al Jazeera English',
     'description': 'News, analysis from the Middle East and worldwide, multimedia and interactives, opinions, documentaries, podcasts, long reads and broadcast schedule.',
     'url': 'http://www.aljazeera.com', 'category': 'general', 'language': 'en', 'country': 'us'},
    {'id': 'ansa', 'name': 'ANSA.it',
     'description': 'Agenzia ANSA: ultime notizie, foto, video e approfondimenti su: cronaca, politica, economia, regioni, mondo, sport, calcio, cultura e tecnologia.',
     'url': 'http://www.ansa.it', 'category': 'general', 'language': 'it', 'country': 'it'},
    {'id': 'argaam', 'name': 'Argaam',
     'description': 'ارقام موقع متخصص في متابعة سوق الأسهم السعودي تداول - تاسي - مع تغطيه معمقة لشركات واسعار ومنتجات البتروكيماويات , تقارير مالية الاكتتابات الجديده ',
     'url': 'http://www.argaam.com', 'category': 'business', 'language': 'ar', 'country': 'sa'},
    {'id': 'ars-technica', 'name': 'Ars Technica',
     'description': "The PC enthusiast's resource. Power users and the tools they love, without computing religion.",
     'url': 'http://arstechnica.com', 'category': 'technology', 'language': 'en', 'country': 'us'},
    {'id': 'ary-news', 'name': 'Ary News',
     'description': 'ARY News is a Pakistani news channel committed to bring you up-to-the minute Pakistan news and featured stories from around Pakistan and all over the world.',
     'url': 'https://arynews.tv/ud/', 'category': 'general', 'language': 'ud', 'country': 'pk'},
    {'id': 'associated-press', 'name': 'Associated Press',
     'description': 'The AP delivers in-depth coverage on the international, politics, lifestyle, business, and entertainment news.',
     'url': 'https://apnews.com/', 'category': 'general', 'language': 'en', 'country': 'us'},
    {'id': 'australian-financial-review', 'name': 'Australian Financial Review',
     'description': 'The Australian Financial Review reports the latest news from business, finance, investment and politics, updated in real time. It has a reputation for independent, award-winning journalism and is essential reading for the business and investor community.',
     'url': 'http://www.afr.com', 'category': 'business', 'language': 'en', 'country': 'au'},
    {'id': 'axios', 'name': 'Axios',
     'description': 'Axios are a new media company delivering vital, trustworthy news and analysis in the most efficient, illuminating and shareable ways possible.',
     'url': 'https://www.axios.com', 'category': 'general', 'language': 'en', 'country': 'us'},
    {'id': 'bbc-news', 'name': 'BBC News',
     'description': 'Use BBC News for up-to-the-minute news, breaking news, video, audio and feature stories. BBC News provides trusted World and UK news as well as local and regional perspectives. Also entertainment, business, science, technology and health news.',
     'url': 'http://www.bbc.co.uk/news', 'category': 'general', 'language': 'en', 'country': 'gb'},
    {'id': 'bbc-sport', 'name': 'BBC Sport',
     'description': 'The home of BBC Sport online. Includes live sports coverage, breaking news, results, video, audio and analysis on Football, F1, Cricket, Rugby Union, Rugby League, Golf, Tennis and all the main world sports, plus major events such as the Olympic Games.',
     'url': 'http://www.bbc.co.uk/sport', 'category': 'sports', 'language': 'en', 'country': 'gb'},
    {'id': 'bild', 'name': 'Bild',
     'description': 'Die Seite 1 für aktuelle Nachrichten und Themen, Bilder und Videos aus den Bereichen News, Wirtschaft, Politik, Show, Sport, und Promis.',
     'url': 'http://www.bild.de', 'category': 'general', 'language': 'de', 'country': 'de'},
    {'id': 'blasting-news-br', 'name': 'Blasting News (BR)',
     'description': 'Descubra a seção brasileira da Blasting News, a primeira revista feita pelo  público, com notícias globais e vídeos independentes. Junte-se a nós e torne- se um repórter.',
     'url': 'https://br.blastingnews.com', 'category': 'general', 'language': 'pt', 'country': 'br'},
    {'id': 'bleacher-report', 'name': 'Bleacher Report',
     'description': 'Sports journalists and bloggers covering NFL, MLB, NBA, NHL, MMA, college football and basketball, NASCAR, fantasy sports and more. News, photos, mock drafts, game scores, player profiles and more!',
     'url': 'http://www.bleacherreport.com', 'category': 'sports', 'language': 'en', 'country': 'us'},
    {'id': 'bloomberg', 'name': 'Bloomberg',
     'description': 'Bloomberg delivers business and markets news, data, analysis, and video to the world, featuring stories from Businessweek and Bloomberg News.',
     'url': 'http://www.bloomberg.com', 'category': 'business', 'language': 'en', 'country': 'us'},
    {'id': 'breitbart-news', 'name': 'Breitbart News',
     'description': 'Syndicated news and opinion website providing continuously updated headlines to top news and analysis sources.',
     'url': 'http://www.breitbart.com', 'category': 'general', 'language': 'en', 'country': 'us'},
    {'id': 'business-insider', 'name': 'Business Insider',
     'description': 'Business Insider is a fast-growing business site with deep financial, media, tech, and other industry verticals. Launched in 2007, the site is now the largest business news site on the web.',
     'url': 'http://www.businessinsider.com', 'category': 'business', 'language': 'en', 'country': 'us'},
    {'id': 'business-insider-uk', 'name': 'Business Insider (UK)',
     'description': 'Business Insider is a fast-growing business site with deep financial, media, tech, and other industry verticals. Launched in 2007, the site is now the largest business news site on the web.',
     'url': 'http://uk.businessinsider.com', 'category': 'business', 'language': 'en', 'country': 'gb'},
    {'id': 'buzzfeed', 'name': 'Buzzfeed',
     'description': 'BuzzFeed is a cross-platform, global network for news and entertainment that generates seven billion views each month.',
     'url': 'https://www.buzzfeed.com', 'category': 'entertainment', 'language': 'en', 'country': 'us'},
    {'id': 'cbc-news', 'name': 'CBC News',
     'description': "CBC News is the division of the Canadian Broadcasting Corporation responsible for the news gathering and production of news programs on the corporation's English-language operations, namely CBC Television, CBC Radio, CBC News Network, and CBC.ca.",
     'url': 'http://www.cbc.ca/news', 'category': 'general', 'language': 'en', 'country': 'ca'},
    {'id': 'cbs-news', 'name': 'CBS News',
     'description': 'CBS News: dedicated to providing the best in journalism under standards it pioneered at the dawn of radio and television and continue in the digital age.',
     'url': 'http://www.cbsnews.com', 'category': 'general', 'language': 'en', 'country': 'us'},
    {'id': 'cnbc', 'name': 'CNBC',
     'description': 'Get latest business news on stock markets, financial & earnings on CNBC. View world markets streaming charts & video; check stock tickers and quotes.',
     'url': 'http://www.cnbc.com', 'category': 'business', 'language': 'en', 'country': 'us'},
    {'id': 'cnn', 'name': 'CNN',
     'description': 'View the latest news and breaking news today for U.S., world, weather, entertainment, politics and health at CNN',
     'url': 'http://us.cnn.com', 'category': 'general', 'language': 'en', 'country': 'us'},
    {'id': 'cnn-es', 'name': 'CNN Spanish',
     'description': 'Lee las últimas noticias e información sobre Latinoamérica, Estados Unidos, mundo, entretenimiento, política, salud, tecnología y deportes en CNNEspañol.com.',
     'url': 'http://cnnespanol.cnn.com/', 'category': 'general', 'language': 'es', 'country': 'us'},
    {'id': 'crypto-coins-news', 'name': 'Crypto Coins News',
     'description': 'Providing breaking cryptocurrency news - focusing on Bitcoin, Ethereum, ICOs, blockchain technology, and smart contracts.',
     'url': 'https://www.ccn.com', 'category': 'technology', 'language': 'en', 'country': 'us'},
    {'id': 'der-tagesspiegel', 'name': 'Der Tagesspiegel',
     'description': 'Nachrichten, News und neueste Meldungen aus dem Inland und dem Ausland - aktuell präsentiert von tagesspiegel.de.',
     'url': 'http://www.tagesspiegel.de', 'category': 'general', 'language': 'de', 'country': 'de'},
    {'id': 'die-zeit', 'name': 'Die Zeit',
     'description': 'Aktuelle Nachrichten, Kommentare, Analysen und Hintergrundberichte aus Politik, Wirtschaft, Gesellschaft, Wissen, Kultur und Sport lesen Sie auf ZEIT ONLINE.',
     'url': 'http://www.zeit.de/index', 'category': 'business', 'language': 'de', 'country': 'de'},
    {'id': 'el-mundo', 'name': 'El Mundo',
     'description': 'Noticias, actualidad, álbumes, debates, sociedad, servicios, entretenimiento y última hora en España y el mundo.',
     'url': 'http://www.elmundo.es', 'category': 'general', 'language': 'es', 'country': 'es'},
    {'id': 'engadget', 'name': 'Engadget',
     'description': 'Engadget is a web magazine with obsessive daily coverage of everything new in gadgets and consumer electronics.',
     'url': 'https://www.engadget.com', 'category': 'technology', 'language': 'en', 'country': 'us'},
    {'id': 'entertainment-weekly', 'name': 'Entertainment Weekly',
     'description': 'Online version of the print magazine includes entertainment news, interviews, reviews of music, film, TV and books, and a special area for magazine subscribers.',
     'url': 'http://www.ew.com', 'category': 'entertainment', 'language': 'en', 'country': 'us'},
    {'id': 'espn', 'name': 'ESPN',
     'description': 'ESPN has up-to-the-minute sports news coverage, scores, highlights and commentary for NFL, MLB, NBA, College Football, NCAA Basketball and more.',
     'url': 'http://espn.go.com', 'category': 'sports', 'language': 'en', 'country': 'us'},
    {'id': 'espn-cric-info', 'name': 'ESPN Cric Info',
     'description': 'ESPN Cricinfo provides the most comprehensive cricket coverage available including live ball-by-ball commentary, news, unparalleled statistics, quality editorial comment and analysis.',
     'url': 'http://www.espncricinfo.com/', 'category': 'sports', 'language': 'en', 'country': 'us'},
    {'id': 'financial-post', 'name': 'Financial Post',
     'description': 'Find the latest happenings in the Canadian Financial Sector and stay up to date with changing trends in Business Markets. Read trading and investing advice from professionals.',
     'url': 'http://business.financialpost.com', 'category': 'business', 'language': 'en', 'country': 'ca'},
    {'id': 'focus', 'name': 'Focus',
     'description': 'Minutenaktuelle Nachrichten und Service-Informationen von Deutschlands modernem Nachrichtenmagazin.',
     'url': 'http://www.focus.de', 'category': 'general', 'language': 'de', 'country': 'de'},
    {'id': 'football-italia', 'name': 'Football Italia',
     'description': 'Italian football news, analysis, fixtures and results for the latest from Serie A, Serie B and the Azzurri.',
     'url': 'http://www.football-italia.net', 'category': 'sports', 'language': 'en', 'country': 'it'},
    {'id': 'fortune', 'name': 'Fortune', 'description': 'Fortune 500 Daily and Breaking Business News',
     'url': 'http://fortune.com', 'category': 'business', 'language': 'en', 'country': 'us'},
    {'id': 'four-four-two', 'name': 'FourFourTwo',
     'description': 'The latest football news, in-depth features, tactical and statistical analysis from FourFourTwo, the UK&#039;s favourite football monthly.',
     'url': 'http://www.fourfourtwo.com/news', 'category': 'sports', 'language': 'en', 'country': 'gb'},
    {'id': 'fox-news', 'name': 'Fox News',
     'description': 'Breaking News, Latest News and Current News from FOXNews.com. Breaking news and video. Latest Current News: U.S., World, Entertainment, Health, Business, Technology, Politics, Sports.',
     'url': 'http://www.foxnews.com', 'category': 'general', 'language': 'en', 'country': 'us'},
    {'id': 'fox-sports', 'name': 'Fox Sports',
     'description': 'Find live scores, player and team news, videos, rumors, stats, standings, schedules and fantasy games on FOX Sports.',
     'url': 'http://www.foxsports.com', 'category': 'sports', 'language': 'en', 'country': 'us'},
    {'id': 'globo', 'name': 'Globo',
     'description': 'Só na globo.com você encontra tudo sobre o conteúdo e marcas do Grupo Globo. O melhor acervo de vídeos online sobre entretenimento, esportes e jornalismo do Brasil.',
     'url': 'http://www.globo.com/', 'category': 'general', 'language': 'pt', 'country': 'br'},
    {'id': 'google-news', 'name': 'Google News',
     'description': 'Comprehensive, up-to-date news coverage, aggregated from sources all over the world by Google News.',
     'url': 'https://news.google.com', 'category': 'general', 'language': 'en', 'country': 'us'},
    {'id': 'google-news-ar', 'name': 'Google News (Argentina)',
     'description': 'Completa cobertura actualizada de noticias agregadas a partir de fuentes de todo el mundo por Google Noticias.',
     'url': 'https://news.google.com', 'category': 'general', 'language': 'es', 'country': 'ar'},
    {'id': 'google-news-au', 'name': 'Google News (Australia)',
     'description': 'Comprehensive, up-to-date Australia news coverage, aggregated from sources all over the world by Google News.',
     'url': 'https://news.google.com', 'category': 'general', 'language': 'en', 'country': 'au'},
    {'id': 'google-news-br', 'name': 'Google News (Brasil)',
     'description': 'Cobertura jornalística abrangente e atualizada, agregada de fontes do mundo inteiro pelo Google Notícias.',
     'url': 'https://news.google.com', 'category': 'general', 'language': 'pt', 'country': 'br'},
    {'id': 'google-news-ca', 'name': 'Google News (Canada)',
     'description': 'Comprehensive, up-to-date Canada news coverage, aggregated from sources all over the world by Google News.',
     'url': 'https://news.google.com', 'category': 'general', 'language': 'en', 'country': 'ca'},
    {'id': 'google-news-fr', 'name': 'Google News (France)',
     'description': 'Informations complètes et à jour, compilées par Google Actualités à partir de sources d&#39;actualités du monde entier.',
     'url': 'https://news.google.com', 'category': 'general', 'language': 'fr', 'country': 'fr'},
    {'id': 'google-news-in', 'name': 'Google News (India)',
     'description': 'Comprehensive, up-to-date India news coverage, aggregated from sources all over the world by Google News.',
     'url': 'https://news.google.com', 'category': 'general', 'language': 'en', 'country': 'in'},
    {'id': 'google-news-is', 'name': 'Google News (Israel)',
     'description': 'כיסוי מקיף ועדכני של חדשות שהצטברו ממקורות בכל העולם על ידי &#39;חדשות Google&#39;.',
     'url': 'https://news.google.com', 'category': 'general', 'language': 'he', 'country': 'is'},
    {'id': 'google-news-it', 'name': 'Google News (Italy)',
     'description': 'Copertura giornalistica completa e aggiornata ottenuta combinando fonti di notizie in tutto il mondo attraverso Google News.',
     'url': 'https://news.google.com', 'category': 'general', 'language': 'it', 'country': 'it'},
    {'id': 'google-news-ru', 'name': 'Google News (Russia)',
     'description': 'Исчерпывающая и актуальная информация, собранная службой &quot;Новости Google&quot; со всего света.',
     'url': 'https://news.google.com', 'category': 'general', 'language': 'ru', 'country': 'ru'},
    {'id': 'google-news-sa', 'name': 'Google News (Saudi Arabia)',
     'description': 'تغطية شاملة ومتجددة للأخبار، تم جمعها من مصادر أخبار من جميع أنحاء العالم بواسطة أخبار Google.',
     'url': 'https://news.google.com', 'category': 'general', 'language': 'ar', 'country': 'sa'},
    {'id': 'google-news-uk', 'name': 'Google News (UK)',
     'description': 'Comprehensive, up-to-date UK news coverage, aggregated from sources all over the world by Google News.',
     'url': 'https://news.google.com', 'category': 'general', 'language': 'en', 'country': 'gb'},
    {'id': 'goteborgs-posten', 'name': 'Göteborgs-Posten',
     'description': 'Göteborgs-Posten, abbreviated GP, is a major Swedish language daily newspaper published in Gothenburg, Sweden.',
     'url': 'http://www.gp.se', 'category': 'general', 'language': 'se', 'country': 'se'},
    {'id': 'gruenderszene', 'name': 'Gruenderszene',
     'description': 'Online-Magazin für Startups und die digitale Wirtschaft. News und Hintergründe zu Investment, VC und Gründungen.',
     'url': 'http://www.gruenderszene.de', 'category': 'technology', 'language': 'de', 'country': 'de'},
    {'id': 'hacker-news', 'name': 'Hacker News',
     'description': 'Hacker News is a social news website focusing on computer science and entrepreneurship. It is run by Paul Graham\'s investment fund and startup incubator, Y Combinator. In general, content that can be submitted is defined as "anything that gratifies one\'s intellectual curiosity".',
     'url': 'https://news.ycombinator.com', 'category': 'technology', 'language': 'en', 'country': 'us'},
    {'id': 'handelsblatt', 'name': 'Handelsblatt',
     'description': 'Auf Handelsblatt lesen sie Nachrichten über Unternehmen, Finanzen, Politik und Technik. Verwalten Sie Ihre Finanzanlagen mit Hilfe unserer Börsenkurse.',
     'url': 'http://www.handelsblatt.com', 'category': 'business', 'language': 'de', 'country': 'de'},
    {'id': 'ign', 'name': 'IGN',
     'description': 'IGN is your site for Xbox One, PS4, PC, Wii-U, Xbox 360, PS3, Wii, 3DS, PS Vita and iPhone games with expert reviews, news, previews, trailers, cheat codes, wiki guides and walkthroughs.',
     'url': 'http://www.ign.com', 'category': 'entertainment', 'language': 'en', 'country': 'us'},
    {'id': 'il-sole-24-ore', 'name': 'Il Sole 24 Ore',
     'description': 'Notizie di economia, cronaca italiana ed estera, quotazioni borsa in tempo reale e di finanza, norme e tributi, fondi e obbligazioni, mutui, prestiti e lavoro a cura de Il Sole 24 Ore.',
     'url': 'https://www.ilsole24ore.com', 'category': 'business', 'language': 'it', 'country': 'it'},
    {'id': 'independent', 'name': 'Independent',
     'description': 'National morning quality (tabloid) includes free online access to news and supplements. Insight by Robert Fisk and various other columnists.',
     'url': 'http://www.independent.co.uk', 'category': 'general', 'language': 'en', 'country': 'gb'},
    {'id': 'infobae', 'name': 'Infobae',
     'description': 'Noticias de Argentina y del mundo en tiempo real. Información, videos y fotos sobre los hechos más relevantes y sus protagonistas. Léelo antes en infobae.',
     'url': 'http://www.infobae.com/?noredirect', 'category': 'general', 'language': 'es', 'country': 'ar'},
    {'id': 'info-money', 'name': 'InfoMoney',
     'description': 'No InfoMoney você encontra tudo o que precisa sobre dinheiro. Ações, investimentos, bolsas de valores e muito mais. Aqui você encontra informação que vale dinheiro!',
     'url': 'https://www.infomoney.com.br', 'category': 'business', 'language': 'pt', 'country': 'br'},
    {'id': 'la-gaceta', 'name': 'La Gaceta',
     'description': 'El diario de Tucumán, noticias 24 horas online - San Miguel de Tucumán - Argentina - Ultimo momento - Ultimas noticias.',
     'url': 'http://www.lagaceta.com.ar', 'category': 'general', 'language': 'es', 'country': 'ar'},
    {'id': 'la-nacion', 'name': 'La Nacion',
     'description': 'Información confiable en Internet. Noticias de Argentina y del mundo - ¡Informate ya!',
     'url': 'http://www.lanacion.com.ar', 'category': 'general', 'language': 'es', 'country': 'ar'},
    {'id': 'la-repubblica', 'name': 'La Repubblica',
     'description': 'Breaking News, Latest News and Current News from FOXNews.com. Breaking news and video. Latest Current News: U.S., World, Entertainment, Health, Business, Technology, Politics, Sports.',
     'url': 'http://www.repubblica.it', 'category': 'general', 'language': 'it', 'country': 'it'},
    {'id': 'le-monde', 'name': 'Le Monde',
     'description': "Les articles du journal et toute l'actualit&eacute; en continu : International, France, Soci&eacute;t&eacute;, Economie, Culture, Environnement, Blogs ...",
     'url': 'http://www.lemonde.fr', 'category': 'general', 'language': 'fr', 'country': 'fr'},
    {'id': 'lenta', 'name': 'Lenta',
     'description': 'Новости, статьи, фотографии, видео. Семь дней в неделю, 24 часа в сутки.',
     'url': 'https://lenta.ru', 'category': 'general', 'language': 'ru', 'country': 'ru'},
    {'id': 'lequipe', 'name': "L'equipe",
     'description': "Le sport en direct sur L'EQUIPE.fr. Les informations, résultats et classements de tous les sports. Directs commentés, images et vidéos à regarder et à partager !",
     'url': 'https://www.lequipe.fr', 'category': 'sports', 'language': 'fr', 'country': 'fr'},
    {'id': 'les-echos', 'name': 'Les Echos',
     'description': "Toute l'actualité économique, financière et boursière française et internationale sur Les Echos.fr",
     'url': 'https://www.lesechos.fr', 'category': 'business', 'language': 'fr', 'country': 'fr'},
    {'id': 'liberation', 'name': 'Libération',
     'description': "Toute l'actualité en direct - photos et vidéos avec Libération",
     'url': 'http://www.liberation.fr', 'category': 'general', 'language': 'fr', 'country': 'fr'},
    {'id': 'marca', 'name': 'Marca',
     'description': 'La mejor información deportiva en castellano actualizada minuto a minuto en noticias, vídeos, fotos, retransmisiones y resultados en directo.',
     'url': 'http://www.marca.com', 'category': 'sports', 'language': 'es', 'country': 'es'},
    {'id': 'mashable', 'name': 'Mashable',
     'description': 'Mashable is a global, multi-platform media and entertainment company.',
     'url': 'https://mashable.com', 'category': 'entertainment', 'language': 'en', 'country': 'us'},
    {'id': 'medical-news-today', 'name': 'Medical News Today',
     'description': 'Medical news and health news headlines posted throughout the day, every day.',
     'url': 'http://www.medicalnewstoday.com', 'category': 'health', 'language': 'en', 'country': 'us'},
    {'id': 'msnbc', 'name': 'MSNBC',
     'description': 'Breaking news and in-depth analysis of the headlines, as well as commentary and informed perspectives from The Rachel Maddow Show, Morning Joe & more.',
     'url': 'http://www.msnbc.com', 'category': 'general', 'language': 'en', 'country': 'us'},
    {'id': 'mtv-news', 'name': 'MTV News',
     'description': "The ultimate news source for music, celebrity, entertainment, movies, and current events on the web. It's pop culture on steroids.",
     'url': 'http://www.mtv.com/news', 'category': 'entertainment', 'language': 'en', 'country': 'us'},
    {'id': 'mtv-news-uk', 'name': 'MTV News (UK)',
     'description': 'All the latest celebrity news, gossip, exclusive interviews and pictures from the world of music and entertainment.',
     'url': 'http://www.mtv.co.uk/news', 'category': 'entertainment', 'language': 'en', 'country': 'gb'},
    {'id': 'national-geographic', 'name': 'National Geographic',
     'description': 'Reporting our world daily: original nature and science news from National Geographic.',
     'url': 'http://news.nationalgeographic.com', 'category': 'science', 'language': 'en', 'country': 'us'},
    {'id': 'national-review', 'name': 'National Review',
     'description': 'National Review: Conservative News, Opinion, Politics, Policy, & Current Events.',
     'url': 'https://www.nationalreview.com/', 'category': 'general', 'language': 'en', 'country': 'us'},
    {'id': 'nbc-news', 'name': 'NBC News',
     'description': 'Breaking news, videos, and the latest top stories in world news, business, politics, health and pop culture.',
     'url': 'http://www.nbcnews.com', 'category': 'general', 'language': 'en', 'country': 'us'},
    {'id': 'news24', 'name': 'News24',
     'description': "South Africa's premier news source, provides breaking news on national, world, Africa, sport, entertainment, technology and more.",
     'url': 'http://www.news24.com', 'category': 'general', 'language': 'en', 'country': 'za'},
    {'id': 'new-scientist', 'name': 'New Scientist',
     'description': 'Breaking science and technology news from around the world. Exclusive stories and expert analysis on space, technology, health, physics, life and Earth.',
     'url': 'https://www.newscientist.com/section/news', 'category': 'science', 'language': 'en',
     'country': 'us'}, {'id': 'news-com-au', 'name': 'News.com.au',
                        'description': 'We say what people are thinking and cover the issues that get people talking balancing Australian and global moments — from politics to pop culture.',
                        'url': 'http://www.news.com.au', 'category': 'general', 'language': 'en',
                        'country': 'au'}, {'id': 'newsweek', 'name': 'Newsweek',
                                           'description': 'Newsweek provides in-depth analysis, news and opinion about international issues, technology, business, culture and politics.',
                                           'url': 'https://www.newsweek.com', 'category': 'general',
                                           'language': 'en', 'country': 'us'},
    {'id': 'new-york-magazine', 'name': 'New York Magazine',
     'description': 'NYMAG and New York magazine cover the new, the undiscovered, the next in politics, culture, food, fashion, and behavior nationally, through a New York lens.',
     'url': 'http://nymag.com', 'category': 'general', 'language': 'en', 'country': 'us'},
    {'id': 'next-big-future', 'name': 'Next Big Future',
     'description': 'Coverage of science and technology that have the potential for disruption, and analysis of plans, policies, and technology that enable radical improvement.',
     'url': 'https://www.nextbigfuture.com', 'category': 'science', 'language': 'en', 'country': 'us'},
    {'id': 'nfl-news', 'name': 'NFL News',
     'description': 'The official source for NFL news, schedules, stats, scores and more.',
     'url': 'http://www.nfl.com/news', 'category': 'sports', 'language': 'en', 'country': 'us'},
    {'id': 'nhl-news', 'name': 'NHL News',
     'description': 'The most up-to-date breaking hockey news from the official source including interviews, rumors, statistics and schedules.',
     'url': 'https://www.nhl.com/news', 'category': 'sports', 'language': 'en', 'country': 'us'},
    {'id': 'nrk', 'name': 'NRK',
     'description': 'NRK er Norges største tilbud på nett: nyheter fra Norge og verden, lokalnyheter, radio- og tv-program, podcast, vær, helse-, kultur-, underholdning-, humor- og debattstoff.',
     'url': 'https://www.nrk.no', 'category': 'general', 'language': 'no', 'country': 'no'},
    {'id': 'politico', 'name': 'Politico',
     'description': 'Political news about Congress, the White House, campaigns, lobbyists and issues.',
     'url': 'https://www.politico.com', 'category': 'general', 'language': 'en', 'country': 'us'},
    {'id': 'polygon', 'name': 'Polygon',
     'description': 'Polygon is a gaming website in partnership with Vox Media. Our culture focused site covers games, their creators, the fans, trending stories and entertainment news.',
     'url': 'http://www.polygon.com', 'category': 'entertainment', 'language': 'en', 'country': 'us'},
    {'id': 'rbc', 'name': 'RBC',
     'description': 'Главные новости политики, экономики и бизнеса, комментарии аналитиков, финансовые данные с российских и мировых биржевых систем на сайте rbc.ru.',
     'url': 'https://www.rbc.ru', 'category': 'general', 'language': 'ru', 'country': 'ru'},
    {'id': 'recode', 'name': 'Recode',
     'description': 'Get the latest independent tech news, reviews and analysis from Recode with the most informed and respected journalists in technology and media.',
     'url': 'http://www.recode.net', 'category': 'technology', 'language': 'en', 'country': 'us'},
    {'id': 'reddit-r-all', 'name': 'Reddit /r/all',
     'description': "Reddit is an entertainment, social news networking service, and news website. Reddit's registered community members can submit content, such as text posts or direct links.",
     'url': 'https://www.reddit.com/r/all', 'category': 'general', 'language': 'en', 'country': 'us'},
    {'id': 'reuters', 'name': 'Reuters',
     'description': 'Reuters.com brings you the latest news from around the world, covering breaking news in business, politics, entertainment, technology, video and pictures.',
     'url': 'http://www.reuters.com', 'category': 'general', 'language': 'en', 'country': 'us'},
    {'id': 'rt', 'name': 'RT',
     'description': 'Актуальная картина дня на RT: круглосуточное ежедневное обновление новостей политики, бизнеса, финансов, спорта, науки, культуры. Онлайн-репортажи с места событий. Комментарии экспертов, актуальные интервью, фото и видео репортажи.',
     'url': 'https://russian.rt.com', 'category': 'general', 'language': 'ru', 'country': 'ru'},
    {'id': 'rte', 'name': 'RTE',
     'description': "Get all of the latest breaking local and international news stories as they happen, with up to the minute updates and analysis, from Ireland's National Broadcaster.",
     'url': 'https://www.rte.ie/news', 'category': 'general', 'language': 'en', 'country': 'ie'},
    {'id': 'rtl-nieuws', 'name': 'RTL Nieuws',
     'description': 'Volg het nieuws terwijl het gebeurt. RTL Nieuws informeert haar lezers op een onafhankelijke, boeiende en toegankelijke wijze over belangrijke ontwikkelingen in eigen land en de rest van de wereld.',
     'url': 'https://www.rtlnieuws.nl/', 'category': 'general', 'language': 'nl', 'country': 'nl'},
    {'id': 'sabq', 'name': 'SABQ',
     'description': 'صحيفة الكترونية سعودية هدفها السبق في نقل الحدث بمهنية ومصداقية خدمة للوطن والمواطن.',
     'url': 'https://sabq.org', 'category': 'general', 'language': 'ar', 'country': 'sa'},
    {'id': 'spiegel-online', 'name': 'Spiegel Online',
     'description': 'Deutschlands führende Nachrichtenseite. Alles Wichtige aus Politik, Wirtschaft, Sport, Kultur, Wissenschaft, Technik und mehr.',
     'url': 'http://www.spiegel.de', 'category': 'general', 'language': 'de', 'country': 'de'},
    {'id': 'svenska-dagbladet', 'name': 'Svenska Dagbladet',
     'description': 'Sveriges ledande mediesajt - SvD.se. Svenska Dagbladets nyhetssajt låter läsarna ta plats och fördjupar nyheterna.',
     'url': 'https://www.svd.se', 'category': 'general', 'language': 'se', 'country': 'se'},
    {'id': 't3n', 'name': 'T3n',
     'description': 'Das Online-Magazin bietet Artikel zu den Themen E-Business, Social Media, Startups und Webdesign.',
     'url': 'https://t3n.de', 'category': 'technology', 'language': 'de', 'country': 'de'},
    {'id': 'talksport', 'name': 'TalkSport',
     'description': "Tune in to the world's biggest sports radio station - Live Premier League football coverage, breaking sports news, transfer rumours &amp; exclusive interviews.",
     'url': 'http://talksport.com', 'category': 'sports', 'language': 'en', 'country': 'gb'},
    {'id': 'techcrunch', 'name': 'TechCrunch',
     'description': 'TechCrunch is a leading technology media property, dedicated to obsessively profiling startups, reviewing new Internet products, and breaking tech news.',
     'url': 'https://techcrunch.com', 'category': 'technology', 'language': 'en', 'country': 'us'},
    {'id': 'techcrunch-cn', 'name': 'TechCrunch (CN)',
     'description': 'TechCrunch is a leading technology media property, dedicated to obsessively profiling startups, reviewing new Internet products, and breaking tech news.',
     'url': 'https://techcrunch.cn', 'category': 'technology', 'language': 'zh', 'country': 'zh'},
    {'id': 'techradar', 'name': 'TechRadar',
     'description': 'The latest technology news and reviews, covering computing, home entertainment systems, gadgets and more.',
     'url': 'http://www.techradar.com', 'category': 'technology', 'language': 'en', 'country': 'us'},
    {'id': 'the-american-conservative', 'name': 'The American Conservative',
     'description': 'Realism and reform. A new voice for a new generation of conservatives.',
     'url': 'http://www.theamericanconservative.com/', 'category': 'general', 'language': 'en',
     'country': 'us'}, {'id': 'the-globe-and-mail', 'name': 'The Globe And Mail',
                        'description': 'The Globe and Mail offers the most authoritative news in Canada, featuring national and international news.',
                        'url': 'https://www.theglobeandmail.com', 'category': 'general', 'language': 'en',
                        'country': 'ca'}, {'id': 'the-hill', 'name': 'The Hill',
                                           'description': 'The Hill is a top US political website, read by the White House and more lawmakers than any other site -- vital for policy, politics and election campaigns.',
                                           'url': 'http://thehill.com', 'category': 'general', 'language': 'en',
                                           'country': 'us'}, {'id': 'the-hindu', 'name': 'The Hindu',
                                                              'description': "The Hindu. latest news, analysis, comment, in-depth coverage of politics, business, sport, environment, cinema and arts from India's national newspaper.",
                                                              'url': 'http://www.thehindu.com',
                                                              'category': 'general', 'language': 'en',
                                                              'country': 'in'},
    {'id': 'the-huffington-post', 'name': 'The Huffington Post',
     'description': 'The Huffington Post is a politically liberal American online news aggregator and blog that has both localized and international editions founded by Arianna Huffington, Kenneth Lerer, Andrew Breitbart, and Jonah Peretti, featuring columnists.',
     'url': 'http://www.huffingtonpost.com', 'category': 'general', 'language': 'en', 'country': 'us'},
    {'id': 'the-irish-times', 'name': 'The Irish Times',
     'description': 'The Irish Times online. Latest news including sport, analysis, business, weather and more from the definitive brand of quality news in Ireland.',
     'url': 'https://www.irishtimes.com', 'category': 'general', 'language': 'en', 'country': 'ie'},
    {'id': 'the-jerusalem-post', 'name': 'The Jerusalem Post',
     'description': 'The Jerusalem Post is the leading online newspaper for English speaking Jewry since 1932, bringing news and updates from the Middle East and all over the Jewish world.',
     'url': 'https://www.jpost.com/', 'category': 'general', 'language': 'en', 'country': 'is'},
    {'id': 'the-lad-bible', 'name': 'The Lad Bible',
     'description': 'The LAD Bible is one of the largest community for guys aged 16-30 in the world. Send us your funniest pictures and videos!',
     'url': 'https://www.theladbible.com', 'category': 'entertainment', 'language': 'en', 'country': 'gb'},
    {'id': 'the-next-web', 'name': 'The Next Web',
     'description': 'The Next Web is one of the world’s largest online publications that delivers an international perspective on the latest news about Internet technology, business and culture.',
     'url': 'http://thenextweb.com', 'category': 'technology', 'language': 'en', 'country': 'us'},
    {'id': 'the-sport-bible', 'name': 'The Sport Bible',
     'description': 'TheSPORTbible is one of the largest communities for sports fans across the world. Send us your sporting pictures and videos!',
     'url': 'https://www.thesportbible.com', 'category': 'sports', 'language': 'en', 'country': 'gb'},
    {'id': 'the-times-of-india', 'name': 'The Times of India',
     'description': 'Times of India brings the Latest News and Top Breaking headlines on Politics and Current Affairs in India and around the World, Sports, Business, Bollywood News and Entertainment, Science, Technology, Health and Fitness news, Cricket and opinions from leading columnists.',
     'url': 'http://timesofindia.indiatimes.com', 'category': 'general', 'language': 'en', 'country': 'in'},
    {'id': 'the-verge', 'name': 'The Verge',
     'description': 'The Verge covers the intersection of technology, science, art, and culture.',
     'url': 'http://www.theverge.com', 'category': 'technology', 'language': 'en', 'country': 'us'},
    {'id': 'the-wall-street-journal', 'name': 'The Wall Street Journal',
     'description': 'WSJ online coverage of breaking news and current headlines from the US and around the world. Top stories, photos, videos, detailed analysis and in-depth reporting.',
     'url': 'http://www.wsj.com', 'category': 'business', 'language': 'en', 'country': 'us'},
    {'id': 'the-washington-post', 'name': 'The Washington Post',
     'description': 'Breaking news and analysis on politics, business, world national news, entertainment more. In-depth DC, Virginia, Maryland news coverage including traffic, weather, crime, education, restaurant reviews and more.',
     'url': 'https://www.washingtonpost.com', 'category': 'general', 'language': 'en', 'country': 'us'},
    {'id': 'the-washington-times', 'name': 'The Washington Times',
     'description': 'The Washington Times delivers breaking news and commentary on the issues that affect the future of our nation.',
     'url': 'https://www.washingtontimes.com/', 'category': 'general', 'language': 'en', 'country': 'us'},
    {'id': 'time', 'name': 'Time',
     'description': 'Breaking news and analysis from TIME.com. Politics, world news, photos, video, tech reviews, health, science and entertainment news.',
     'url': 'http://time.com', 'category': 'general', 'language': 'en', 'country': 'us'},
    {'id': 'usa-today', 'name': 'USA Today',
     'description': 'Get the latest national, international, and political news at USATODAY.com.',
     'url': 'http://www.usatoday.com/news', 'category': 'general', 'language': 'en', 'country': 'us'},
    {'id': 'vice-news', 'name': 'Vice News',
     'description': 'Vice News is Vice Media, Inc.\'s current affairs channel, producing daily documentary essays and video through its website and YouTube channel. It promotes itself on its coverage of "under - reported stories".',
     'url': 'https://news.vice.com', 'category': 'general', 'language': 'en', 'country': 'us'},
    {'id': 'wired', 'name': 'Wired',
     'description': 'Wired is a monthly American magazine, published in print and online editions, that focuses on how emerging technologies affect culture, the economy, and politics.',
     'url': 'https://www.wired.com', 'category': 'technology', 'language': 'en', 'country': 'us'},
    {'id': 'wired-de', 'name': 'Wired.de',
     'description': 'Wired reports on how emerging technologies affect culture, the economy and politics.',
     'url': 'https://www.wired.de', 'category': 'technology', 'language': 'de', 'country': 'de'},
    {'id': 'wirtschafts-woche', 'name': 'Wirtschafts Woche',
     'description': 'Das Online-Portal des führenden Wirtschaftsmagazins in Deutschland. Das Entscheidende zu Unternehmen, Finanzen, Erfolg und Technik.',
     'url': 'http://www.wiwo.de', 'category': 'business', 'language': 'de', 'country': 'de'},
    {'id': 'xinhua-net', 'name': 'Xinhua Net',
     'description': '中国主要重点新闻网站,依托新华社遍布全球的采编网络,记者遍布世界100多个国家和地区,地方频道分布全国31个省市自治区,每天24小时同时使用6种语言滚动发稿,权威、准确、及时播发国内外重要新闻和重大突发事件,受众覆盖200多个国家和地区,发展论坛是全球知名的中文论坛。',
     'url': 'http://xinhuanet.com/', 'category': 'general', 'language': 'zh', 'country': 'zh'},
    {'id': 'ynet', 'name': 'Ynet',
     'description': 'ynet דף הבית: אתר החדשות המוביל בישראל מבית ידיעות אחרונות. סיקור מלא של חדשות מישראל והעולם, ספורט, כלכלה, תרבות, אוכל, מדע וטבע, כל מה שקורה וכל מה שמעניין ב ynet.',
     'url': 'http://www.ynet.co.il', 'category': 'general', 'language': 'he', 'country': 'is'}]}
