search_success_reponse = {'events': [
    {'attending_count': 5, 'category': 'food-and-drink', 'cost': None, 'cost_max': None,
     'description': 'The 10th Annual Seafood Festival itself will be:\n\nSaturday, February 25, 2017\n11:00am - 5:00pm\nShelter Cove Community Park \n\nThe family friendly headlining...',
     'event_site_url': 'https://www.yelp.co.uk/events/hilton-head-island-10th-annual-hilton-head-island-seafood-festival?adjust_creative=s4TB2oNJKW1zRFSbBUC-hw&utm_campaign=yelp_api_v3&utm_medium=api_v3_event_search&utm_source=s4TB2oNJKW1zRFSbBUC-hw',
     'id': 'hilton-head-island-10th-annual-hilton-head-island-seafood-festival',
     'image_url': 'https://s3-media3.fl.yelpcdn.com/ephoto/D8Qf6j3heMUxgMP-9uBoZA/o.jpg', 'interested_count': 4,
     'is_canceled': False, 'is_free': True, 'is_official': False, 'latitude': 32.1864131, 'longitude': -80.721556,
     'name': '10th Annual Hilton Head Island Seafood Festival', 'tickets_url': None,
     'time_end': '2017-02-26T00:00:00-05:00', 'time_start': '2017-02-20T00:00:00-05:00',
     'location': {'address1': '39 Shelter Cove Lane', 'address2': '', 'address3': '', 'city': 'Hilton Head Island',
                  'zip_code': '29928', 'country': 'US', 'state': 'SC',
                  'display_address': ['39 Shelter Cove Lane, Hilton Head Island, SC 29928'], 'cross_streets': ''},
     'business_id': None}, {'attending_count': 2, 'category': 'festivals-fairs', 'cost': 10.0, 'cost_max': 15.0,
                            'description': 'Featured presentations at the Juneteenth Celebration include:\nJoseph McGill of the award-winning Slave Dwelling Project\nMarlena Smalls and the Hallelujah...',
                            'event_site_url': 'https://www.yelp.co.uk/events/hilton-head-island-juneteenth-celebration-at-mitchelville?adjust_creative=s4TB2oNJKW1zRFSbBUC-hw&utm_campaign=yelp_api_v3&utm_medium=api_v3_event_search&utm_source=s4TB2oNJKW1zRFSbBUC-hw',
                            'id': 'hilton-head-island-juneteenth-celebration-at-mitchelville',
                            'image_url': 'https://s3-media1.fl.yelpcdn.com/ephoto/pr2Zyra_jQ1sUrTq9CWdUw/o.jpg',
                            'interested_count': 3, 'is_canceled': False, 'is_free': False, 'is_official': False,
                            'latitude': 32.238368, 'longitude': -80.687762,
                            'name': 'Juneteenth Celebration at Mitchelville',
                            'tickets_url': 'http://exploremitchelville.org/events/juneteenth-tickets',
                            'time_end': '2017-06-17T17:00:00-04:00', 'time_start': '2017-06-17T10:00:00-04:00',
                            'location': {'address1': '229 Beach City Road', 'address2': '', 'address3': '',
                                         'city': 'Hilton Head Island', 'zip_code': '29926', 'country': 'US',
                                         'state': 'SC',
                                         'display_address': ['229 Beach City Rd, Hilton Head Island, SC 29926'],
                                         'cross_streets': ''}, 'business_id': None},
    {'attending_count': 7, 'category': 'festivals-fairs', 'cost': None, 'cost_max': None,
     'description': 'Experience the food and music, receive firsthand, historical information and take a journey through the culture via the visual arts. Visit website for...',
     'event_site_url': 'https://www.yelp.co.uk/events/hilton-head-island-22nd-annual-hilton-head-island-gullah-celebration?adjust_creative=s4TB2oNJKW1zRFSbBUC-hw&utm_campaign=yelp_api_v3&utm_medium=api_v3_event_search&utm_source=s4TB2oNJKW1zRFSbBUC-hw',
     'id': 'hilton-head-island-22nd-annual-hilton-head-island-gullah-celebration',
     'image_url': 'https://s3-media2.fl.yelpcdn.com/ephoto/QXqel3gw9RLhHVtQnTe7uA/o.jpg', 'interested_count': 9,
     'is_canceled': False, 'is_free': False, 'is_official': False, 'latitude': 32.1865132658581,
     'longitude': -80.7217853835875, 'name': '22nd Annual Hilton Head Island Gullah Celebration', 'tickets_url': '',
     'time_end': '2018-02-28T00:00:00-05:00', 'time_start': '2018-02-01T00:00:00-05:00',
     'location': {'address1': '39 Shelter Cove Ln', 'address2': '', 'address3': None, 'city': 'Hilton Head Island',
                  'zip_code': '29928', 'country': 'US', 'state': 'SC',
                  'display_address': ['39 Shelter Cove Ln', 'Hilton Head Island, SC 29928', 'United States'],
                  'cross_streets': ''}, 'business_id': 'shelter-cover-community-park-hilton-head-island'}], 'total': 3}
