
search_success_response = {'timestamp': 1579714500, 'articleCount': 10, 'articles': [
    {'title': 'Recovering Lost Sales with Facebook Messenger Marketing',
     'description': 'With Facebook Messenger marketing, ecommerce companies can connect with shoppers and site visitors directly through Facebook chatbots, creating a new channel for engagement. Similar to email marketing ...',
     'url': 'https://multichannelmerchant.com/blog/recovering-lost-sales-facebook-messenger-marketing/',
     'image': 'https://images.gnews.io/a1fcd0818cbc64341e6e8b8c8cde5897', 'publishedAt': '2020-01-17 12:35:00 UTC',
     'source': {'name': 'Multichannel Merchant', 'url': 'https://multichannelmerchant.com'}},
    {'title': 'How to grow your business in 2020: The essential marketing toolkit you need in your arsenal',
     'description': 'Also, chatbots offer a 24-hour service and eliminate the delay that comes with customer reps. This is where LivePerson comes in. LivePerson uses artificial intelligence to automate up to 70% of ...',
     'url': 'https://www.smartinsights.com/managing-digital-marketing/growth-hacking/how-to-grow-your-business-in-2020/',
     'image': None, 'publishedAt': '2020-01-15 08:32:00 UTC',
     'source': {'name': 'Smart Insights', 'url': 'https://www.smartinsights.com'}},
    {'title': 'Chatbots Market Assessment of Competitors 2020-2029',
     'description': 'Global News for Chatbots Market Study 2020-2029, by Segment (TalkBot, Elbot, ELise), Playing a Pivotal Role in Expanding by (Phone, Pad, Desktop PC, Laptop), Investment Analysis by Leading ...',
     'url': 'https://www.marketwatch.com/press-release/chatbots-market-assessment-of-competitors-2020-2029-2020-01-15',
     'image': None, 'publishedAt': '2020-01-15 03:46:00 UTC',
     'source': {'name': 'MarketWatch', 'url': 'https://www.marketwatch.com'}},
    {'title': 'Global Advanced Chatbots Market 2019 EGain Coporation, Creative Virtual, Next IT Corp',
     'description': 'Access complete report here @ http://www.marketresearchstore.com/report/global-advanced-chatbots-market-report-2019-651858 The examination underlines the immense driving business players : Artificial ...',
     'url': 'https://www.openpr.com/news/1895901/global-advanced-chatbots-market-2019-egain-coporation', 'image': None,
     'publishedAt': '2020-01-14 04:31:00 UTC', 'source': {'name': 'openpr.com', 'url': 'https://www.openpr.com'}},
    {'title': 'AI in marketing: How to find the right use cases, people and technology',
     'description': 'Among the common use cases are the following: intelligent chatbots, smarter personalized digital advertising, content generation and curation, AI-powered account or lead scoring, AI-assisted email ...',
     'url': 'https://www.clickz.com/ai-in-marketing-how-to-find-the-right-use-cases-people-and-technology/259376/',
     'image': 'https://images.gnews.io/0a9cd2f2a023dcbd09a43c69bfc91386', 'publishedAt': '2020-01-10 05:03:00 UTC',
     'source': {'name': 'ClickZ', 'url': 'https://www.clickz.com'}},
    {'title': 'Five Conversational AI Predictions For 2020',
     'description': 'The year 2020 will be an exciting time for conversational artificial intelligence (AI), as chatbots join forces with other digital assistants and integrate deeper into back-end technologies to deliver ...',
     'url': 'https://www.forbes.com/sites/forbescommunicationscouncil/2020/01/10/five-conversational-ai-predictions-for-2020/',
     'image': 'https://images.gnews.io/0f6b8ddc6ccf18eaf535b219dc81103e', 'publishedAt': '2020-01-10 03:08:00 UTC',
     'source': {'name': 'Forbes', 'url': 'https://www.forbes.com'}}, {
        'title': 'Global Chatbots Market Grow with Noteworthy CAGR of around 35.08% by 2023| Accounted for USD 88.5 Million in 2015',
        'description': 'The global chatbots market has been segmented by end-use into large enterprise, small and medium sized enterprise, out of which, the large scale enterprise segment is estimated to be the largest ...',
        'url': 'https://www.marketwatch.com/press-release/global-chatbots-market-grow-with-noteworthy-cagr-of-around-3508-by-2023-accounted-for-usd-885-million-in-2015-2020-01-10',
        'image': None, 'publishedAt': '2020-01-10 01:41:00 UTC',
        'source': {'name': 'MarketWatch', 'url': 'https://www.marketwatch.com'}},
    {'title': 'The Chinese startup using chatbots to revolutionize hotel bookings',
     'description': 'The platform has signed deals with 25 partners while 120 more are in the pipeline, according to Wang. It also works with more than 100 travel content and product suppliers including Asian booking ...',
     'url': 'https://technode.com/2020/01/08/the-chinese-startup-using-chatbots-to-revolutionize-hotel-booking/',
     'image': 'https://images.gnews.io/2c547b4795e6b09055cf8c41f29d8ccf', 'publishedAt': '2020-01-08 20:00:00 UTC',
     'source': {'name': 'TechNode', 'url': 'https://technode.com'}},
    {'title': 'AI poses risks, but the White House says regulators shouldn’t “needlessly hamper” innovation',
     'description': 'Artificial intelligence is here, and it’s impacting our lives in real ways — whether it’s the Alexa smart speaker on our nightstand, online customer service chatbots, or the smart replies Google ...',
     'url': 'https://www.vox.com/recode/2020/1/8/21056809/artificial-intelligence-new-ai-principles-white-house',
     'image': 'https://images.gnews.io/0e368b57437de7a3654aade8782aff75', 'publishedAt': '2020-01-08 16:30:00 UTC',
     'source': {'name': 'Vox', 'url': 'https://www.vox.com'}},
    {'title': "Samsung's Neon 'artificial humans' look like super-realistic video chatbots",
     'description': "Samsung Neon isn't a robot or a voice assistant like Siri or Alexa. Instead, it's a simulated human assistant that appears on a screen and learns about people to help it give intelligent responses -- ...",
     'url': 'https://www.cnbc.com/2020/01/06/samsung-neon-artificial-human-announced-at-ces-2020.html',
     'image': 'https://images.gnews.io/214618b3fc601ad80704b8e2b20ba957', 'publishedAt': '2020-01-08 15:16:00 UTC',
     'source': {'name': 'CNBC', 'url': 'https://www.cnbc.com'}}]}

top_news_success_response = {"timestamp": 1583496614, "articleCount": 10, "articles": [
    {"title": "Coronavirus: Britons quarantined on cruise ship off San Francisco", "description": "",
     "url": "https:\/\/news.google.com\/__i\/rss\/rd\/articles\/CBMifWh0dHBzOi8vd3d3LnRoZWd1YXJkaWFuLmNvbS93b3JsZC8yMDIwL21hci8wNi9jb3JvbmF2aXJ1cy1icml0b25zLXF1YXJhbnRpbmVkLW9uLWNydWlzZS1zaGlwLW9mZi1zYW4tZnJhbmNpc2NvLWdyYW5kLXByaW5jZXNz0gF9aHR0cHM6Ly9hbXAudGhlZ3VhcmRpYW4uY29tL3dvcmxkLzIwMjAvbWFyLzA2L2Nvcm9uYXZpcnVzLWJyaXRvbnMtcXVhcmFudGluZWQtb24tY3J1aXNlLXNoaXAtb2ZmLXNhbi1mcmFuY2lzY28tZ3JhbmQtcHJpbmNlc3M?oc=5",
     "image": None, "publishedAt": "2020-03-06 10:03:00 UTC",
     "source": {"name": "The Guardian", "url": "https:\/\/www.theguardian.com"}},
    {"title": "Ceasefire in Syria after Russia and Turkey strike deal", "description": "",
     "url": "https:\/\/news.google.com\/__i\/rss\/rd\/articles\/CBMiW2h0dHBzOi8vbmV3cy5za3kuY29tL3N0b3J5L3J1c3NpYS1hbmQtdHVya2V5LWFncmVlLWNlYXNlZmlyZS1pbi1ub3J0aHdlc3Rlcm4tc3lyaWEtMTE5NTA0NDjSAV9odHRwczovL25ld3Muc2t5LmNvbS9zdG9yeS9hbXAvcnVzc2lhLWFuZC10dXJrZXktYWdyZWUtY2Vhc2VmaXJlLWluLW5vcnRod2VzdGVybi1zeXJpYS0xMTk1MDQ0OA?oc=5",
     "image": None, "publishedAt": "2020-03-05 22:30:00 UTC",
     "source": {"name": "Sky News", "url": "https:\/\/news.sky.com"}},
    {"title": "Vatican City reports its first case of coronavirus, days after Pope tested negative", "description": "",
     "url": "https:\/\/news.google.com\/__i\/rss\/rd\/articles\/CBMidWh0dHBzOi8vd3d3LmRhaWx5bWFpbC5jby51ay9uZXdzL2FydGljbGUtODA4MjI1OS9WYXRpY2FuLUNpdHktcmVwb3J0cy1jYXNlLWNvcm9uYXZpcnVzLWRheXMtUG9wZS10ZXN0ZWQtbmVnYXRpdmUuaHRtbNIBeWh0dHBzOi8vd3d3LmRhaWx5bWFpbC5jby51ay9uZXdzL2FydGljbGUtODA4MjI1OS9hbXAvVmF0aWNhbi1DaXR5LXJlcG9ydHMtY2FzZS1jb3JvbmF2aXJ1cy1kYXlzLVBvcGUtdGVzdGVkLW5lZ2F0aXZlLmh0bWw?oc=5",
     "image": None, "publishedAt": "2020-03-06 09:32:00 UTC",
     "source": {"name": "Daily Mail", "url": "https:\/\/www.dailymail.co.uk"}},
    {"title": "Bomb squad called and two held after suspicious device found in car in Luton", "description": "",
     "url": "https:\/\/news.google.com\/__i\/rss\/rd\/articles\/CBMicGh0dHBzOi8vbmV3cy5za3kuY29tL3N0b3J5L2JvbWItc3F1YWQtY2FsbGVkLWFuZC10d28taGVsZC1hZnRlci1zdXNwaWNpb3VzLWRldmljZS1mb3VuZC1pbi1jYXItaW4tbHV0b24tMTE5NTA3ODfSAXRodHRwczovL25ld3Muc2t5LmNvbS9zdG9yeS9hbXAvYm9tYi1zcXVhZC1jYWxsZWQtYW5kLXR3by1oZWxkLWFmdGVyLXN1c3BpY2lvdXMtZGV2aWNlLWZvdW5kLWluLWNhci1pbi1sdXRvbi0xMTk1MDc4Nw?oc=5",
     "image": None, "publishedAt": "2020-03-06 10:22:00 UTC",
     "source": {"name": "Sky News", "url": "https:\/\/news.sky.com"}},
    {"title": "Boris Johnson's government has already spent \u00a34.4bn on Brexit preparations, new figures reveal",
     "description": "",
     "url": "https:\/\/news.google.com\/__i\/rss\/rd\/articles\/CBMib2h0dHBzOi8vd3d3LmluZGVwZW5kZW50LmNvLnVrL25ld3MvdWsvcG9saXRpY3MvYnJleGl0LWNvc3QtYm9yaXMtam9obnNvbi1sZWF2ZS1ldS1ib3JkZXItY29udHJvbHMtYTkzNzgwNjYuaHRtbNIBc2h0dHBzOi8vd3d3LmluZGVwZW5kZW50LmNvLnVrL25ld3MvdWsvcG9saXRpY3MvYnJleGl0LWNvc3QtYm9yaXMtam9obnNvbi1sZWF2ZS1ldS1ib3JkZXItY29udHJvbHMtYTkzNzgwNjYuaHRtbD9hbXA?oc=5",
     "image": None, "publishedAt": "2020-03-06 07:04:00 UTC",
     "source": {"name": "The Independent", "url": "https:\/\/www.independent.co.uk"}},
    {"title": "Mum goes days without food in icy cold home and struggles sending son to \u00a31 playgroup",
     "description": "",
     "url": "https:\/\/news.google.com\/__i\/rss\/rd\/articles\/CBMiSWh0dHBzOi8vd3d3Lm1pcnJvci5jby51ay9uZXdzL3VrLW5ld3MvbXVtLWdvZXMtZGF5cy13aXRob3V0LWZvb2QtMjE2NDE5NTPSAU1odHRwczovL3d3dy5taXJyb3IuY28udWsvbmV3cy91ay1uZXdzL211bS1nb2VzLWRheXMtd2l0aG91dC1mb29kLTIxNjQxOTUzLmFtcA?oc=5",
     "image": None, "publishedAt": "2020-03-06 10:03:00 UTC",
     "source": {"name": "Mirror Online", "url": "https:\/\/www.mirror.co.uk"}},
    {"title": "Meghan Markle sends Twitter into meltdown as viewers think she \u2018pushed\u2019 Harry out the way",
     "description": "",
     "url": "https:\/\/news.google.com\/__i\/rss\/rd\/articles\/CBMid2h0dHBzOi8vd3d3LmV4cHJlc3MuY28udWsvbmV3cy9yb3lhbC8xMjUxNjA0L21lZ2hhbi1tYXJrbGUtcHJpbmNlLWhhcnJ5LWR1Y2hlc3MtcHVzaGVzLWR1a2UtdXByb2FyLXVrLW5ld3Mtcm95YWwtZmFtaWx50gF7aHR0cHM6Ly93d3cuZXhwcmVzcy5jby51ay9uZXdzL3JveWFsLzEyNTE2MDQvbWVnaGFuLW1hcmtsZS1wcmluY2UtaGFycnktZHVjaGVzcy1wdXNoZXMtZHVrZS11cHJvYXItdWstbmV3cy1yb3lhbC1mYW1pbHkvYW1w?oc=5",
     "image": None, "publishedAt": "2020-03-06 04:47:00 UTC",
     "source": {"name": "Express", "url": "https:\/\/www.express.co.uk"}},
    {"title": "Supermarket rejects minister's food supplies claim", "description": "",
     "url": "https:\/\/news.google.com\/__i\/rss\/rd\/articles\/CBMiLGh0dHBzOi8vd3d3LmJiYy5jby51ay9uZXdzL2J1c2luZXNzLTUxNzY5MTg00gEwaHR0cHM6Ly93d3cuYmJjLmNvLnVrL25ld3MvYW1wL2J1c2luZXNzLTUxNzY5MTg0?oc=5",
     "image": None, "publishedAt": "2020-03-06 11:26:02 UTC",
     "source": {"name": "BBC News", "url": "https:\/\/www.bbc.co.uk"}}, {"title": "Coronavirus news", "description": "",
                                                                         "url": "https:\/\/news.google.com\/__i\/rss\/rd\/articles\/CBMieGh0dHBzOi8vd3d3LmluZGVwZW5kZW50LmNvLnVrL25ld3MvaGVhbHRoL2Nvcm9uYXZpcnVzLW5ld3MtbGl2ZS1zeW1wdG9tcy1jb3ZpZC0xOS11ay11cy1pdGFseS1jYXNlcy1sYXRlc3QtYTkzODA1MjYuaHRtbNIBfGh0dHBzOi8vd3d3LmluZGVwZW5kZW50LmNvLnVrL25ld3MvaGVhbHRoL2Nvcm9uYXZpcnVzLW5ld3MtbGl2ZS1zeW1wdG9tcy1jb3ZpZC0xOS11ay11cy1pdGFseS1jYXNlcy1sYXRlc3QtYTkzODA1MjYuaHRtbD9hbXA?oc=5",
                                                                         "image": None,
                                                                         "publishedAt": "2020-03-06 09:18:00 UTC",
                                                                         "source": {"name": "The Independent",
                                                                                    "url": "https:\/\/www.independent.co.uk"}},
    {"title": "Amber Rudd hits out at 'rude' Oxford students after talk cancelled", "description": "",
     "url": "https:\/\/news.google.com\/__i\/rss\/rd\/articles\/CBMicWh0dHBzOi8vd3d3LnRoZWd1YXJkaWFuLmNvbS9wb2xpdGljcy8yMDIwL21hci8wNi9hbWJlci1ydWRkLWhpdHMtb3V0LWF0LXJ1ZGUtb3hmb3JkLXN0dWRlbnRzLWFmdGVyLXRhbGstY2FuY2VsbGVk0gFxaHR0cHM6Ly9hbXAudGhlZ3VhcmRpYW4uY29tL3BvbGl0aWNzLzIwMjAvbWFyLzA2L2FtYmVyLXJ1ZGQtaGl0cy1vdXQtYXQtcnVkZS1veGZvcmQtc3R1ZGVudHMtYWZ0ZXItdGFsay1jYW5jZWxsZWQ?oc=5",
     "image": None, "publishedAt": "2020-03-06 10:16:09 UTC",
     "source": {"name": "The Guardian", "url": "https:\/\/www.theguardian.com"}}]}

topics_success_response = {"timestamp": 1583482937, "articleCount": 10, "articles": [
    {"title": "A triple folding phone? Hands-on with TCL's working DragonHinge prototype", "description": "",
     "url": "https:\/\/news.google.com\/__i\/rss\/rd\/articles\/CBMiYGh0dHBzOi8vd3d3LmNuZXQuY29tL25ld3MvdHJpcGxlLWZvbGRpbmctcGhvbmUtaGFuZHMtb24td2l0aC10Y2xzLXdvcmtpbmctZHJhZ29uaGluZ2UtcHJvdG90eXBlL9IBa2h0dHBzOi8vd3d3LmNuZXQuY29tL2dvb2dsZS1hbXAvbmV3cy90cmlwbGUtZm9sZGluZy1waG9uZS1oYW5kcy1vbi13aXRoLXRjbHMtd29ya2luZy1kcmFnb25oaW5nZS1wcm90b3R5cGUv?oc=5",
     "image": None, "publishedAt": "2020-03-06 05:22:00 UTC",
     "source": {"name": "CNET", "url": "https:\/\/www.cnet.com"}},
    {"title": "Windows 10 April 2020 Update", "description": "",
     "url": "https:\/\/news.google.com\/__i\/rss\/rd\/articles\/CBMiK2h0dHBzOi8vd3d3LnlvdXR1YmUuY29tL3dhdGNoP3Y9S2g5TFZxZFhiTTTSAQA?oc=5",
     "image": None, "publishedAt": "2020-03-06 04:37:55 UTC",
     "source": {"name": "Windows Central", "url": "https:\/\/www.youtube.com"}},
    {"title": "Miyamoto Says The Success Of The Switch Was All Thanks To The \"Good Timing\" Of Its Release",
     "description": "",
     "url": "https:\/\/news.google.com\/__i\/rss\/rd\/articles\/CBMigQFodHRwOi8vd3d3Lm5pbnRlbmRvbGlmZS5jb20vbmV3cy8yMDIwLzAzL21peWFtb3RvX3NheXNfdGhlX3N1Y2Nlc3Nfb2ZfdGhlX3N3aXRjaF93YXNfYWxsX3RoYW5rc190b190aGVfZ29vZF90aW1pbmdfb2ZfaXRzX3JlbGVhc2XSAQA?oc=5",
     "image": None, "publishedAt": "2020-03-06 03:05:00 UTC",
     "source": {"name": "Nintendo Life", "url": "http:\/\/www.nintendolife.com"}},
    {"title": "How to livestream the Oppo Find X2 and Oppo Smartwatch launch [Video]", "description": "",
     "url": "https:\/\/news.google.com\/__i\/rss\/rd\/articles\/CBMiOmh0dHBzOi8vOXRvNWdvb2dsZS5jb20vMjAyMC8wMy8wNS9vcHBvLWZpbmQteDItbGl2ZXN0cmVhbS_SAT5odHRwczovLzl0bzVnb29nbGUuY29tLzIwMjAvMDMvMDUvb3Bwby1maW5kLXgyLWxpdmVzdHJlYW0vYW1wLw?oc=5",
     "image": None, "publishedAt": "2020-03-06 03:00:00 UTC",
     "source": {"name": "9to5Google", "url": "https:\/\/9to5google.com"}},
    {"title": "Xbox Series X and PS5 graphics hardware will finally kiss goodbye to weird-looking hair",
     "description": "",
     "url": "https:\/\/news.google.com\/__i\/rss\/rd\/articles\/CBMicWh0dHBzOi8vd3d3LmdhbWVzcmFkYXIuY29tL3hib3gtc2VyaWVzLXhzLTEyLXRlcmFmbG9wLWdwdS1tZWFucy13ZS1jYW4tZmluYWxseS1zYXktZ29vZGJ5ZS10by13ZWlyZC1sb29raW5nLWhhaXIv0gF1aHR0cHM6Ly93d3cuZ2FtZXNyYWRhci5jb20vYW1wL3hib3gtc2VyaWVzLXhzLTEyLXRlcmFmbG9wLWdwdS1tZWFucy13ZS1jYW4tZmluYWxseS1zYXktZ29vZGJ5ZS10by13ZWlyZC1sb29raW5nLWhhaXIv?oc=5",
     "image": None, "publishedAt": "2020-03-06 02:44:00 UTC",
     "source": {"name": "GamesRadar+", "url": "https:\/\/www.gamesradar.com"}},
    {"title": "Santa Clara County Asks Apple, Google and Others to Cancel Large In-Person Meetings and Conferences",
     "description": "",
     "url": "https:\/\/news.google.com\/__i\/rss\/rd\/articles\/CBMiVGh0dHBzOi8vd3d3Lm1hY3J1bW9ycy5jb20vMjAyMC8wMy8wNS9zYW50YS1jbGFyYS1jb3VudHktY292aWQtMTktY2FuY2VsLWNvbmZlcmVuY2VzL9IBWGh0dHBzOi8vd3d3Lm1hY3J1bW9ycy5jb20vMjAyMC8wMy8wNS9zYW50YS1jbGFyYS1jb3VudHktY292aWQtMTktY2FuY2VsLWNvbmZlcmVuY2VzL2FtcC8?oc=5",
     "image": None, "publishedAt": "2020-03-06 02:22:00 UTC",
     "source": {"name": "MacRumors", "url": "https:\/\/www.macrumors.com"}},
    {"title": "Porsche Explains Why The New 911 Turbo S Is Way More Powerful", "description": "",
     "url": "https:\/\/news.google.com\/__i\/rss\/rd\/articles\/CBMiRGh0dHBzOi8vd3d3Lm1vdG9yMS5jb20vbmV3cy80MDI2MTYvcG9yc2NoZS05MTEtdHVyYm8tcG93ZXItaW5jcmVhc2Uv0gEA?oc=5",
     "image": None, "publishedAt": "2020-03-06 02:00:58 UTC",
     "source": {"name": "Motor1 ", "url": "https:\/\/www.motor1.com"}},
    {"title": "Twitch Streamer Suspended After Accidentally Firing Real Gun At His Monitor", "description": "",
     "url": "https:\/\/news.google.com\/__i\/rss\/rd\/articles\/CBMiVWh0dHBzOi8va290YWt1LmNvbS90d2l0Y2gtc3RyZWFtZXItc3VzcGVuZGVkLWFmdGVyLWFjY2lkZW50YWxseS1maXJpbmctcmVhLTE4NDIxMzUyNjfSAVlodHRwczovL2tvdGFrdS5jb20vdHdpdGNoLXN0cmVhbWVyLXN1c3BlbmRlZC1hZnRlci1hY2NpZGVudGFsbHktZmlyaW5nLXJlYS0xODQyMTM1MjY3L2FtcA?oc=5",
     "image": None, "publishedAt": "2020-03-06 02:00:00 UTC",
     "source": {"name": "Kotaku", "url": "https:\/\/kotaku.com"}},
    {"title": "Pokemon Mystery Dungeon: Rescue Team DX Review", "description": "",
     "url": "https:\/\/news.google.com\/__i\/rss\/rd\/articles\/CBMiYWh0dHBzOi8vd3d3LmdhbWVzcG90LmNvbS9yZXZpZXdzL3Bva2Vtb24tbXlzdGVyeS1kdW5nZW9uLXJlc2N1ZS10ZWFtLWR4LXJldmlldy1iZXR0LzE5MDAtNjQxNzQyNC_SAWVodHRwczovL3d3dy5nYW1lc3BvdC5jb20vYW1wLXJldmlld3MvcG9rZW1vbi1teXN0ZXJ5LWR1bmdlb24tcmVzY3VlLXRlYW0tZHgtcmV2aWV3LWJldHQvMTkwMC02NDE3NDI0Lw?oc=5",
     "image": None, "publishedAt": "2020-03-06 00:59:00 UTC",
     "source": {"name": "GameSpot", "url": "https:\/\/www.gamespot.com"}},
    {"title": "Apple Issues New Warning Affecting Millions Of iPhone Users", "description": "",
     "url": "https:\/\/news.google.com\/__i\/rss\/rd\/articles\/CBMiZGh0dHBzOi8vd3d3LmZvcmJlcy5jb20vc2l0ZXMvZ29yZG9ua2VsbHkvMjAyMC8wMy8wNS9hcHBsZS1pcGhvbmUtcmVwYWlyLXdhcm5pbmctbmV3LWlwaG9uZS11cGdyYWRlcy_SAWhodHRwczovL3d3dy5mb3JiZXMuY29tL3NpdGVzL2dvcmRvbmtlbGx5LzIwMjAvMDMvMDUvYXBwbGUtaXBob25lLXJlcGFpci13YXJuaW5nLW5ldy1pcGhvbmUtdXBncmFkZXMvYW1wLw?oc=5",
     "image": None, "publishedAt": "2020-03-06 00:30:00 UTC",
     "source": {"name": "Forbes", "url": "https:\/\/www.forbes.com"}}]}
