instant_success_response = {'Redirect': '', 'meta': {'unsafe': 0, 'id': 'wikipedia_fathead',
                                                   'src_domain': 'en.wikipedia.org',
                                                   'developer': [{'name': 'DDG Team',
                                                                  'url': 'http://www.duckduckhack.com',
                                                                  'type': 'ddg'}],
                                                   'example_query': 'nikola tesla',
                                                   'name': 'Wikipedia', 'repo': 'fathead',
                                                   'perl_module': 'DDG::Fathead::Wikipedia',
                                                   'is_stackexchange': None,
                                                   'created_date': None, 'tab': 'About',
                                                   'src_options': {'is_mediawiki': 1,
                                                                   'directory': '',
                                                                   'is_wikipedia': 1,
                                                                   'skip_end': '0',
                                                                   'skip_abstract': 0,
                                                                   'language': 'en',
                                                                   'source_skip': '',
                                                                   'min_abstract_length': '20',
                                                                   'src_info': '',
                                                                   'skip_icon': 0,
                                                                   'skip_qr': '',
                                                                   'is_fanon': 0,
                                                                   'skip_abstract_paren': 0,
                                                                   'skip_image_name': 0},
                                                   'status': 'live',
                                                   'js_callback_name': 'wikipedia',
                                                   'src_url': None, 'live_date': None,
                                                   'description': 'Wikipedia',
                                                   'topic': ['productivity'], 'producer': None,
                                                   'dev_milestone': 'live',
                                                   'signal_from': 'wikipedia_fathead',
                                                   'src_id': 1, 'designer': None,
                                                   'blockgroup': None,
                                                   'maintainer': {'github': 'duckduckgo'},
                                                   'dev_date': None,
                                                   'production_state': 'online',
                                                   'src_name': 'Wikipedia',
                                                   'attribution': None},
                          'Image': 'https://duckduckgo.com/i/8bb94c10.png', 'Answer': '',
                          'Entity': '', 'Heading': 'Chatbot', 'Definition': '',
                          'ImageWidth': 160, 'AnswerType': '', 'RelatedTopics': [{
        'Text': "Applications of artificial intelligence - Artificial intelligence, defined as intelligence exhibited by machines, has many applications in today's society.",
        'FirstURL': 'https://duckduckgo.com/Applications_of_artificial_intelligence',
        'Icon': {
            'Width': '',
            'Height': '',
            'URL': ''},
        'Result': '<a href="https://duckduckgo.com/Applications_of_artificial_intelligence">Applications of artificial intelligence</a> - Artificial intelligence, defined as intelligence exhibited by machines, has many applications in today\'s society.'},
        {'Icon': {
            'Width': '',
            'Height': '',
            'URL': ''},
            'Result': '<a href="https://duckduckgo.com/Eugene_Goostman">Eugene Goostman</a> - Eugene Goostman is a chatbot that some regard as having passed the Turing test, a test of a computer\'s ability to communicate indistinguishably from a human.',
            'FirstURL': 'https://duckduckgo.com/Eugene_Goostman',
            'Text': "Eugene Goostman - Eugene Goostman is a chatbot that some regard as having passed the Turing test, a test of a computer's ability to communicate indistinguishably from a human."},
        {'Icon': {
            'Height': '',
            'URL': '',
            'Width': ''},
            'Result': '<a href="https://duckduckgo.com/Automated_online_assistant">Interactive online characters</a> - An automated online assistant is a program that uses artificial intelligence to provide customer service or other assistance on a website. Such an assistant may basically consist of a dialog system, an avatar, as well as an expert system to provide specific expertise to the user.',
            'FirstURL': 'https://duckduckgo.com/Automated_online_assistant',
            'Text': 'Interactive online characters - An automated online assistant is a program that uses artificial intelligence to provide customer service or other assistance on a website. Such an assistant may basically consist of a dialog system, an avatar, as well as an expert system to provide specific expertise to the user.'},
        {'Icon': {
            'URL': '',
            'Height': '',
            'Width': ''},
            'Result': '<a href="https://duckduckgo.com/Internet_bot">Internet bot</a> - An Internet bot, also known as a web robot, robot or simply bot, is a software application that runs automated tasks over the Internet. Typically, bots perform tasks that are both simple and structurally repetitive, at a much higher rate than would be possible for a human alone.',
            'FirstURL': 'https://duckduckgo.com/Internet_bot',
            'Text': 'Internet bot - An Internet bot, also known as a web robot, robot or simply bot, is a software application that runs automated tasks over the Internet. Typically, bots perform tasks that are both simple and structurally repetitive, at a much higher rate than would be possible for a human alone.'},
        {'Icon': {
            'Width': '',
            'URL': '',
            'Height': ''},
            'Result': '<a href="https://duckduckgo.com/Social_bot">Social bot</a> - A social bot is a particular type of chatbot that is employed in social media networks to automatically generate messages or in general advocate certain ideas, support campaigns, and public relations either by acting as a "follower" or even as a fake account that gathers followers itself.',
            'Text': 'Social bot - A social bot is a particular type of chatbot that is employed in social media networks to automatically generate messages or in general advocate certain ideas, support campaigns, and public relations either by acting as a "follower" or even as a fake account that gathers followers itself.',
            'FirstURL': 'https://duckduckgo.com/Social_bot'},
        {
            'FirstURL': 'https://duckduckgo.com/Software_bot',
            'Text': 'Software bot - A software bot is a type of software agent in the service of software project management and software engineering. A software bot has an identity and potentially personified aspects in order to serve their stakeholders.',
            'Icon': {
                'Height': '',
                'URL': '',
                'Width': ''},
            'Result': '<a href="https://duckduckgo.com/Software_bot">Software bot</a> - A software bot is a type of software agent in the service of software project management and software engineering. A software bot has an identity and potentially personified aspects in order to serve their stakeholders.'},
        {
            'Result': '<a href="https://duckduckgo.com/c/Natural_language_parsing">Natural language parsing</a>',
            'Icon': {
                'Height': '',
                'URL': '',
                'Width': ''},
            'FirstURL': 'https://duckduckgo.com/c/Natural_language_parsing',
            'Text': 'Natural language parsing'},
        {'Icon': {
            'Width': '',
            'Height': '',
            'URL': ''},
            'Result': '<a href="https://duckduckgo.com/c/Interactive_narrative">Interactive narrative</a>',
            'Text': 'Interactive narrative',
            'FirstURL': 'https://duckduckgo.com/c/Interactive_narrative'},
        {'Icon': {
            'Width': '',
            'Height': '',
            'URL': ''},
            'Result': '<a href="https://duckduckgo.com/c/Instant_messaging">Instant messaging</a>',
            'Text': 'Instant messaging',
            'FirstURL': 'https://duckduckgo.com/c/Instant_messaging'}],
                          'DefinitionURL': '', 'DefinitionSource': '',
                          'AbstractURL': 'https://en.wikipedia.org/wiki/Chatbot',
                          'AbstractText': 'A chatbot is a piece of software that conducts a conversation via auditory or textual methods. Such programs are often designed to convincingly simulate how a human would behave as a conversational partner, although as of 2019, they are far short of being able to pass the Turing test. Chatbots are typically used in dialog systems for various practical purposes including customer service or information acquisition. Some chatbots use sophisticated natural language processing systems, but many simpler ones scan for keywords within the input, then pull a reply with the most matching keywords, or the most similar wording pattern, from a database. The term "ChatterBot" was originally coined by Michael Mauldin in 1994 to describe these conversational programs. Today, most chatbots are accessed via virtual assistants such as Google Assistant and Amazon Alexa, via messaging apps such as Facebook Messenger or WeChat, or via individual organizations\' apps and websites.',
                          'Results': [], 'ImageHeight': 200, 'ImageIsLogo': 0,
                          'AbstractSource': 'Wikipedia', 'Type': 'A',
                          'Abstract': 'A chatbot is a piece of software that conducts a conversation via auditory or textual methods. Such programs are often designed to convincingly simulate how a human would behave as a conversational partner, although as of 2019, they are far short of being able to pass the Turing test. Chatbots are typically used in dialog systems for various practical purposes including customer service or information acquisition. Some chatbots use sophisticated natural language processing systems, but many simpler ones scan for keywords within the input, then pull a reply with the most matching keywords, or the most similar wording pattern, from a database. The term "ChatterBot" was originally coined by Michael Mauldin in 1994 to describe these conversational programs. Today, most chatbots are accessed via virtual assistants such as Google Assistant and Amazon Alexa, via messaging apps such as Facebook Messenger or WeChat, or via individual organizations\' apps and websites.',
                          'Infobox': ''}

scrape_success_response = {'Answer': '', 'Type': 'A',
                           'AbstractText': 'A chatbot is a piece of software that conducts a conversation via auditory or textual methods. Such programs are often designed to convincingly simulate how a human would behave as a conversational partner, although as of 2019, they are far short of being able to pass the Turing test. Chatbots are typically used in dialog systems for various practical purposes including customer service or information acquisition. Some chatbots use sophisticated natural language processing systems, but many simpler ones scan for keywords within the input, then pull a reply with the most matching keywords, or the most similar wording pattern, from a database. The term "ChatterBot" was originally coined by Michael Mauldin in 1994 to describe these conversational programs. Today, most chatbots are accessed via virtual assistants such as Google Assistant and Amazon Alexa, via messaging apps such as Facebook Messenger or WeChat, or via individual organizations\' apps and websites.',
                           'RelatedTopics': [
                               {'FirstURL': 'https://duckduckgo.com/Applications_of_artificial_intelligence',
                                'Result': '<a href="https://duckduckgo.com/Applications_of_artificial_intelligence">Applications of artificial intelligence</a> - Artificial intelligence, defined as intelligence exhibited by machines, has many applications in today\'s society.',
                                'Icon': {'Width': '', 'Height': '', 'URL': ''},
                                'Text': "Applications of artificial intelligence - Artificial intelligence, defined as intelligence exhibited by machines, has many applications in today's society."},
                               {
                                   'Text': "Eugene Goostman - Eugene Goostman is a chatbot that some regard as having passed the Turing test, a test of a computer's ability to communicate indistinguishably from a human.",
                                   'FirstURL': 'https://duckduckgo.com/Eugene_Goostman',
                                   'Icon': {'Width': '', 'URL': '', 'Height': ''},
                                   'Result': '<a href="https://duckduckgo.com/Eugene_Goostman">Eugene Goostman</a> - Eugene Goostman is a chatbot that some regard as having passed the Turing test, a test of a computer\'s ability to communicate indistinguishably from a human.'},
                               {
                                   'Result': '<a href="https://duckduckgo.com/Automated_online_assistant">Interactive online characters</a> - An automated online assistant is a program that uses artificial intelligence to provide customer service or other assistance on a website. Such an assistant may basically consist of a dialog system, an avatar, as well as an expert system to provide specific expertise to the user.',
                                   'Icon': {'Height': '', 'URL': '', 'Width': ''},
                                   'FirstURL': 'https://duckduckgo.com/Automated_online_assistant',
                                   'Text': 'Interactive online characters - An automated online assistant is a program that uses artificial intelligence to provide customer service or other assistance on a website. Such an assistant may basically consist of a dialog system, an avatar, as well as an expert system to provide specific expertise to the user.'},
                               {'FirstURL': 'https://duckduckgo.com/Internet_bot',
                                'Icon': {'Width': '', 'Height': '', 'URL': ''},
                                'Result': '<a href="https://duckduckgo.com/Internet_bot">Internet bot</a> - An Internet bot, also known as a web robot, robot or simply bot, is a software application that runs automated tasks over the Internet. Typically, bots perform tasks that are both simple and structurally repetitive, at a much higher rate than would be possible for a human alone.',
                                'Text': 'Internet bot - An Internet bot, also known as a web robot, robot or simply bot, is a software application that runs automated tasks over the Internet. Typically, bots perform tasks that are both simple and structurally repetitive, at a much higher rate than would be possible for a human alone.'},
                               {
                                   'Result': '<a href="https://duckduckgo.com/Social_bot">Social bot</a> - A social bot is a particular type of chatbot that is employed in social media networks to automatically generate messages or in general advocate certain ideas, support campaigns, and public relations either by acting as a "follower" or even as a fake account that gathers followers itself.',
                                   'Icon': {'URL': '', 'Height': '', 'Width': ''},
                                   'FirstURL': 'https://duckduckgo.com/Social_bot',
                                   'Text': 'Social bot - A social bot is a particular type of chatbot that is employed in social media networks to automatically generate messages or in general advocate certain ideas, support campaigns, and public relations either by acting as a "follower" or even as a fake account that gathers followers itself.'},
                               {'FirstURL': 'https://duckduckgo.com/Software_bot',
                                'Icon': {'Height': '', 'URL': '', 'Width': ''},
                                'Result': '<a href="https://duckduckgo.com/Software_bot">Software bot</a> - A software bot is a type of software agent in the service of software project management and software engineering. A software bot has an identity and potentially personified aspects in order to serve their stakeholders.',
                                'Text': 'Software bot - A software bot is a type of software agent in the service of software project management and software engineering. A software bot has an identity and potentially personified aspects in order to serve their stakeholders.'},
                               {'FirstURL': 'https://duckduckgo.com/c/Natural_language_parsing',
                                'Result': '<a href="https://duckduckgo.com/c/Natural_language_parsing">Natural language parsing</a>',
                                'Icon': {'URL': '', 'Height': '', 'Width': ''}, 'Text': 'Natural language parsing'},
                               {'Icon': {'URL': '', 'Height': '', 'Width': ''},
                                'Result': '<a href="https://duckduckgo.com/c/Interactive_narrative">Interactive narrative</a>',
                                'FirstURL': 'https://duckduckgo.com/c/Interactive_narrative',
                                'Text': 'Interactive narrative'}, {'Icon': {'Width': '', 'URL': '', 'Height': ''},
                                                                   'Result': '<a href="https://duckduckgo.com/c/Instant_messaging">Instant messaging</a>',
                                                                   'FirstURL': 'https://duckduckgo.com/c/Instant_messaging',
                                                                   'Text': 'Instant messaging'}],
                           'Image': 'https://duckduckgo.com/i/8bb94c10.png', 'Infobox': '', 'ImageIsLogo': 0,
                           'Entity': '', 'Redirect': '', 'ImageWidth': 160,
                           'meta': {'attribution': None, 'repo': 'fathead', 'dev_date': None, 'created_date': None,
                                    'src_name': 'Wikipedia', 'status': 'live', 'perl_module': 'DDG::Fathead::Wikipedia',
                                    'description': 'Wikipedia', 'dev_milestone': 'live',
                                    'src_options': {'skip_abstract': 0, 'is_wikipedia': 1, 'is_fanon': 0,
                                                    'directory': '', 'skip_end': '0', 'skip_image_name': 0,
                                                    'min_abstract_length': '20', 'is_mediawiki': 1, 'skip_qr': '',
                                                    'src_info': '', 'skip_icon': 0, 'source_skip': '',
                                                    'skip_abstract_paren': 0, 'language': 'en'}, 'live_date': None,
                                    'name': 'Wikipedia', 'signal_from': 'wikipedia_fathead',
                                    'maintainer': {'github': 'duckduckgo'}, 'production_state': 'online',
                                    'src_url': None, 'designer': None, 'js_callback_name': 'wikipedia',
                                    'example_query': 'nikola tesla', 'producer': None, 'src_domain': 'en.wikipedia.org',
                                    'unsafe': 0, 'developer': [
                                   {'url': 'http://www.duckduckhack.com', 'name': 'DDG Team', 'type': 'ddg'}],
                                    'tab': 'About', 'topic': ['productivity'], 'is_stackexchange': None,
                                    'blockgroup': None, 'src_id': 1, 'id': 'wikipedia_fathead'},
                           'AbstractURL': 'https://en.wikipedia.org/wiki/Chatbot', 'DefinitionSource': '',
                           'ImageHeight': 200, 'DefinitionURL': '', 'Definition': '', 'AbstractSource': 'Wikipedia',
                           'Heading': 'Chatbot', 'AnswerType': '',
                           'Abstract': 'A chatbot is a piece of software that conducts a conversation via auditory or textual methods. Such programs are often designed to convincingly simulate how a human would behave as a conversational partner, although as of 2019, they are far short of being able to pass the Turing test. Chatbots are typically used in dialog systems for various practical purposes including customer service or information acquisition. Some chatbots use sophisticated natural language processing systems, but many simpler ones scan for keywords within the input, then pull a reply with the most matching keywords, or the most similar wording pattern, from a database. The term "ChatterBot" was originally coined by Michael Mauldin in 1994 to describe these conversational programs. Today, most chatbots are accessed via virtual assistants such as Google Assistant and Amazon Alexa, via messaging apps such as Facebook Messenger or WeChat, or via individual organizations\' apps and websites.',
                           'Results': []}
