search_success_reponse = {'_type': 'SearchResponse', 'queryContext': {'originalQuery': 'chatbots'},
                             'webPages': {'webSearchUrl': 'https://www.bing.com/search?q=chatbots',
                                          'totalEstimatedMatches': 3620000, 'value': [
                                     {'id': 'https://chatilly.cognitiveservices.azure.com/api/v7/#WebPages.0',
                                      'contractualRules': [{'_type': 'ContractualRules/LicenseAttribution',
                                                            'targetPropertyName': 'description',
                                                            'targetPropertyIndex': 1, 'mustBeCloseToContent': True,
                                                            'license': {'name': 'CC-BY-SA',
                                                                        'url': 'http://creativecommons.org/licenses/by-sa/3.0/'},
                                                            'licenseNotice': 'Text under CC-BY-SA license'}],
                                      'name': 'Chatbot - Wikipedia', 'url': 'https://en.wikipedia.org/wiki/Chatbot',
                                      'about': [{'name': 'Chatbot'}, {'name': 'Chatbot'}], 'isFamilyFriendly': True,
                                      'displayUrl': 'https://en.wikipedia.org/wiki/Chatbot',
                                      'snippet': 'Chatbots are also appearing in the healthcare industry. A study suggested that physicians in the United States believed that chatbots would be most beneficial for scheduling doctor appointments, locating health clinics, or providing medication information. Certain patient groups are still reluctant to use chatbots.',
                                      'dateLastCrawled': '2020-02-20T15:05:00.0000000Z', 'language': 'en',
                                      'isNavigational': False},
                                     {'id': 'https://chatilly.cognitiveservices.azure.com/api/v7/#WebPages.1',
                                      'name': 'The Complete Beginner’s Guide To Chatbots',
                                      'url': 'https://chatbotsmagazine.com/the-complete-beginner-s-guide-to-chatbots-8280b7b906ca',
                                      'about': [{'name': 'Chatbot'}], 'isFamilyFriendly': True,
                                      'displayUrl': 'https://chatbotsmagazine.com/the-complete-beginner-s-guide-to-chatbots-8280b7b906ca',
                                      'snippet': 'Examples of Chatbots. Buying shoes isn’t the only thing chatbots can be used for. Here are a couple of other examples: Weather bot. Get the weather whenever you ask. Grocery bot. Help me pick out and order groceries for the week.',
                                      'dateLastCrawled': '2020-03-05T05:21:00.0000000Z', 'language': 'en',
                                      'isNavigational': False},
                                     {'id': 'https://chatilly.cognitiveservices.azure.com/api/v7/#WebPages.2',
                                      'name': '10 of the Most Innovative Chatbots on the Web | WordStream',
                                      'url': 'https://www.wordstream.com/blog/ws/2017/10/04/chatbots',
                                      'about': [{'name': 'Chatbot'}], 'isFamilyFriendly': True,
                                      'displayUrl': 'https://www.wordstream.com/blog/ws/2017/10/04/chatbots',
                                      'snippet': 'Chatbots – also known as “conversational agents” – are software applications that mimic written or spoken human speech for the purposes of simulating a conversation or interaction with a real person. There are two primary ways chatbots are offered to visitors: via web-based applications or standalone apps.',
                                      'dateLastCrawled': '2020-03-07T00:21:00.0000000Z', 'language': 'en',
                                      'isNavigational': False},
                                     {'id': 'https://chatilly.cognitiveservices.azure.com/api/v7/#WebPages.3',
                                      'name': 'Chatbots.org - Virtual assistants, virtual agents, chat ...',
                                      'url': 'https://www.chatbots.org/',
                                      'about': [{'name': 'Chatbot'}, {'name': 'Chatbot'}, {'name': 'Embodied Agent'}],
                                      'isFamilyFriendly': True, 'displayUrl': 'https://www.chatbots.org',
                                      'snippet': 'Chatbots are used in a wide variety of situations and over a number of different platforms. Bots are used for customer service, for product suggestion, for sales, for scheduling, for marketing, engagement and so much more. Chatbots work by using predetermined conversational elements to interact with a human user over the internet.',
                                      'dateLastCrawled': '2020-03-08T11:26:00.0000000Z', 'language': 'en',
                                      'isNavigational': False},
                                     {'id': 'https://chatilly.cognitiveservices.azure.com/api/v7/#WebPages.4',
                                      'name': 'Why Chatbots Are the Future of Marketing: The Battle of ...',
                                      'url': 'https://www.hubspot.com/stories/chatbot-marketing-future',
                                      'isFamilyFriendly': True,
                                      'displayUrl': 'https://www.hubspot.com/stories/chatbot-marketing-future',
                                      'snippet': "Research from Forrester showed 5% of companies worldwide said they were using chatbots regularly in 2016, 20% were piloting them, and 32% were planning to use or test them in 2017. As more and more brands join the race, we're in desperate need of a framework around doing bots the right way — one that reflects the way consumers have changed.",
                                      'dateLastCrawled': '2020-03-06T13:27:00.0000000Z', 'language': 'en',
                                      'isNavigational': False},
                                     {'id': 'https://chatilly.cognitiveservices.azure.com/api/v7/#WebPages.5',
                                      'name': 'Top 10 Best Chatbot Platform Tools to Build Chatbots for ...',
                                      'url': 'https://www.entrepreneur.com/article/289788',
                                      'about': [{'name': 'Chatbot'}], 'isFamilyFriendly': True,
                                      'displayUrl': 'https://www.entrepreneur.com/article/289788',
                                      'snippet': 'Chatbots are the new rage as more top brands are advancing the technology and integrating it into their chat systems. Big names such as Facebook and Telegram have already made moves in this arena ...',
                                      'dateLastCrawled': '2020-03-09T19:46:00.0000000Z', 'language': 'en',
                                      'isNavigational': False},
                                     {'id': 'https://chatilly.cognitiveservices.azure.com/api/v7/#WebPages.6',
                                      'name': 'Chatbot Definition',
                                      'url': 'https://www.investopedia.com/terms/c/chatbot.asp',
                                      'about': [{'name': 'Chatbot'}], 'isFamilyFriendly': True,
                                      'displayUrl': 'https://www.investopedia.com/terms/c/chatbot.asp',
                                      'snippet': 'A chatbot is an automated program that interacts with customers like a human would and cost little to nothing to engage with. Chatbots attend to customers at all times of the day and week and are ...',
                                      'dateLastCrawled': '2020-03-05T07:40:00.0000000Z', 'language': 'en',
                                      'isNavigational': False},
                                     {'id': 'https://chatilly.cognitiveservices.azure.com/api/v7/#WebPages.7',
                                      'name': 'Chatbots | Technology | The Guardian',
                                      'url': 'https://www.theguardian.com/technology/chatbots',
                                      'isFamilyFriendly': True,
                                      'displayUrl': 'https://www.theguardian.com/technology/chatbots',
                                      'snippet': 'Why Facebook and Microsoft say chatbots are the talk of the town Software programmed to interact with humans is hot property in Silicon Valley, with potential benefits for businesses, consumers ...',
                                      'dateLastCrawled': '2020-02-25T21:43:00.0000000Z', 'language': 'en',
                                      'isNavigational': False},
                                     {'id': 'https://chatilly.cognitiveservices.azure.com/api/v7/#WebPages.8',
                                      'name': 'Chatbots Magazine', 'url': 'https://chatbotsmagazine.com/',
                                      'isFamilyFriendly': True, 'displayUrl': 'https://chatbotsmagazine.com',
                                      'snippet': 'Chatbots, AI, NLP, Facebook Messenger, Slack, Telegram, and more.',
                                      'dateLastCrawled': '2020-03-09T16:04:00.0000000Z', 'language': 'en',
                                      'isNavigational': False}], 'someResultsRemoved': True},
                             'images': {'id': 'https://chatilly.cognitiveservices.azure.com/api/v7/#Images',
                                        'readLink': 'https://chatilly.cognitiveservices.azure.com/api/v7/images/search?q=chatbots&qpvt=chatbots',
                                        'webSearchUrl': 'https://www.bing.com/images/search?q=chatbots&qpvt=chatbots',
                                        'isFamilyFriendly': True, 'value': [{
                                                                                'webSearchUrl': 'https://www.bing.com/images/search?q=chatbots&id=D0795593A9912F4FEFF99AB6DF430092EAE641D8&FORM=IQFRBA',
                                                                                'name': 'How 5 Innovative Businesses Are Using Chatbots',
                                                                                'thumbnailUrl': 'https://tse1.mm.bing.net/th?id=OIP.BWZp1CB1u7QE1CAr6eewrAHaE7&pid=Api',
                                                                                'datePublished': '2017-11-15T10:29:00.0000000Z',
                                                                                'contentUrl': 'https://jumbotron-production-f.squarecdn.com/assets/23263a5b26d07f810dd4.jpg',
                                                                                'hostPageUrl': 'https://squareup.com/townsquare/how-5-innovative-businesses-are-using-chatbots',
                                                                                'contentSize': '54306 B',
                                                                                'encodingFormat': 'jpeg',
                                                                                'hostPageDisplayUrl': 'https://squareup.com/townsquare/how-5-innovative-businesses-are-using-chatbots',
                                                                                'width': 1496, 'height': 996,
                                                                                'thumbnail': {'width': 474,
                                                                                              'height': 315}}, {
                                                                                'webSearchUrl': 'https://www.bing.com/images/search?q=chatbots&id=41369F325C2DCE7F2ADB7937F7608D91C555B96C&FORM=IQFRBA',
                                                                                'name': "Retail Chatbots: Get to Know RooBot and Why Everyone's ...",
                                                                                'thumbnailUrl': 'https://tse1.mm.bing.net/th?id=OIP.iPLTVwBuojFJo882la2XtgHaE8&pid=Api',
                                                                                'datePublished': '2017-10-18T04:22:00.0000000Z',
                                                                                'contentUrl': 'https://cdn.app.compendium.com/uploads/user/e7c690e8-6ff9-102a-ac6d-e4aebca50425/44daa97a-36df-42aa-af1a-47183923e1d1/File/88f2d357006ea23149a3cf3695ad97b6/retail_chatbots.jpg',
                                                                                'hostPageUrl': 'https://blogs.oracle.com/cx/retail-chatbots-get-to-know-roobot-and-why-everyones-talking-about-ai',
                                                                                'contentSize': '338573 B',
                                                                                'encodingFormat': 'jpeg',
                                                                                'hostPageDisplayUrl': 'https://blogs.oracle.com/cx/retail-chatbots-get-to-know-roobot-and-why-everyones-talking-about-ai',
                                                                                'width': 1000, 'height': 667,
                                                                                'thumbnail': {'width': 474,
                                                                                              'height': 316}}, {
                                                                                'webSearchUrl': 'https://www.bing.com/images/search?q=chatbots&id=A94862EDF224A67D9851A19EF561AF7DEC07BC6E&FORM=IQFRBA',
                                                                                'name': 'chatbots',
                                                                                'thumbnailUrl': 'https://tse1.mm.bing.net/th?id=OIP.gb_mmm-6SFkEa_OrkYz2vgHaE8&pid=Api',
                                                                                'datePublished': '2018-06-18T13:27:00.0000000Z',
                                                                                'contentUrl': 'https://cdn.app.compendium.com/uploads/user/e7c690e8-6ff9-102a-ac6d-e4aebca50425/554cf0ae-e9da-49d5-9318-c1cd36224c06/File/81bfe69a6fba4859046bf3ab918cf6be/adobestock_194734459.jpeg',
                                                                                'hostPageUrl': 'https://blogs.oracle.com/marketingcloud/a-look-at-the-current-state-of-chatbots',
                                                                                'contentSize': '2643217 B',
                                                                                'encodingFormat': 'jpeg',
                                                                                'hostPageDisplayUrl': 'https://blogs.oracle.com/marketingcloud/a-look-at-the-current-state-of-chatbots',
                                                                                'width': 5184, 'height': 3456,
                                                                                'thumbnail': {'width': 474,
                                                                                              'height': 316}}, {
                                                                                'webSearchUrl': 'https://www.bing.com/images/search?q=chatbots&id=305A2BCCF266B9E25B3F99BC519147F4797D6FF1&FORM=IQFRBA',
                                                                                'name': 'Dawn of the Chatbots: What Do Consumers Want and Expect ...',
                                                                                'thumbnailUrl': 'https://tse1.mm.bing.net/th?id=OIP.IfHc0tX71qLedcwJREnf1gHaEU&pid=Api',
                                                                                'datePublished': '2020-02-27T21:36:00.0000000Z',
                                                                                'contentUrl': 'https://cdn.technologyadvice.com/wp-content/uploads/2018/02/friendly-chatbot-700x408.jpg',
                                                                                'hostPageUrl': 'https://technologyadvice.com/blog/marketing/chatbots-consumers-want-expect/',
                                                                                'contentSize': '22895 B',
                                                                                'encodingFormat': 'jpeg',
                                                                                'hostPageDisplayUrl': 'https://technologyadvice.com/blog/marketing/chatbots-consumers-want-expect/',
                                                                                'width': 700, 'height': 408,
                                                                                'thumbnail': {'width': 474,
                                                                                              'height': 276}}, {
                                                                                'webSearchUrl': 'https://www.bing.com/images/search?q=chatbots&id=06B3AB0267697B2988D343B122C71ACDCADE8B16&FORM=IQFRBA',
                                                                                'name': 'Revived: League of Legends - Chatbot',
                                                                                'thumbnailUrl': 'https://tse1.mm.bing.net/th?id=OIP.Z7kTtThYc2BHGoqN18g2rgHaFP&pid=Api',
                                                                                'datePublished': '2020-01-26T11:30:00.0000000Z',
                                                                                'contentUrl': 'http://www.skillbyte.de/wp-content/uploads/2016/05/chatbot.jpg',
                                                                                'hostPageUrl': 'https://boards.euw.leagueoflegends.com/en/c/champions-gameplay-en/U8XvZEqG-revived-league-of-legends-chatbot',
                                                                                'contentSize': '34693 B',
                                                                                'encodingFormat': 'jpeg',
                                                                                'hostPageDisplayUrl': 'https://boards.euw.leagueoflegends.com/en/c/champions-gameplay-en/U8XvZEqG-revived-league-of-legends-chatbot',
                                                                                'width': 930, 'height': 659,
                                                                                'thumbnail': {'width': 474,
                                                                                              'height': 335}}, {
                                                                                'webSearchUrl': 'https://www.bing.com/images/search?q=chatbots&id=66065125936C44EB379C428B91214D8CCBFDCB44&FORM=IQFRBA',
                                                                                'name': '3 types of business chatbots you can build - Watson',
                                                                                'thumbnailUrl': 'https://tse1.mm.bing.net/th?id=OIP.7L1dWT624daKANsMAP6kaQHaDt&pid=Api',
                                                                                'datePublished': '2017-12-03T12:00:00.0000000Z',
                                                                                'contentUrl': 'https://www.ibm.com/blogs/watson/wp-content/uploads/2017/12/Conversation_service_Blog1200x600.png',
                                                                                'hostPageUrl': 'https://www.ibm.com/blogs/watson/2017/12/3-types-of-business-chatbots-you-can-build/',
                                                                                'contentSize': '826866 B',
                                                                                'encodingFormat': 'png',
                                                                                'hostPageDisplayUrl': 'https://www.ibm.com/blogs/watson/2017/12/3-types-of-business-chatbots-you-can-build/',
                                                                                'width': 1200, 'height': 601,
                                                                                'thumbnail': {'width': 474,
                                                                                              'height': 237}}, {
                                                                                'webSearchUrl': 'https://www.bing.com/images/search?q=chatbots&id=8377DE57B7F4D211095FCBF1BB0C6D6AC738D724&FORM=IQFRBA',
                                                                                'name': 'What relevance do Chatbots have to B2B ecommerce? - B2B ...',
                                                                                'thumbnailUrl': 'https://tse1.mm.bing.net/th?id=OIP.nlfcVSw5TyFzzx5h35LiRQHaEj&pid=Api',
                                                                                'datePublished': '2017-03-06T17:31:00.0000000Z',
                                                                                'contentUrl': 'http://www.netalogue.com/wp-content/uploads/2017/03/chatbot.png',
                                                                                'hostPageUrl': 'http://www.netalogue.com/what-relevance-do-chatbots-have-to-b2b-ecommerce',
                                                                                'contentSize': '33570 B',
                                                                                'encodingFormat': 'png',
                                                                                'hostPageDisplayUrl': 'http://www.netalogue.com/what-relevance-do-chatbots-have-to-b2b-ecommerce',
                                                                                'width': 880, 'height': 541,
                                                                                'thumbnail': {'width': 474,
                                                                                              'height': 291}}, {
                                                                                'webSearchUrl': 'https://www.bing.com/images/search?q=chatbots&id=1F1330CBB9CEE366BE59924CD2EBA2C6DCD379A1&FORM=IQFRBA',
                                                                                'name': 'The linguistics behind chatbots | iCapps',
                                                                                'thumbnailUrl': 'https://tse1.mm.bing.net/th?id=OIP.lgqyyFHbouXXr55PUFEQfwHaEK&pid=Api',
                                                                                'datePublished': '2017-08-12T02:45:00.0000000Z',
                                                                                'contentUrl': 'http://www.icapps.com/wp-content/uploads/2017/02/3059439-poster-1280-why-the-latest-invasion-of-chatbots-isnt-like-the-others.jpg',
                                                                                'hostPageUrl': 'http://www.icapps.com/the-linguistics-behind-chatbots/',
                                                                                'contentSize': '106145 B',
                                                                                'encodingFormat': 'jpeg',
                                                                                'hostPageDisplayUrl': 'http://www.icapps.com/the-linguistics-behind-chatbots/',
                                                                                'width': 1280, 'height': 720,
                                                                                'thumbnail': {'width': 474,
                                                                                              'height': 266}}, {
                                                                                'webSearchUrl': 'https://www.bing.com/images/search?q=chatbots&id=DCF45BCE50C2DB9F883D1AE90D20B583AE808DA9&FORM=IQFRBA',
                                                                                'name': 'Chatbots will be one of the biggest drivers for workplace ...',
                                                                                'thumbnailUrl': 'https://tse1.mm.bing.net/th?id=OIP.MkLQhBjTm5Jbi48y5nlU0wHaE8&pid=Api',
                                                                                'datePublished': '2017-08-29T08:28:00.0000000Z',
                                                                                'contentUrl': 'https://www.talk-business.co.uk/wp-content/uploads/2017/08/shutterstock_666171235.jpg',
                                                                                'hostPageUrl': 'https://www.talk-business.co.uk/2017/08/21/chatbots-will-be-one-of-the-biggest-drivers-for-workplace-efficiency/',
                                                                                'contentSize': '53315 B',
                                                                                'encodingFormat': 'jpeg',
                                                                                'hostPageDisplayUrl': 'https://www.talk-business.co.uk/2017/08/21/chatbots-will-be-one-of-the-biggest-drivers-for-workplace-efficiency/',
                                                                                'width': 1000, 'height': 667,
                                                                                'thumbnail': {'width': 474,
                                                                                              'height': 316}}, {
                                                                                'webSearchUrl': 'https://www.bing.com/images/search?q=chatbots&id=4F543A364109DE7B07A85390AD33C18185EBD9B7&FORM=IQFRBA',
                                                                                'name': 'Chatbots on Mobiles will Reach 2 Billion Apps by 2021 ...',
                                                                                'thumbnailUrl': 'https://tse1.mm.bing.net/th?id=OIP.N-C_cnZwrsLpHOR6PtExIgHaDu&pid=Api',
                                                                                'datePublished': '2017-04-11T13:21:00.0000000Z',
                                                                                'contentUrl': 'http://blog.appsheet.com/hs-fs/hubfs/Chatbots.png',
                                                                                'hostPageUrl': 'https://geobrava.wordpress.com/2017/04/11/chatbots-on-mobiles-will-reach-2-billion-apps-by-2021/',
                                                                                'contentSize': '146331 B',
                                                                                'encodingFormat': 'png',
                                                                                'hostPageDisplayUrl': 'https://geobrava.wordpress.com/2017/04/11/chatbots-on-mobiles-will-reach-2-billion-apps-by-2021/',
                                                                                'width': 800, 'height': 402,
                                                                                'thumbnail': {'width': 474,
                                                                                              'height': 238}}, {
                                                                                'webSearchUrl': 'https://www.bing.com/images/search?q=chatbots&id=5ACE9078104FA21BB24059A23A8DDC32C82E1FCF&FORM=IQFRBA',
                                                                                'name': 'Profiling Medical Chatbots and Their Multilingual Capabilities',
                                                                                'thumbnailUrl': 'https://tse1.mm.bing.net/th?id=OIP.sEWPIcyT3JrxrtKXtv36uAHaE8&pid=Api',
                                                                                'datePublished': '2018-02-02T09:18:00.0000000Z',
                                                                                'contentUrl': 'https://www.translatemedia.com/wp-content/cache/thumbnails/2017/12/shutterstock_650363986-860x9999.jpg',
                                                                                'hostPageUrl': 'https://www.translatemedia.com/translation-blog/profiling-medical-chatbots-multilingual-capabilities/',
                                                                                'contentSize': '33023 B',
                                                                                'encodingFormat': 'jpeg',
                                                                                'hostPageDisplayUrl': 'https://www.translatemedia.com/translation-blog/profiling-medical-chatbots-multilingual-capabilities/',
                                                                                'width': 860, 'height': 574,
                                                                                'thumbnail': {'width': 474,
                                                                                              'height': 316}}, {
                                                                                'webSearchUrl': 'https://www.bing.com/images/search?q=chatbots&id=B3FAD9B950D847341CE2E410C0E2A7E87638C696&FORM=IQFRBA',
                                                                                'name': 'The Four Steps for Building Chatbots of the Future',
                                                                                'thumbnailUrl': 'https://tse1.mm.bing.net/th?id=OIP.B6Vaq8JVifEcaq1sjZXnVwHaC9&pid=Api',
                                                                                'datePublished': '2017-05-17T05:47:00.0000000Z',
                                                                                'contentUrl': 'http://www.iamwire.com/wp-content/uploads/2017/05/chatbots.jpg',
                                                                                'hostPageUrl': 'http://www.iamwire.com/2017/05/steps-building-chatbots/152684',
                                                                                'contentSize': '171322 B',
                                                                                'encodingFormat': 'jpeg',
                                                                                'hostPageDisplayUrl': 'http://www.iamwire.com/2017/05/steps-building-chatbots/152684',
                                                                                'width': 2000, 'height': 800,
                                                                                'thumbnail': {'width': 474,
                                                                                              'height': 189}}, {
                                                                                'webSearchUrl': 'https://www.bing.com/images/search?q=chatbots&id=54A145226BF69894C143730220DBFB58EF2AAA30&FORM=IQFRBA',
                                                                                'name': 'Chatbots: A Guide for Enthusiast Developers',
                                                                                'thumbnailUrl': 'https://tse1.mm.bing.net/th?id=OIP.NBn-Yh9Thaw7O4KEah_PdwHaE7&pid=Api',
                                                                                'datePublished': '2019-10-23T19:28:00.0000000Z',
                                                                                'contentUrl': 'http://www.iamwire.com/wp-content/uploads/2016/05/chatbot.jpg',
                                                                                'hostPageUrl': 'http://www.iamwire.com/2016/11/chatbots-guide-enthusiast-developers/136717',
                                                                                'contentSize': '67494 B',
                                                                                'encodingFormat': 'jpeg',
                                                                                'hostPageDisplayUrl': 'http://www.iamwire.com/2016/11/chatbots-guide-enthusiast-developers/136717',
                                                                                'width': 800, 'height': 533,
                                                                                'thumbnail': {'width': 474,
                                                                                              'height': 315}}, {
                                                                                'webSearchUrl': 'https://www.bing.com/images/search?q=chatbots&id=E61A25A01D554965369D59C90BADEE87212199E9&FORM=IQFRBA',
                                                                                'name': 'Are People Even Using Chatbots? A Closer Look at Some ...',
                                                                                'thumbnailUrl': 'https://tse1.mm.bing.net/th?id=OIP.GAL-0Q5TQWsp0gBiG26blQHaE8&pid=Api',
                                                                                'datePublished': '2019-02-21T16:44:00.0000000Z',
                                                                                'contentUrl': 'https://getvoip.com/uploads/chatbots-2019-use.png',
                                                                                'hostPageUrl': 'https://getvoip.com/blog/2019/02/21/chatbot-adoption/',
                                                                                'contentSize': '78007 B',
                                                                                'encodingFormat': 'png',
                                                                                'hostPageDisplayUrl': 'https://getvoip.com/blog/2019/02/21/chatbot-adoption/',
                                                                                'width': 1200, 'height': 800,
                                                                                'thumbnail': {'width': 474,
                                                                                              'height': 316}}, {
                                                                                'webSearchUrl': 'https://www.bing.com/images/search?q=chatbots&id=C8D2A0AE266B6DF53E0D16E82D363973FC410114&FORM=IQFRBA',
                                                                                'name': 'Great Reasons Why Chatbots Should Be a Sensitive Member of ...',
                                                                                'thumbnailUrl': 'https://tse1.mm.bing.net/th?id=OIP.YeNlPp61isNumoIKqoeYqQHaEK&pid=Api',
                                                                                'datePublished': '2019-04-09T20:08:00.0000000Z',
                                                                                'contentUrl': 'https://acquire.io/wp-content/uploads/2017/12/chatbot-part-of-sales-team.png',
                                                                                'hostPageUrl': 'https://acquire.io/blog/chatbots-make-sensitive-member-sales-team/',
                                                                                'contentSize': '53466 B',
                                                                                'encodingFormat': 'png',
                                                                                'hostPageDisplayUrl': 'https://acquire.io/blog/chatbots-make-sensitive-member-sales-team/',
                                                                                'width': 800, 'height': 450,
                                                                                'thumbnail': {'width': 474,
                                                                                              'height': 266}}, {
                                                                                'webSearchUrl': 'https://www.bing.com/images/search?q=chatbots&id=792E8BFD022B35105708630FD6A674A9C17E17EF&FORM=IQFRBA',
                                                                                'name': 'Chatbots – the Biggest IT Revolution after the iPhone?',
                                                                                'thumbnailUrl': 'https://tse1.mm.bing.net/th?id=OIP.ipIZPqe6S9__L54_qVDs2QHaFL&pid=Api',
                                                                                'datePublished': '2019-12-27T00:02:00.0000000Z',
                                                                                'contentUrl': 'https://www.travel-industry-blog.com/wp-content/uploads/2016/09/chatbot-2.jpg',
                                                                                'hostPageUrl': 'https://www.travel-industry-blog.com/travel-technology/chatbots/',
                                                                                'contentSize': '133406 B',
                                                                                'encodingFormat': 'jpeg',
                                                                                'hostPageDisplayUrl': 'https://www.travel-industry-blog.com/travel-technology/chatbots/',
                                                                                'width': 1000, 'height': 700,
                                                                                'thumbnail': {'width': 474,
                                                                                              'height': 331}}, {
                                                                                'webSearchUrl': 'https://www.bing.com/images/search?q=chatbots&id=F6E02E3115276372E59C0DAD667AD94148F7C1DA&FORM=IQFRBA',
                                                                                'name': '8 Benefits of Bringing Chatbots Into Your Business ...',
                                                                                'thumbnailUrl': 'https://tse1.mm.bing.net/th?id=OIP.J8E9wyjlwEKRjZN7FKMljwHaEK&pid=Api',
                                                                                'datePublished': '2017-11-30T08:09:00.0000000Z',
                                                                                'contentUrl': 'http://microteltechnology.com/wp-content/uploads/2017/11/Chatbot-ai-1.png',
                                                                                'hostPageUrl': 'http://microteltechnology.com/8-benefits-of-chatbots-in-your-business/',
                                                                                'contentSize': '69713 B',
                                                                                'encodingFormat': 'png',
                                                                                'hostPageDisplayUrl': 'http://microteltechnology.com/8-benefits-of-chatbots-in-your-business/',
                                                                                'width': 560, 'height': 315,
                                                                                'thumbnail': {'width': 474,
                                                                                              'height': 266}}, {
                                                                                'webSearchUrl': 'https://www.bing.com/images/search?q=chatbots&id=497C5B286ACBFF81360491E57770FCD4649B4ADA&FORM=IQFRBA',
                                                                                'name': 'Chatbots: Separating the hype from reality',
                                                                                'thumbnailUrl': 'https://tse1.mm.bing.net/th?id=OIP.YHWbjHrSCexhsDP1V7rhnwHaDm&pid=Api',
                                                                                'datePublished': '2019-09-16T11:50:00.0000000Z',
                                                                                'contentUrl': 'https://www.expertsystem.com/wp-content/uploads/2017/05/Chatbots_Separating-the-hype-from-reality.jpg',
                                                                                'hostPageUrl': 'https://www.expertsystem.com/chatbots-separating-hype-reality/',
                                                                                'contentSize': '56344 B',
                                                                                'encodingFormat': 'jpeg',
                                                                                'hostPageDisplayUrl': 'https://www.expertsystem.com/chatbots-separating-hype-reality/',
                                                                                'width': 948, 'height': 461,
                                                                                'thumbnail': {'width': 474,
                                                                                              'height': 230}}, {
                                                                                'webSearchUrl': 'https://www.bing.com/images/search?q=chatbots&id=6ACB45788AD0B2CC3F7EF2D18EEB3C06753414F6&FORM=IQFRBA',
                                                                                'name': "The Rise of Chatbots | Decoded by Marriott's Digital Services",
                                                                                'thumbnailUrl': 'https://tse1.mm.bing.net/th?id=OIP.5bxYB2E97da3GO5Zs_A9nwEsCn&pid=Api',
                                                                                'datePublished': '2020-01-13T02:20:00.0000000Z',
                                                                                'contentUrl': 'https://www.mdsdecoded.com/wp-content/uploads/2017/01/chatbots_blog-1024x573.png',
                                                                                'hostPageUrl': 'https://www.mdsdecoded.com/blog/the-rise-of-chatbots/',
                                                                                'contentSize': '94795 B',
                                                                                'encodingFormat': 'png',
                                                                                'hostPageDisplayUrl': 'https://www.mdsdecoded.com/blog/the-rise-of-chatbots/',
                                                                                'width': 1024, 'height': 573,
                                                                                'thumbnail': {'width': 334,
                                                                                              'height': 187}}, {
                                                                                'webSearchUrl': 'https://www.bing.com/images/search?q=chatbots&id=6AE60FAE1523FE1E40222131AAB8194CCEDFA8F4&FORM=IQFRBA',
                                                                                'name': '10 of the Most Innovative Chatbots on the Web | WordStream',
                                                                                'thumbnailUrl': 'https://tse1.mm.bing.net/th?id=OIP.ncAtrnlzgmekGb6tRsrItQHaEJ&pid=Api',
                                                                                'datePublished': '2017-10-04T12:00:00.0000000Z',
                                                                                'contentUrl': 'https://wordstream-files-prod.s3.amazonaws.com/s3fs-public/styles/simple_image/public/images/chatbots-how-chatbots-work.jpg?VT5HzCgWVg4XECaNfPUBL_dle5nyGVz2&itok=_zeJfzK5',
                                                                                'hostPageUrl': 'https://www.wordstream.com/blog/ws/2017/10/04/chatbots',
                                                                                'contentSize': '45937 B',
                                                                                'encodingFormat': 'jpeg',
                                                                                'hostPageDisplayUrl': 'https://www.wordstream.com/blog/ws/2017/10/04/chatbots',
                                                                                'width': 1033, 'height': 578,
                                                                                'thumbnail': {'width': 474,
                                                                                              'height': 265}}]},
                             'relatedSearches': {
                                 'id': 'https://chatilly.cognitiveservices.azure.com/api/v7/#RelatedSearches',
                                 'value': [{'text': 'alice chat bot', 'displayText': 'alice chat bot',
                                            'webSearchUrl': 'https://www.bing.com/search?q=alice+chat+bot'},
                                           {'text': 'talking evie bot', 'displayText': 'talking evie bot',
                                            'webSearchUrl': 'https://www.bing.com/search?q=talking+evie+bot'},
                                           {'text': 'talk to robots online', 'displayText': 'talk to robots online',
                                            'webSearchUrl': 'https://www.bing.com/search?q=talk+to+robots+online'},
                                           {'text': 'artificial intelligence chat bot',
                                            'displayText': 'artificial intelligence chat bot',
                                            'webSearchUrl': 'https://www.bing.com/search?q=artificial+intelligence+chat+bot'},
                                           {'text': 'talk to artificial intelligence online',
                                            'displayText': 'talk to artificial intelligence online',
                                            'webSearchUrl': 'https://www.bing.com/search?q=talk+to+artificial+intelligence+online'},
                                           {'text': 'what are chatbots used for',
                                            'displayText': 'what are chatbots used for',
                                            'webSearchUrl': 'https://www.bing.com/search?q=what+are+chatbots+used+for'},
                                           {'text': 'chatbot ai', 'displayText': 'chatbot ai',
                                            'webSearchUrl': 'https://www.bing.com/search?q=chatbot+ai'},
                                           {'text': 'chatbot farm girl', 'displayText': 'chatbot farm girl',
                                            'webSearchUrl': 'https://www.bing.com/search?q=chatbot+farm+girl'}]},
                             'videos': {'id': 'https://chatilly.cognitiveservices.azure.com/api/v7/#Videos',
                                        'readLink': 'https://chatilly.cognitiveservices.azure.com/api/v7/videos/search?q=chatbots',
                                        'webSearchUrl': 'https://www.bing.com/videos/search?q=chatbots',
                                        'isFamilyFriendly': True, 'value': [{
                                                                                'webSearchUrl': 'https://www.bing.com/videos/search?q=chatbots&view=detail&mid=635040DF688D3DD3E9A4635040DF688D3DD3E9A4',
                                                                                'name': 'Deconstructing Chatbots - An Overview',
                                                                                'description': 'In this first episode of Deconstructing Chatbots, Priyanka Vergadia will set the stage for designing chatbots, powered with Natural Language Understanding (NLU) and Dialogflow. Check out Dialogflow → http://bit.ly/2R74i7g Dialogflow Enterprise Edition → http://bit.ly/2DsmOmV Dialogflow Console → http://bit.ly/2RXeaoI Watch other videos in ...',
                                                                                'thumbnailUrl': 'https://tse1.mm.bing.net/th?id=OVP.WJjBGZtZlqcugRARG6M6FgEsDh&pid=Api',
                                                                                'datePublished': '2019-01-22T23:00:59.0000000',
                                                                                'publisher': [{'name': 'YouTube'}],
                                                                                'isAccessibleForFree': True,
                                                                                'contentUrl': 'https://www.youtube.com/watch?v=O00K10xP5MU',
                                                                                'hostPageUrl': 'https://www.youtube.com/watch?v=O00K10xP5MU',
                                                                                'encodingFormat': 'mp4',
                                                                                'hostPageDisplayUrl': 'https://www.youtube.com/watch?v=O00K10xP5MU',
                                                                                'width': 1280, 'height': 720,
                                                                                'duration': 'PT3M38S',
                                                                                'motionThumbnailUrl': 'https://tse1.mm.bing.net/th?id=OM1.pOnTPY1o30BQYw_1578124228&pid=Api',
                                                                                'embedHtml': '<iframe width="1280" height="720" src="http://www.youtube.com/embed/O00K10xP5MU?autoplay=1" frameborder="0" allowfullscreen></iframe>',
                                                                                'allowHttpsEmbed': True,
                                                                                'viewCount': 25599,
                                                                                'thumbnail': {'width': 160,
                                                                                              'height': 120},
                                                                                'allowMobileEmbed': True,
                                                                                'isSuperfresh': False}, {
                                                                                'webSearchUrl': 'https://www.bing.com/videos/search?q=chatbots&view=detail&mid=1274F14EB96CAD8ADC6F1274F14EB96CAD8ADC6F',
                                                                                'name': 'Chatbots on Campus',
                                                                                'description': 'Hear how students from the College of Science, Technology, and Applied Arts, Trinidad and Tobago (COSTAAT) are using chatbots and how Alexa is helping improve their campus experience.',
                                                                                'thumbnailUrl': 'https://tse1.mm.bing.net/th?id=OVP.PmV-QhnRXEtcdEtvNktJwAEsDh&pid=Api',
                                                                                'datePublished': '2019-07-25T17:16:16.0000000',
                                                                                'publisher': [{'name': 'YouTube'}],
                                                                                'isAccessibleForFree': True,
                                                                                'contentUrl': 'https://www.youtube.com/watch?v=adz-n4mtS3s',
                                                                                'hostPageUrl': 'https://www.youtube.com/watch?v=adz-n4mtS3s',
                                                                                'encodingFormat': 'mp4',
                                                                                'hostPageDisplayUrl': 'https://www.youtube.com/watch?v=adz-n4mtS3s',
                                                                                'width': 1280, 'height': 720,
                                                                                'duration': 'PT2M18S',
                                                                                'motionThumbnailUrl': 'https://tse1.mm.bing.net/th?id=OM1.b9yKrWy5TvF0Eg_1583079795&pid=Api',
                                                                                'embedHtml': '<iframe width="1280" height="720" src="http://www.youtube.com/embed/adz-n4mtS3s?autoplay=1" frameborder="0" allowfullscreen></iframe>',
                                                                                'allowHttpsEmbed': True,
                                                                                'viewCount': 292,
                                                                                'thumbnail': {'width': 160,
                                                                                              'height': 120},
                                                                                'allowMobileEmbed': True,
                                                                                'isSuperfresh': False}, {
                                                                                'webSearchUrl': 'https://www.bing.com/videos/search?q=chatbots&view=detail&mid=176C91164CB265D1DDCF176C91164CB265D1DDCF',
                                                                                'name': 'Fulfillment: Integrating Dialogflow with BigQuery (Deconstructing Chatbots)',
                                                                                'description': 'In this episode of Deconstructing Chatbots, +Priyanka Vergadia shows you how to integrate a Dialogflow agent using BigQuery, starting with enhancing your Appointment scheduler chatbot. Then, create a dataset and table to connect to your fulfillment and test your agent. Build your first Chatbot with Dialogflow Codelab → https://goo.gle/2y4JOVQ ...',
                                                                                'thumbnailUrl': 'https://tse4.mm.bing.net/th?id=OVP.vXerLFoN3eR_-CG_O3unfgEsDh&pid=Api',
                                                                                'datePublished': '2019-07-25T15:00:08.0000000',
                                                                                'publisher': [{'name': 'YouTube'}],
                                                                                'isAccessibleForFree': True,
                                                                                'contentUrl': 'https://www.youtube.com/watch?v=l3sEaeVXdpk',
                                                                                'hostPageUrl': 'https://www.youtube.com/watch?v=l3sEaeVXdpk',
                                                                                'encodingFormat': 'mp4',
                                                                                'hostPageDisplayUrl': 'https://www.youtube.com/watch?v=l3sEaeVXdpk',
                                                                                'width': 1280, 'height': 720,
                                                                                'duration': 'PT5M20S',
                                                                                'motionThumbnailUrl': 'https://tse4.mm.bing.net/th?id=OM1.z93RZbJMFpFsFw_1575801908&pid=Api',
                                                                                'embedHtml': '<iframe width="1280" height="720" src="http://www.youtube.com/embed/l3sEaeVXdpk?autoplay=1" frameborder="0" allowfullscreen></iframe>',
                                                                                'allowHttpsEmbed': True,
                                                                                'viewCount': 5435,
                                                                                'thumbnail': {'width': 160,
                                                                                              'height': 120},
                                                                                'allowMobileEmbed': True,
                                                                                'isSuperfresh': False}, {
                                                                                'webSearchUrl': 'https://www.bing.com/videos/search?q=chatbots&view=detail&mid=94C115F2E78E5AE656D894C115F2E78E5AE656D8',
                                                                                'name': 'Understanding Entities in Dialogflow (Deconstructing Chatbots)',
                                                                                'description': "In this episode of Deconstructing Chatbots, Priyanka Vergadia shows you the 3 types of system entities: system, developer, and session. You will cover Dialogflow's mechanism for identifying and extracting useful data from user input. Get started with DialogFlow → https://bit.ly/2R74i7g Telephony gateway → https://bit.ly/2LbY1ti ...",
                                                                                'thumbnailUrl': 'https://tse4.mm.bing.net/th?id=OVP.23GJL8eqmM_5kmUvHZ6c7wEsDh&pid=Api',
                                                                                'datePublished': '2019-04-30T17:35:44.0000000',
                                                                                'publisher': [{'name': 'YouTube'}],
                                                                                'isAccessibleForFree': True,
                                                                                'contentUrl': 'https://www.youtube.com/watch?v=UmMRW3kG738',
                                                                                'hostPageUrl': 'https://www.youtube.com/watch?v=UmMRW3kG738',
                                                                                'encodingFormat': 'mp4',
                                                                                'hostPageDisplayUrl': 'https://www.youtube.com/watch?v=UmMRW3kG738',
                                                                                'width': 1280, 'height': 720,
                                                                                'duration': 'PT5M48S',
                                                                                'motionThumbnailUrl': 'https://tse4.mm.bing.net/th?id=OM2.2FbmWo7n8hXBlA_1577994175&pid=Api',
                                                                                'embedHtml': '<iframe width="1280" height="720" src="http://www.youtube.com/embed/UmMRW3kG738?autoplay=1" frameborder="0" allowfullscreen></iframe>',
                                                                                'allowHttpsEmbed': True,
                                                                                'viewCount': 8797,
                                                                                'thumbnail': {'width': 160,
                                                                                              'height': 120},
                                                                                'allowMobileEmbed': True,
                                                                                'isSuperfresh': False}, {
                                                                                'webSearchUrl': 'https://www.bing.com/videos/search?q=chatbots&view=detail&mid=C6F15BF5FADAE3232610C6F15BF5FADAE3232610',
                                                                                'name': 'Getting Started with Dialogflow (Deconstructing Chatbots)',
                                                                                'description': 'In this episode of Deconstructing Chatbots with +Priyanka Vergadia, learn all the important terms you need to know to start building your own chatbot. Get started with DialogFlow → https://bit.ly/2R74i7g Understand more about “intents” → https://bit.ly/2GoCABp Watch other videos in the Deconstructing Chatbots Playlist → https://bit.ly ...',
                                                                                'thumbnailUrl': 'https://tse1.mm.bing.net/th?id=OVP.rnkgsgruyI0UOBQtS4D6_AHfFn&pid=Api',
                                                                                'datePublished': '2019-02-05T17:00:03.0000000',
                                                                                'publisher': [{'name': 'YouTube'}],
                                                                                'isAccessibleForFree': True,
                                                                                'contentUrl': 'https://www.youtube.com/watch?v=Ov3CDTxZRQc',
                                                                                'hostPageUrl': 'https://www.youtube.com/watch?v=Ov3CDTxZRQc',
                                                                                'encodingFormat': 'mp4',
                                                                                'hostPageDisplayUrl': 'https://www.youtube.com/watch?v=Ov3CDTxZRQc',
                                                                                'width': 1280, 'height': 720,
                                                                                'duration': 'PT5M28S',
                                                                                'embedHtml': '<iframe width="1280" height="720" src="http://www.youtube.com/embed/Ov3CDTxZRQc?autoplay=1" frameborder="0" allowfullscreen></iframe>',
                                                                                'allowHttpsEmbed': True,
                                                                                'viewCount': 26720,
                                                                                'thumbnail': {'width': 160,
                                                                                              'height': 119},
                                                                                'allowMobileEmbed': True,
                                                                                'isSuperfresh': False}, {
                                                                                'webSearchUrl': 'https://www.bing.com/videos/search?q=chatbots&view=detail&mid=594265CD980B22916F60594265CD980B22916F60',
                                                                                'name': 'Production ready chatbots with SpringML (Deconstructing Chatbots)',
                                                                                'description': 'In this special episode of Deconstructing Chatbots, Priyanka Vergadia visits Spring ML’s office in Pleasanton, California. Dhruv Hemmady, Technical Project Manager, sits down and covers some real world use cases of conversational AI and how some of them have come to life starting from the idea to the finished experience. Spring ML → https ...',
                                                                                'thumbnailUrl': 'https://tse2.mm.bing.net/th?id=OVP.cxZKclNZBdkVx-BwKsy_egEsDh&pid=Api',
                                                                                'datePublished': '2019-10-01T04:00:00.0000000',
                                                                                'publisher': [{'name': 'YouTube'}],
                                                                                'isAccessibleForFree': True,
                                                                                'contentUrl': 'https://www.youtube.com/watch?v=6T0_4O9868o',
                                                                                'hostPageUrl': 'https://www.youtube.com/watch?v=6T0_4O9868o',
                                                                                'encodingFormat': 'mp4',
                                                                                'hostPageDisplayUrl': 'https://www.youtube.com/watch?v=6T0_4O9868o',
                                                                                'width': 1280, 'height': 720,
                                                                                'duration': 'PT10M44S',
                                                                                'motionThumbnailUrl': 'https://tse2.mm.bing.net/th?id=OM1.YG-RIguYzWVCWQ_1580323680&pid=Api',
                                                                                'embedHtml': '<iframe width="1280" height="720" src="http://www.youtube.com/embed/6T0_4O9868o?autoplay=1" frameborder="0" allowfullscreen></iframe>',
                                                                                'allowHttpsEmbed': True,
                                                                                'viewCount': 3126,
                                                                                'thumbnail': {'width': 160,
                                                                                              'height': 120},
                                                                                'allowMobileEmbed': True,
                                                                                'isSuperfresh': False}, {
                                                                                'webSearchUrl': 'https://www.bing.com/videos/search?q=chatbots&view=detail&mid=73DDBB8C48329EBC84A573DDBB8C48329EBC84A5',
                                                                                'name': 'Integrate Dialogflow with Telephony Gateway (Deconstructing Chatbots)',
                                                                                'description': 'In this episode of Deconstructing Chatbots, +Priyanka Vergadia will show how to enable telephony Gateway in your Dialogflow agent to build conversational IVR (interactive voice response) solutions that integrate with the rest of your call center network. Get started with DialogFlow → https://bit.ly/2R74i7g Deconstructing Chatbots Playlist ...',
                                                                                'thumbnailUrl': 'https://tse4.mm.bing.net/th?id=OVP.PeVpzxrChNRd0m_MTymW6gEsDh&pid=Api',
                                                                                'datePublished': '2019-04-02T16:15:42.0000000',
                                                                                'publisher': [{'name': 'YouTube'}],
                                                                                'isAccessibleForFree': True,
                                                                                'contentUrl': 'https://www.youtube.com/watch?v=whZPw0HFnTE',
                                                                                'hostPageUrl': 'https://www.youtube.com/watch?v=whZPw0HFnTE',
                                                                                'encodingFormat': 'mp4',
                                                                                'hostPageDisplayUrl': 'https://www.youtube.com/watch?v=whZPw0HFnTE',
                                                                                'width': 1280, 'height': 720,
                                                                                'duration': 'PT2M47S',
                                                                                'motionThumbnailUrl': 'https://tse4.mm.bing.net/th?id=OM2.pYS8njJIjLvdcw_1582073364&pid=Api',
                                                                                'embedHtml': '<iframe width="1280" height="720" src="http://www.youtube.com/embed/whZPw0HFnTE?autoplay=1" frameborder="0" allowfullscreen></iframe>',
                                                                                'allowHttpsEmbed': True,
                                                                                'viewCount': 8876,
                                                                                'thumbnail': {'width': 160,
                                                                                              'height': 120},
                                                                                'allowMobileEmbed': True,
                                                                                'isSuperfresh': False}, {
                                                                                'webSearchUrl': 'https://www.bing.com/videos/search?q=chatbots&view=detail&mid=F531A9C9D1D4D39EC046F531A9C9D1D4D39EC046',
                                                                                'name': 'Integrate Dialogflow with Actions on Google (Deconstructing Chatbots)',
                                                                                'description': 'Reach over 500M devices that support the Google Assistant by integrating Dialogflow with Actions on Google. In this episode of Deconstructing Chatbots, Priyanka Vergadia teaches you all about it! Actions on Google is a platform where you can create software to extend the functionality of Google Assistant. Using a conversational interface helps ...',
                                                                                'thumbnailUrl': 'https://tse3.mm.bing.net/th?id=OVP.-wnpg528BSKXux559JsrlgEsDh&pid=Api',
                                                                                'datePublished': '2019-03-22T17:34:20.0000000',
                                                                                'publisher': [{'name': 'YouTube'}],
                                                                                'isAccessibleForFree': True,
                                                                                'contentUrl': 'https://www.youtube.com/watch?v=z5f52sMgJLQ',
                                                                                'hostPageUrl': 'https://www.youtube.com/watch?v=z5f52sMgJLQ',
                                                                                'encodingFormat': 'mp4',
                                                                                'hostPageDisplayUrl': 'https://www.youtube.com/watch?v=z5f52sMgJLQ',
                                                                                'width': 1280, 'height': 720,
                                                                                'duration': 'PT4M25S',
                                                                                'motionThumbnailUrl': 'https://tse3.mm.bing.net/th?id=OM2.RsCe09TRyakx9Q_1578909059&pid=Api',
                                                                                'embedHtml': '<iframe width="1280" height="720" src="http://www.youtube.com/embed/z5f52sMgJLQ?autoplay=1" frameborder="0" allowfullscreen></iframe>',
                                                                                'allowHttpsEmbed': True,
                                                                                'viewCount': 13780,
                                                                                'thumbnail': {'width': 160,
                                                                                              'height': 120},
                                                                                'allowMobileEmbed': True,
                                                                                'isSuperfresh': False}, {
                                                                                'webSearchUrl': 'https://www.bing.com/videos/search?q=chatbots&view=detail&mid=BB06399FE49BEFB445EABB06399FE49BEFB445EA',
                                                                                'name': 'How do Chatbots work? Simply Explained',
                                                                                'description': 'This video is an introduction to chatbots and conversational AI, in which we explain the basics of these technologies. This video will help you understand: what chatbots are, how they work, how you can use it and we provide you with real-life examples. Also, we explain natural language processing, also known as NLP, the driver behind chatbots ...',
                                                                                'thumbnailUrl': 'https://tse2.mm.bing.net/th?id=OVP.l5SZeEuD-m0LfZU6Gw1HKAEsDh&pid=Api',
                                                                                'datePublished': '2019-04-19T18:37:17.0000000',
                                                                                'publisher': [{'name': 'YouTube'}],
                                                                                'isAccessibleForFree': True,
                                                                                'contentUrl': 'https://www.youtube.com/watch?v=aDZc_UW7uNA',
                                                                                'hostPageUrl': 'https://www.youtube.com/watch?v=aDZc_UW7uNA',
                                                                                'encodingFormat': 'mp4',
                                                                                'hostPageDisplayUrl': 'https://www.youtube.com/watch?v=aDZc_UW7uNA',
                                                                                'width': 1280, 'height': 720,
                                                                                'duration': 'PT2M38S',
                                                                                'motionThumbnailUrl': 'https://tse2.mm.bing.net/th?id=OM1.6kW075vknzkGuw_1581084194&pid=Api',
                                                                                'embedHtml': '<iframe width="1280" height="720" src="http://www.youtube.com/embed/aDZc_UW7uNA?autoplay=1" frameborder="0" allowfullscreen></iframe>',
                                                                                'allowHttpsEmbed': True,
                                                                                'viewCount': 3186,
                                                                                'thumbnail': {'width': 160,
                                                                                              'height': 120},
                                                                                'allowMobileEmbed': True,
                                                                                'isSuperfresh': False}, {
                                                                                'webSearchUrl': 'https://www.bing.com/videos/search?q=chatbots&view=detail&mid=22948DF02D4D53DE9F1D22948DF02D4D53DE9F1D',
                                                                                'name': 'How to Build an Appointment Scheduler with Dialogflow (Deconstructing Chatbots)',
                                                                                'description': 'Building chatbots is fun and simple. In this episode of Deconstructing Chatbots, +Priyanka Vergadia shows you how to build an appointment scheduler chatbot and explain the concepts including agent, intent, entity, slot filling, and web integrations. Get started with DialogFlow → https://bit.ly/2R74i7g Deconstructing Chatbots Playlist ...',
                                                                                'thumbnailUrl': 'https://tse1.mm.bing.net/th?id=OVP.p-LyvavrCn4HT-pvUlPSjwEsDh&pid=Api',
                                                                                'datePublished': '2019-02-20T03:01:37.0000000',
                                                                                'publisher': [{'name': 'YouTube'}],
                                                                                'isAccessibleForFree': True,
                                                                                'contentUrl': 'https://www.youtube.com/watch?v=oU88sHd6ilE',
                                                                                'hostPageUrl': 'https://www.youtube.com/watch?v=oU88sHd6ilE',
                                                                                'encodingFormat': 'mp4',
                                                                                'hostPageDisplayUrl': 'https://www.youtube.com/watch?v=oU88sHd6ilE',
                                                                                'width': 1280, 'height': 720,
                                                                                'duration': 'PT4M40S',
                                                                                'motionThumbnailUrl': 'https://tse1.mm.bing.net/th?id=OM1.HZ_eU00t8I2UIg_1578789429&pid=Api',
                                                                                'embedHtml': '<iframe width="1280" height="720" src="http://www.youtube.com/embed/oU88sHd6ilE?autoplay=1" frameborder="0" allowfullscreen></iframe>',
                                                                                'allowHttpsEmbed': True,
                                                                                'viewCount': 24234,
                                                                                'thumbnail': {'width': 160,
                                                                                              'height': 120},
                                                                                'allowMobileEmbed': True,
                                                                                'isSuperfresh': False}],
                                        'scenario': 'List'}, 'rankingResponse': {'mainline': {'items': [
                         {'answerType': 'WebPages', 'resultIndex': 0,
                          'value': {'id': 'https://chatilly.cognitiveservices.azure.com/api/v7/#WebPages.0'}},
                         {'answerType': 'WebPages', 'resultIndex': 1,
                          'value': {'id': 'https://chatilly.cognitiveservices.azure.com/api/v7/#WebPages.1'}},
                         {'answerType': 'WebPages', 'resultIndex': 2,
                          'value': {'id': 'https://chatilly.cognitiveservices.azure.com/api/v7/#WebPages.2'}},
                         {'answerType': 'Videos',
                          'value': {'id': 'https://chatilly.cognitiveservices.azure.com/api/v7/#Videos'}},
                         {'answerType': 'WebPages', 'resultIndex': 3,
                          'value': {'id': 'https://chatilly.cognitiveservices.azure.com/api/v7/#WebPages.3'}},
                         {'answerType': 'WebPages', 'resultIndex': 4,
                          'value': {'id': 'https://chatilly.cognitiveservices.azure.com/api/v7/#WebPages.4'}},
                         {'answerType': 'WebPages', 'resultIndex': 5,
                          'value': {'id': 'https://chatilly.cognitiveservices.azure.com/api/v7/#WebPages.5'}},
                         {'answerType': 'WebPages', 'resultIndex': 6,
                          'value': {'id': 'https://chatilly.cognitiveservices.azure.com/api/v7/#WebPages.6'}},
                         {'answerType': 'WebPages', 'resultIndex': 7,
                          'value': {'id': 'https://chatilly.cognitiveservices.azure.com/api/v7/#WebPages.7'}},
                         {'answerType': 'WebPages', 'resultIndex': 8,
                          'value': {'id': 'https://chatilly.cognitiveservices.azure.com/api/v7/#WebPages.8'}},
                         {'answerType': 'Images',
                          'value': {'id': 'https://chatilly.cognitiveservices.azure.com/api/v7/#Images'}},
                         {'answerType': 'RelatedSearches',
                          'value': {'id': 'https://chatilly.cognitiveservices.azure.com/api/v7/#RelatedSearches'}}]}}}
