forecast_success_response = {'latitude': 56.0712, 'longitude': -3.1743,
                             'timezone': 'Europe/London',
                             'currently': {'time': 1580847010, 'summary': 'Clear',
                                           'icon': 'clear-night', 'nearestStormDistance': 63,
                                           'nearestStormBearing': 297, 'precipIntensity': 0,
                                           'precipProbability': 0, 'temperature': 39.44,
                                           'apparentTemperature': 35.41, 'dewPoint': 36.33,
                                           'humidity': 0.89, 'pressure': 1030.8,
                                           'windSpeed': 5.54, 'windGust': 6.76,
                                           'windBearing': 233, 'cloudCover': 0.18,
                                           'uvIndex': 0, 'visibility': 10, 'ozone': 340.2},
                             'minutely': {'summary': 'Clear for the hour.',
                                          'icon': 'clear-night', 'data': [
                                     {'time': 1580847000, 'precipIntensity': 0,
                                      'precipProbability': 0},
                                     {'time': 1580847060, 'precipIntensity': 0,
                                      'precipProbability': 0},
                                     {'time': 1580847120, 'precipIntensity': 0,
                                      'precipProbability': 0},
                                     {'time': 1580847180, 'precipIntensity': 0,
                                      'precipProbability': 0},
                                     {'time': 1580847240, 'precipIntensity': 0,
                                      'precipProbability': 0},
                                     {'time': 1580847300, 'precipIntensity': 0,
                                      'precipProbability': 0},
                                     {'time': 1580847360, 'precipIntensity': 0,
                                      'precipProbability': 0},
                                     {'time': 1580847420, 'precipIntensity': 0,
                                      'precipProbability': 0},
                                     {'time': 1580847480, 'precipIntensity': 0,
                                      'precipProbability': 0},
                                     {'time': 1580847540, 'precipIntensity': 0,
                                      'precipProbability': 0},
                                     {'time': 1580847600, 'precipIntensity': 0,
                                      'precipProbability': 0},
                                     {'time': 1580847660, 'precipIntensity': 0,
                                      'precipProbability': 0},
                                     {'time': 1580847720, 'precipIntensity': 0,
                                      'precipProbability': 0},
                                     {'time': 1580847780, 'precipIntensity': 0,
                                      'precipProbability': 0},
                                     {'time': 1580847840, 'precipIntensity': 0,
                                      'precipProbability': 0},
                                     {'time': 1580847900, 'precipIntensity': 0,
                                      'precipProbability': 0},
                                     {'time': 1580847960, 'precipIntensity': 0,
                                      'precipProbability': 0},
                                     {'time': 1580848020, 'precipIntensity': 0,
                                      'precipProbability': 0},
                                     {'time': 1580848080, 'precipIntensity': 0,
                                      'precipProbability': 0},
                                     {'time': 1580848140, 'precipIntensity': 0,
                                      'precipProbability': 0},
                                     {'time': 1580848200, 'precipIntensity': 0,
                                      'precipProbability': 0},
                                     {'time': 1580848260, 'precipIntensity': 0,
                                      'precipProbability': 0},
                                     {'time': 1580848320, 'precipIntensity': 0,
                                      'precipProbability': 0},
                                     {'time': 1580848380, 'precipIntensity': 0,
                                      'precipProbability': 0},
                                     {'time': 1580848440, 'precipIntensity': 0,
                                      'precipProbability': 0},
                                     {'time': 1580848500, 'precipIntensity': 0,
                                      'precipProbability': 0},
                                     {'time': 1580848560, 'precipIntensity': 0,
                                      'precipProbability': 0},
                                     {'time': 1580848620, 'precipIntensity': 0,
                                      'precipProbability': 0},
                                     {'time': 1580848680, 'precipIntensity': 0,
                                      'precipProbability': 0},
                                     {'time': 1580848740, 'precipIntensity': 0,
                                      'precipProbability': 0},
                                     {'time': 1580848800, 'precipIntensity': 0,
                                      'precipProbability': 0},
                                     {'time': 1580848860, 'precipIntensity': 0,
                                      'precipProbability': 0},
                                     {'time': 1580848920, 'precipIntensity': 0,
                                      'precipProbability': 0},
                                     {'time': 1580848980, 'precipIntensity': 0,
                                      'precipProbability': 0},
                                     {'time': 1580849040, 'precipIntensity': 0,
                                      'precipProbability': 0},
                                     {'time': 1580849100, 'precipIntensity': 0,
                                      'precipProbability': 0},
                                     {'time': 1580849160, 'precipIntensity': 0,
                                      'precipProbability': 0},
                                     {'time': 1580849220, 'precipIntensity': 0,
                                      'precipProbability': 0},
                                     {'time': 1580849280, 'precipIntensity': 0,
                                      'precipProbability': 0},
                                     {'time': 1580849340, 'precipIntensity': 0,
                                      'precipProbability': 0},
                                     {'time': 1580849400, 'precipIntensity': 0,
                                      'precipProbability': 0},
                                     {'time': 1580849460, 'precipIntensity': 0,
                                      'precipProbability': 0},
                                     {'time': 1580849520, 'precipIntensity': 0,
                                      'precipProbability': 0},
                                     {'time': 1580849580, 'precipIntensity': 0,
                                      'precipProbability': 0},
                                     {'time': 1580849640, 'precipIntensity': 0,
                                      'precipProbability': 0},
                                     {'time': 1580849700, 'precipIntensity': 0,
                                      'precipProbability': 0},
                                     {'time': 1580849760, 'precipIntensity': 0,
                                      'precipProbability': 0},
                                     {'time': 1580849820, 'precipIntensity': 0,
                                      'precipProbability': 0},
                                     {'time': 1580849880, 'precipIntensity': 0,
                                      'precipProbability': 0},
                                     {'time': 1580849940, 'precipIntensity': 0,
                                      'precipProbability': 0},
                                     {'time': 1580850000, 'precipIntensity': 0,
                                      'precipProbability': 0},
                                     {'time': 1580850060, 'precipIntensity': 0,
                                      'precipProbability': 0},
                                     {'time': 1580850120, 'precipIntensity': 0,
                                      'precipProbability': 0},
                                     {'time': 1580850180, 'precipIntensity': 0,
                                      'precipProbability': 0},
                                     {'time': 1580850240, 'precipIntensity': 0,
                                      'precipProbability': 0},
                                     {'time': 1580850300, 'precipIntensity': 0,
                                      'precipProbability': 0},
                                     {'time': 1580850360, 'precipIntensity': 0,
                                      'precipProbability': 0},
                                     {'time': 1580850420, 'precipIntensity': 0,
                                      'precipProbability': 0},
                                     {'time': 1580850480, 'precipIntensity': 0,
                                      'precipProbability': 0},
                                     {'time': 1580850540, 'precipIntensity': 0,
                                      'precipProbability': 0},
                                     {'time': 1580850600, 'precipIntensity': 0,
                                      'precipProbability': 0}]},
                             'hourly': {'summary': 'Overcast throughout the day.',
                                        'icon': 'cloudy', 'data': [
                                     {'time': 1580846400, 'summary': 'Clear',
                                      'icon': 'clear-night', 'precipIntensity': 0,
                                      'precipProbability': 0, 'temperature': 39.55,
                                      'apparentTemperature': 35.72, 'dewPoint': 36.24,
                                      'humidity': 0.88, 'pressure': 1030.7, 'windSpeed': 5.3,
                                      'windGust': 6.34, 'windBearing': 233, 'cloudCover': 0.2,
                                      'uvIndex': 0, 'visibility': 10, 'ozone': 340.7},
                                     {'time': 1580850000, 'summary': 'Clear',
                                      'icon': 'clear-night', 'precipIntensity': 0,
                                      'precipProbability': 0, 'temperature': 38.99,
                                      'apparentTemperature': 34.15, 'dewPoint': 36.59,
                                      'humidity': 0.91, 'pressure': 1031.4, 'windSpeed': 6.63,
                                      'windGust': 8.74, 'windBearing': 246, 'cloudCover': 0.08,
                                      'uvIndex': 0, 'visibility': 10, 'ozone': 338.1},
                                     {'time': 1580853600, 'summary': 'Clear',
                                      'icon': 'clear-night', 'precipIntensity': 0,
                                      'precipProbability': 0, 'temperature': 38.62,
                                      'apparentTemperature': 33.31, 'dewPoint': 35.86,
                                      'humidity': 0.9, 'pressure': 1032, 'windSpeed': 7.28,
                                      'windGust': 10.74, 'windBearing': 241,
                                      'cloudCover': 0.03, 'uvIndex': 0, 'visibility': 10,
                                      'ozone': 336.6}, {'time': 1580857200, 'summary': 'Clear',
                                                        'icon': 'clear-night',
                                                        'precipIntensity': 0,
                                                        'precipProbability': 0,
                                                        'temperature': 38.53,
                                                        'apparentTemperature': 32.97,
                                                        'dewPoint': 34.8, 'humidity': 0.86,
                                                        'pressure': 1032.5, 'windSpeed': 7.68,
                                                        'windGust': 12.87, 'windBearing': 270,
                                                        'cloudCover': 0.02, 'uvIndex': 0,
                                                        'visibility': 10, 'ozone': 335.5},
                                     {'time': 1580860800, 'summary': 'Clear',
                                      'icon': 'clear-night', 'precipIntensity': 0,
                                      'precipProbability': 0, 'temperature': 38.46,
                                      'apparentTemperature': 32.73, 'dewPoint': 34.11,
                                      'humidity': 0.84, 'pressure': 1032.9, 'windSpeed': 7.97,
                                      'windGust': 14.21, 'windBearing': 261,
                                      'cloudCover': 0.05, 'uvIndex': 0, 'visibility': 10,
                                      'ozone': 333.9}, {'time': 1580864400, 'summary': 'Clear',
                                                        'icon': 'clear-night',
                                                        'precipIntensity': 0,
                                                        'precipProbability': 0,
                                                        'temperature': 38.51,
                                                        'apparentTemperature': 32.69,
                                                        'dewPoint': 34.22, 'humidity': 0.84,
                                                        'pressure': 1033.2, 'windSpeed': 8.15,
                                                        'windGust': 14.06, 'windBearing': 267,
                                                        'cloudCover': 0.19, 'uvIndex': 0,
                                                        'visibility': 10, 'ozone': 331},
                                     {'time': 1580868000, 'summary': 'Partly Cloudy',
                                      'icon': 'partly-cloudy-night', 'precipIntensity': 0,
                                      'precipProbability': 0, 'temperature': 38.56,
                                      'apparentTemperature': 32.74, 'dewPoint': 34.71,
                                      'humidity': 0.86, 'pressure': 1033.4, 'windSpeed': 8.18,
                                      'windGust': 13.13, 'windBearing': 233, 'cloudCover': 0.4,
                                      'uvIndex': 0, 'visibility': 10, 'ozone': 327.6},
                                     {'time': 1580871600, 'summary': 'Partly Cloudy',
                                      'icon': 'partly-cloudy-night', 'precipIntensity': 0,
                                      'precipProbability': 0, 'temperature': 38.59,
                                      'apparentTemperature': 32.78, 'dewPoint': 35.04,
                                      'humidity': 0.87, 'pressure': 1033.5, 'windSpeed': 8.17,
                                      'windGust': 12.67, 'windBearing': 245,
                                      'cloudCover': 0.56, 'uvIndex': 0, 'visibility': 10,
                                      'ozone': 324.9},
                                     {'time': 1580875200, 'summary': 'Mostly Cloudy',
                                      'icon': 'partly-cloudy-night', 'precipIntensity': 0,
                                      'precipProbability': 0, 'temperature': 38.54,
                                      'apparentTemperature': 32.78, 'dewPoint': 35.01,
                                      'humidity': 0.87, 'pressure': 1033.5, 'windSpeed': 8.05,
                                      'windGust': 13.14, 'windBearing': 246,
                                      'cloudCover': 0.65, 'uvIndex': 0, 'visibility': 10,
                                      'ozone': 322.8},
                                     {'time': 1580878800, 'summary': 'Mostly Cloudy',
                                      'icon': 'partly-cloudy-night', 'precipIntensity': 0,
                                      'precipProbability': 0, 'temperature': 38.37,
                                      'apparentTemperature': 32.65, 'dewPoint': 34.73,
                                      'humidity': 0.87, 'pressure': 1033.4, 'windSpeed': 7.9,
                                      'windGust': 14.11, 'windBearing': 246, 'cloudCover': 0.7,
                                      'uvIndex': 0, 'visibility': 10, 'ozone': 321.4},
                                     {'time': 1580882400, 'summary': 'Mostly Cloudy',
                                      'icon': 'partly-cloudy-night', 'precipIntensity': 0,
                                      'precipProbability': 0, 'temperature': 38.2,
                                      'apparentTemperature': 32.36, 'dewPoint': 34.55,
                                      'humidity': 0.87, 'pressure': 1033.4, 'windSpeed': 8.07,
                                      'windGust': 15.41, 'windBearing': 244,
                                      'cloudCover': 0.76, 'uvIndex': 0, 'visibility': 10,
                                      'ozone': 321.6},
                                     {'time': 1580886000, 'summary': 'Mostly Cloudy',
                                      'icon': 'partly-cloudy-night', 'precipIntensity': 0,
                                      'precipProbability': 0, 'temperature': 38.28,
                                      'apparentTemperature': 32.08, 'dewPoint': 34.97,
                                      'humidity': 0.88, 'pressure': 1033.5, 'windSpeed': 8.77,
                                      'windGust': 17.3, 'windBearing': 243, 'cloudCover': 0.84,
                                      'uvIndex': 0, 'visibility': 10, 'ozone': 324.4},
                                     {'time': 1580889600, 'summary': 'Overcast',
                                      'icon': 'cloudy', 'precipIntensity': 0,
                                      'precipProbability': 0, 'temperature': 38.49,
                                      'apparentTemperature': 31.88, 'dewPoint': 35.63,
                                      'humidity': 0.89, 'pressure': 1033.8, 'windSpeed': 9.77,
                                      'windGust': 19.55, 'windBearing': 241,
                                      'cloudCover': 0.94, 'uvIndex': 0, 'visibility': 10,
                                      'ozone': 328.8},
                                     {'time': 1580893200, 'summary': 'Overcast',
                                      'icon': 'cloudy', 'precipIntensity': 0,
                                      'precipProbability': 0, 'temperature': 39.14,
                                      'apparentTemperature': 32.23, 'dewPoint': 36.46,
                                      'humidity': 0.9, 'pressure': 1033.9, 'windSpeed': 10.82,
                                      'windGust': 21.42, 'windBearing': 241, 'cloudCover': 1,
                                      'uvIndex': 0, 'visibility': 10, 'ozone': 332.7},
                                     {'time': 1580896800, 'summary': 'Overcast',
                                      'icon': 'cloudy', 'precipIntensity': 0,
                                      'precipProbability': 0, 'temperature': 40.96,
                                      'apparentTemperature': 34.08, 'dewPoint': 37.77,
                                      'humidity': 0.88, 'pressure': 1033.4, 'windSpeed': 11.91,
                                      'windGust': 22.48, 'windBearing': 242, 'cloudCover': 1,
                                      'uvIndex': 0, 'visibility': 10, 'ozone': 335.6},
                                     {'time': 1580900400, 'summary': 'Overcast',
                                      'icon': 'cloudy', 'precipIntensity': 0.0002,
                                      'precipProbability': 0.07, 'precipType': 'rain',
                                      'temperature': 43.34, 'apparentTemperature': 36.73,
                                      'dewPoint': 39.59, 'humidity': 0.87, 'pressure': 1033.1,
                                      'windSpeed': 12.97, 'windGust': 23.18,
                                      'windBearing': 245, 'cloudCover': 0.99, 'uvIndex': 0,
                                      'visibility': 10, 'ozone': 338.1},
                                     {'time': 1580904000, 'summary': 'Overcast',
                                      'icon': 'cloudy', 'precipIntensity': 0.0003,
                                      'precipProbability': 0.07, 'precipType': 'rain',
                                      'temperature': 45.36, 'apparentTemperature': 39.02,
                                      'dewPoint': 41.07, 'humidity': 0.85, 'pressure': 1032.7,
                                      'windSpeed': 13.85, 'windGust': 23.99,
                                      'windBearing': 248, 'cloudCover': 0.97, 'uvIndex': 1,
                                      'visibility': 10, 'ozone': 340.7},
                                     {'time': 1580907600, 'summary': 'Overcast',
                                      'icon': 'cloudy', 'precipIntensity': 0.0002,
                                      'precipProbability': 0.09, 'precipType': 'rain',
                                      'temperature': 46.26, 'apparentTemperature': 39.93,
                                      'dewPoint': 41.69, 'humidity': 0.84, 'pressure': 1032.2,
                                      'windSpeed': 14.71, 'windGust': 25.3, 'windBearing': 248,
                                      'cloudCover': 0.97, 'uvIndex': 1, 'visibility': 10,
                                      'ozone': 344.2},
                                     {'time': 1580911200, 'summary': 'Overcast',
                                      'icon': 'cloudy', 'precipIntensity': 0,
                                      'precipProbability': 0, 'temperature': 46.34,
                                      'apparentTemperature': 39.84, 'dewPoint': 41.56,
                                      'humidity': 0.83, 'pressure': 1031.5, 'windSpeed': 15.47,
                                      'windGust': 26.73, 'windBearing': 248,
                                      'cloudCover': 0.97, 'uvIndex': 0, 'visibility': 10,
                                      'ozone': 347.8},
                                     {'time': 1580914800, 'summary': 'Overcast',
                                      'icon': 'cloudy', 'precipIntensity': 0,
                                      'precipProbability': 0, 'temperature': 45.86,
                                      'apparentTemperature': 39.14, 'dewPoint': 40.91,
                                      'humidity': 0.83, 'pressure': 1031.1, 'windSpeed': 15.78,
                                      'windGust': 27.61, 'windBearing': 248,
                                      'cloudCover': 0.98, 'uvIndex': 0, 'visibility': 10,
                                      'ozone': 349.1},
                                     {'time': 1580918400, 'summary': 'Overcast',
                                      'icon': 'cloudy', 'precipIntensity': 0,
                                      'precipProbability': 0, 'temperature': 44.81,
                                      'apparentTemperature': 37.9, 'dewPoint': 39.51,
                                      'humidity': 0.82, 'pressure': 1030.8, 'windSpeed': 15.36,
                                      'windGust': 27.54, 'windBearing': 248,
                                      'cloudCover': 0.98, 'uvIndex': 0, 'visibility': 10,
                                      'ozone': 346.1},
                                     {'time': 1580922000, 'summary': 'Overcast',
                                      'icon': 'cloudy', 'precipIntensity': 0.0003,
                                      'precipProbability': 0.04, 'precipType': 'rain',
                                      'temperature': 43.48, 'apparentTemperature': 36.44,
                                      'dewPoint': 38.11, 'humidity': 0.81, 'pressure': 1030.6,
                                      'windSpeed': 14.48, 'windGust': 26.9, 'windBearing': 248,
                                      'cloudCover': 0.99, 'uvIndex': 0, 'visibility': 10,
                                      'ozone': 340.8},
                                     {'time': 1580925600, 'summary': 'Overcast',
                                      'icon': 'cloudy', 'precipIntensity': 0.0003,
                                      'precipProbability': 0.02, 'precipType': 'rain',
                                      'temperature': 42.41, 'apparentTemperature': 35.35,
                                      'dewPoint': 37.1, 'humidity': 0.81, 'pressure': 1030.5,
                                      'windSpeed': 13.58, 'windGust': 26.12,
                                      'windBearing': 248, 'cloudCover': 0.99, 'uvIndex': 0,
                                      'visibility': 10, 'ozone': 336.8},
                                     {'time': 1580929200, 'summary': 'Overcast',
                                      'icon': 'cloudy', 'precipIntensity': 0,
                                      'precipProbability': 0, 'temperature': 41.59,
                                      'apparentTemperature': 34.6, 'dewPoint': 36.58,
                                      'humidity': 0.82, 'pressure': 1030.5, 'windSpeed': 12.68,
                                      'windGust': 25.33, 'windBearing': 249, 'cloudCover': 1,
                                      'uvIndex': 0, 'visibility': 10, 'ozone': 335.7},
                                     {'time': 1580932800, 'summary': 'Overcast',
                                      'icon': 'cloudy', 'precipIntensity': 0,
                                      'precipProbability': 0, 'temperature': 41.03,
                                      'apparentTemperature': 34.25, 'dewPoint': 36.59,
                                      'humidity': 0.84, 'pressure': 1030.5, 'windSpeed': 11.71,
                                      'windGust': 24.4, 'windBearing': 249, 'cloudCover': 0.99,
                                      'uvIndex': 0, 'visibility': 10, 'ozone': 335.7},
                                     {'time': 1580936400, 'summary': 'Overcast',
                                      'icon': 'cloudy', 'precipIntensity': 0,
                                      'precipProbability': 0, 'temperature': 40.6,
                                      'apparentTemperature': 34.03, 'dewPoint': 36.64,
                                      'humidity': 0.86, 'pressure': 1030.5, 'windSpeed': 10.86,
                                      'windGust': 23.44, 'windBearing': 248,
                                      'cloudCover': 0.95, 'uvIndex': 0, 'visibility': 10,
                                      'ozone': 335.9},
                                     {'time': 1580940000, 'summary': 'Mostly Cloudy',
                                      'icon': 'partly-cloudy-night', 'precipIntensity': 0,
                                      'precipProbability': 0, 'temperature': 40.12,
                                      'apparentTemperature': 33.74, 'dewPoint': 36.37,
                                      'humidity': 0.86, 'pressure': 1030.4, 'windSpeed': 10.1,
                                      'windGust': 22.47, 'windBearing': 249,
                                      'cloudCover': 0.83, 'uvIndex': 0, 'visibility': 10,
                                      'ozone': 335.8},
                                     {'time': 1580943600, 'summary': 'Mostly Cloudy',
                                      'icon': 'partly-cloudy-night', 'precipIntensity': 0,
                                      'precipProbability': 0, 'temperature': 39.59,
                                      'apparentTemperature': 33.38, 'dewPoint': 36.01,
                                      'humidity': 0.87, 'pressure': 1030.2, 'windSpeed': 9.44,
                                      'windGust': 21.5, 'windBearing': 248, 'cloudCover': 0.66,
                                      'uvIndex': 0, 'visibility': 10, 'ozone': 335.8},
                                     {'time': 1580947200, 'summary': 'Partly Cloudy',
                                      'icon': 'partly-cloudy-night', 'precipIntensity': 0,
                                      'precipProbability': 0, 'temperature': 39.09,
                                      'apparentTemperature': 32.98, 'dewPoint': 35.66,
                                      'humidity': 0.87, 'pressure': 1029.9, 'windSpeed': 8.99,
                                      'windGust': 20.55, 'windBearing': 247,
                                      'cloudCover': 0.48, 'uvIndex': 0, 'visibility': 10,
                                      'ozone': 335.6}, {'time': 1580950800, 'summary': 'Clear',
                                                        'icon': 'clear-night',
                                                        'precipIntensity': 0,
                                                        'precipProbability': 0,
                                                        'temperature': 38.69,
                                                        'apparentTemperature': 32.51,
                                                        'dewPoint': 35.3, 'humidity': 0.87,
                                                        'pressure': 1029.7, 'windSpeed': 8.94,
                                                        'windGust': 19.72, 'windBearing': 245,
                                                        'cloudCover': 0.31, 'uvIndex': 0,
                                                        'visibility': 10, 'ozone': 334.9},
                                     {'time': 1580954400, 'summary': 'Clear',
                                      'icon': 'clear-night', 'precipIntensity': 0,
                                      'precipProbability': 0, 'temperature': 38.28,
                                      'apparentTemperature': 31.93, 'dewPoint': 35.01,
                                      'humidity': 0.88, 'pressure': 1029.4, 'windSpeed': 9.1,
                                      'windGust': 18.95, 'windBearing': 244,
                                      'cloudCover': 0.13, 'uvIndex': 0, 'visibility': 10,
                                      'ozone': 334}, {'time': 1580958000, 'summary': 'Clear',
                                                      'icon': 'clear-night',
                                                      'precipIntensity': 0,
                                                      'precipProbability': 0,
                                                      'temperature': 37.93,
                                                      'apparentTemperature': 31.48,
                                                      'dewPoint': 34.74, 'humidity': 0.88,
                                                      'pressure': 1029.2, 'windSpeed': 9.14,
                                                      'windGust': 17.96, 'windBearing': 243,
                                                      'cloudCover': 0, 'uvIndex': 0,
                                                      'visibility': 10, 'ozone': 333.1},
                                     {'time': 1580961600, 'summary': 'Clear',
                                      'icon': 'clear-night', 'precipIntensity': 0,
                                      'precipProbability': 0, 'temperature': 37.56,
                                      'apparentTemperature': 31.16, 'dewPoint': 34.5,
                                      'humidity': 0.89, 'pressure': 1029, 'windSpeed': 8.87,
                                      'windGust': 16.51, 'windBearing': 241, 'cloudCover': 0,
                                      'uvIndex': 0, 'visibility': 10, 'ozone': 333},
                                     {'time': 1580965200, 'summary': 'Clear',
                                      'icon': 'clear-night', 'precipIntensity': 0,
                                      'precipProbability': 0, 'temperature': 37.31,
                                      'apparentTemperature': 31.06, 'dewPoint': 34.32,
                                      'humidity': 0.89, 'pressure': 1028.8, 'windSpeed': 8.46,
                                      'windGust': 14.83, 'windBearing': 240, 'cloudCover': 0,
                                      'uvIndex': 0, 'visibility': 10, 'ozone': 333},
                                     {'time': 1580968800, 'summary': 'Clear',
                                      'icon': 'clear-night', 'precipIntensity': 0,
                                      'precipProbability': 0, 'temperature': 37.15,
                                      'apparentTemperature': 31.01, 'dewPoint': 34.29,
                                      'humidity': 0.89, 'pressure': 1028.6, 'windSpeed': 8.19,
                                      'windGust': 13.64, 'windBearing': 239, 'cloudCover': 0,
                                      'uvIndex': 0, 'visibility': 10, 'ozone': 331.7},
                                     {'time': 1580972400, 'summary': 'Clear',
                                      'icon': 'clear-night', 'precipIntensity': 0,
                                      'precipProbability': 0, 'temperature': 36.89,
                                      'apparentTemperature': 30.72, 'dewPoint': 34.19,
                                      'humidity': 0.9, 'pressure': 1028.5, 'windSpeed': 8.14,
                                      'windGust': 13.24, 'windBearing': 239, 'cloudCover': 0,
                                      'uvIndex': 0, 'visibility': 10, 'ozone': 328.1},
                                     {'time': 1580976000, 'summary': 'Clear',
                                      'icon': 'clear-night', 'precipIntensity': 0.0002,
                                      'precipProbability': 0.02, 'precipType': 'rain',
                                      'temperature': 36.71, 'apparentTemperature': 30.46,
                                      'dewPoint': 34.2, 'humidity': 0.91, 'pressure': 1028.5,
                                      'windSpeed': 8.21, 'windGust': 13.26, 'windBearing': 239,
                                      'cloudCover': 0, 'uvIndex': 0, 'visibility': 10,
                                      'ozone': 323.2}, {'time': 1580979600, 'summary': 'Clear',
                                                        'icon': 'clear-day',
                                                        'precipIntensity': 0.0002,
                                                        'precipProbability': 0.03,
                                                        'precipType': 'rain',
                                                        'temperature': 37.27,
                                                        'apparentTemperature': 31.06,
                                                        'dewPoint': 34.88, 'humidity': 0.91,
                                                        'pressure': 1028.4, 'windSpeed': 8.37,
                                                        'windGust': 13.57, 'windBearing': 240,
                                                        'cloudCover': 0.02, 'uvIndex': 0,
                                                        'visibility': 10, 'ozone': 318.3},
                                     {'time': 1580983200, 'summary': 'Clear',
                                      'icon': 'clear-day', 'precipIntensity': 0.0002,
                                      'precipProbability': 0.03, 'precipType': 'rain',
                                      'temperature': 39, 'apparentTemperature': 32.98,
                                      'dewPoint': 36.36, 'humidity': 0.9, 'pressure': 1028.2,
                                      'windSpeed': 8.76, 'windGust': 14.55, 'windBearing': 241,
                                      'cloudCover': 0.12, 'uvIndex': 0, 'visibility': 10,
                                      'ozone': 313.3}, {'time': 1580986800, 'summary': 'Clear',
                                                        'icon': 'clear-day',
                                                        'precipIntensity': 0,
                                                        'precipProbability': 0,
                                                        'temperature': 41.47,
                                                        'apparentTemperature': 35.8,
                                                        'dewPoint': 38.23, 'humidity': 0.88,
                                                        'pressure': 1028, 'windSpeed': 9.22,
                                                        'windGust': 16.08, 'windBearing': 244,
                                                        'cloudCover': 0.27, 'uvIndex': 1,
                                                        'visibility': 10, 'ozone': 308.5},
                                     {'time': 1580990400, 'summary': 'Partly Cloudy',
                                      'icon': 'partly-cloudy-day', 'precipIntensity': 0,
                                      'precipProbability': 0, 'temperature': 43.7,
                                      'apparentTemperature': 38.47, 'dewPoint': 39.9,
                                      'humidity': 0.86, 'pressure': 1027.8, 'windSpeed': 9.39,
                                      'windGust': 16.99, 'windBearing': 246,
                                      'cloudCover': 0.39, 'uvIndex': 1, 'visibility': 10,
                                      'ozone': 305.8},
                                     {'time': 1580994000, 'summary': 'Partly Cloudy',
                                      'icon': 'partly-cloudy-day', 'precipIntensity': 0,
                                      'precipProbability': 0, 'temperature': 45.53,
                                      'apparentTemperature': 40.88, 'dewPoint': 41.26,
                                      'humidity': 0.85, 'pressure': 1027.4, 'windSpeed': 9.04,
                                      'windGust': 16.98, 'windBearing': 247,
                                      'cloudCover': 0.47, 'uvIndex': 1, 'visibility': 10,
                                      'ozone': 307.1},
                                     {'time': 1580997600, 'summary': 'Partly Cloudy',
                                      'icon': 'partly-cloudy-day', 'precipIntensity': 0,
                                      'precipProbability': 0, 'temperature': 46.89,
                                      'apparentTemperature': 42.83, 'dewPoint': 41.97,
                                      'humidity': 0.83, 'pressure': 1026.9, 'windSpeed': 8.34,
                                      'windGust': 16.36, 'windBearing': 246,
                                      'cloudCover': 0.52, 'uvIndex': 1, 'visibility': 10,
                                      'ozone': 310.5},
                                     {'time': 1581001200, 'summary': 'Partly Cloudy',
                                      'icon': 'partly-cloudy-day', 'precipIntensity': 0,
                                      'precipProbability': 0, 'temperature': 47.2,
                                      'apparentTemperature': 43.59, 'dewPoint': 42.05,
                                      'humidity': 0.82, 'pressure': 1026.6, 'windSpeed': 7.47,
                                      'windGust': 15, 'windBearing': 242, 'cloudCover': 0.54,
                                      'uvIndex': 0, 'visibility': 10, 'ozone': 313.6},
                                     {'time': 1581004800, 'summary': 'Partly Cloudy',
                                      'icon': 'partly-cloudy-day', 'precipIntensity': 0,
                                      'precipProbability': 0, 'temperature': 45.77,
                                      'apparentTemperature': 42.38, 'dewPoint': 40.82,
                                      'humidity': 0.83, 'pressure': 1026.3, 'windSpeed': 6.43,
                                      'windGust': 12.26, 'windBearing': 231,
                                      'cloudCover': 0.53, 'uvIndex': 0, 'visibility': 10,
                                      'ozone': 315.1},
                                     {'time': 1581008400, 'summary': 'Partly Cloudy',
                                      'icon': 'partly-cloudy-night', 'precipIntensity': 0,
                                      'precipProbability': 0, 'temperature': 43.36,
                                      'apparentTemperature': 40.23, 'dewPoint': 39.11,
                                      'humidity': 0.85, 'pressure': 1026.1, 'windSpeed': 5.26,
                                      'windGust': 8.77, 'windBearing': 216, 'cloudCover': 0.49,
                                      'uvIndex': 0, 'visibility': 10, 'ozone': 316.1},
                                     {'time': 1581012000, 'summary': 'Partly Cloudy',
                                      'icon': 'partly-cloudy-night', 'precipIntensity': 0,
                                      'precipProbability': 0, 'temperature': 41.16,
                                      'apparentTemperature': 38.38, 'dewPoint': 37.94,
                                      'humidity': 0.88, 'pressure': 1025.8, 'windSpeed': 4.32,
                                      'windGust': 6.17, 'windBearing': 206, 'cloudCover': 0.5,
                                      'uvIndex': 0, 'visibility': 10, 'ozone': 316.9},
                                     {'time': 1581015600, 'summary': 'Mostly Cloudy',
                                      'icon': 'partly-cloudy-night', 'precipIntensity': 0,
                                      'precipProbability': 0, 'temperature': 39.73,
                                      'apparentTemperature': 37.2, 'dewPoint': 37.05,
                                      'humidity': 0.9, 'pressure': 1025.6, 'windSpeed': 3.8,
                                      'windGust': 5.24, 'windBearing': 205, 'cloudCover': 0.6,
                                      'uvIndex': 0, 'visibility': 10, 'ozone': 317.6},
                                     {'time': 1581019200, 'summary': 'Mostly Cloudy',
                                      'icon': 'partly-cloudy-night', 'precipIntensity': 0,
                                      'precipProbability': 0, 'temperature': 38.55,
                                      'apparentTemperature': 36.12, 'dewPoint': 36.31,
                                      'humidity': 0.92, 'pressure': 1025.3, 'windSpeed': 3.53,
                                      'windGust': 5.18, 'windBearing': 210, 'cloudCover': 0.74,
                                      'uvIndex': 0, 'visibility': 10, 'ozone': 318}]},
                             'daily': {
                                 'summary': 'Light rain on Saturday through next Tuesday.',
                                 'icon': 'rain', 'data': [
                                     {'time': 1580774400, 'summary': 'Windy in the morning.',
                                      'icon': 'wind', 'sunriseTime': 1580803440,
                                      'sunsetTime': 1580835120, 'moonPhase': 0.34,
                                      'precipIntensity': 0.0004, 'precipIntensityMax': 0.0015,
                                      'precipIntensityMaxTime': 1580785500,
                                      'precipProbability': 0.27, 'precipType': 'rain',
                                      'temperatureHigh': 49.1,
                                      'temperatureHighTime': 1580822100,
                                      'temperatureLow': 37.71,
                                      'temperatureLowTime': 1580882940,
                                      'apparentTemperatureHigh': 44.83,
                                      'apparentTemperatureHighTime': 1580822460,
                                      'apparentTemperatureLow': 31.87,
                                      'apparentTemperatureLowTime': 1580889360,
                                      'dewPoint': 36.29, 'humidity': 0.79, 'pressure': 1018.7,
                                      'windSpeed': 11.69, 'windGust': 47.07,
                                      'windGustTime': 1580784660, 'windBearing': 277,
                                      'cloudCover': 0.32, 'uvIndex': 1,
                                      'uvIndexTime': 1580818860, 'visibility': 10,
                                      'ozone': 368, 'temperatureMin': 37.79,
                                      'temperatureMinTime': 1580777040, 'temperatureMax': 49.1,
                                      'temperatureMaxTime': 1580822100,
                                      'apparentTemperatureMin': 28.08,
                                      'apparentTemperatureMinTime': 1580774760,
                                      'apparentTemperatureMax': 44.83,
                                      'apparentTemperatureMaxTime': 1580822460},
                                     {'time': 1580860800,
                                      'summary': 'Overcast throughout the day.',
                                      'icon': 'cloudy', 'sunriseTime': 1580889720,
                                      'sunsetTime': 1580921640, 'moonPhase': 0.37,
                                      'precipIntensity': 0.0001, 'precipIntensityMax': 0.0003,
                                      'precipIntensityMaxTime': 1580924820,
                                      'precipProbability': 0.16, 'precipType': 'rain',
                                      'temperatureHigh': 46.89,
                                      'temperatureHighTime': 1580909700,
                                      'temperatureLow': 36.2, 'temperatureLowTime': 1580975460,
                                      'apparentTemperatureHigh': 39.99,
                                      'apparentTemperatureHighTime': 1580908860,
                                      'apparentTemperatureLow': 30.45,
                                      'apparentTemperatureLowTime': 1580975580,
                                      'dewPoint': 37.07, 'humidity': 0.85, 'pressure': 1032.1,
                                      'windSpeed': 11.22, 'windGust': 27.68,
                                      'windGustTime': 1580916060, 'windBearing': 247,
                                      'cloudCover': 0.82, 'uvIndex': 1,
                                      'uvIndexTime': 1580905380, 'visibility': 10,
                                      'ozone': 334.5, 'temperatureMin': 37.71,
                                      'temperatureMinTime': 1580882940,
                                      'temperatureMax': 46.89,
                                      'temperatureMaxTime': 1580909700,
                                      'apparentTemperatureMin': 31.87,
                                      'apparentTemperatureMinTime': 1580889360,
                                      'apparentTemperatureMax': 39.99,
                                      'apparentTemperatureMaxTime': 1580908860},
                                     {'time': 1580947200,
                                      'summary': 'Partly cloudy throughout the day.',
                                      'icon': 'partly-cloudy-day', 'sunriseTime': 1580976000,
                                      'sunsetTime': 1581008160, 'moonPhase': 0.41,
                                      'precipIntensity': 0, 'precipIntensityMax': 0.0002,
                                      'precipIntensityMaxTime': 1580977200,
                                      'precipProbability': 0.09, 'temperatureHigh': 47.77,
                                      'temperatureHighTime': 1581000300,
                                      'temperatureLow': 32.78,
                                      'temperatureLowTime': 1581051420,
                                      'apparentTemperatureHigh': 43.6,
                                      'apparentTemperatureHighTime': 1581000900,
                                      'apparentTemperatureLow': 31.49,
                                      'apparentTemperatureLowTime': 1581062400,
                                      'dewPoint': 36.74, 'humidity': 0.88, 'pressure': 1027.2,
                                      'windSpeed': 7.02, 'windGust': 20.55,
                                      'windGustTime': 1580947200, 'windBearing': 237,
                                      'cloudCover': 0.36, 'uvIndex': 1,
                                      'uvIndexTime': 1580991780, 'visibility': 10,
                                      'ozone': 320.4, 'temperatureMin': 35.25,
                                      'temperatureMinTime': 1581033600,
                                      'temperatureMax': 47.77,
                                      'temperatureMaxTime': 1581000300,
                                      'apparentTemperatureMin': 30.45,
                                      'apparentTemperatureMinTime': 1580975580,
                                      'apparentTemperatureMax': 43.6,
                                      'apparentTemperatureMaxTime': 1581000900},
                                     {'time': 1581033600,
                                      'summary': 'Possible light rain overnight.',
                                      'icon': 'clear-day', 'sunriseTime': 1581062280,
                                      'sunsetTime': 1581094680, 'moonPhase': 0.45,
                                      'precipIntensity': 0.0001, 'precipIntensityMax': 0.0004,
                                      'precipIntensityMaxTime': 1581120000,
                                      'precipProbability': 0.08, 'precipType': 'rain',
                                      'temperatureHigh': 47.82,
                                      'temperatureHighTime': 1581087420,
                                      'temperatureLow': 40.71,
                                      'temperatureLowTime': 1581148800,
                                      'apparentTemperatureHigh': 42.81,
                                      'apparentTemperatureHighTime': 1581087240,
                                      'apparentTemperatureLow': 32.52,
                                      'apparentTemperatureLowTime': 1581148800,
                                      'dewPoint': 34.94, 'humidity': 0.83, 'pressure': 1012.3,
                                      'windSpeed': 6.17, 'windGust': 20.56,
                                      'windGustTime': 1581089280, 'windBearing': 151,
                                      'cloudCover': 0.4, 'uvIndex': 1,
                                      'uvIndexTime': 1581078180, 'visibility': 10,
                                      'ozone': 306.5, 'temperatureMin': 32.78,
                                      'temperatureMinTime': 1581051420,
                                      'temperatureMax': 47.82,
                                      'temperatureMaxTime': 1581087420,
                                      'apparentTemperatureMin': 31.38,
                                      'apparentTemperatureMinTime': 1581063240,
                                      'apparentTemperatureMax': 42.81,
                                      'apparentTemperatureMaxTime': 1581087240},
                                     {'time': 1581120000,
                                      'summary': 'Light rain until morning, starting again in the evening.',
                                      'icon': 'rain', 'sunriseTime': 1581148560,
                                      'sunsetTime': 1581181260, 'moonPhase': 0.48,
                                      'precipIntensity': 0.0063, 'precipIntensityMax': 0.0224,
                                      'precipIntensityMaxTime': 1581201900,
                                      'precipProbability': 0.76, 'precipType': 'rain',
                                      'temperatureHigh': 46.1,
                                      'temperatureHighTime': 1581170820,
                                      'temperatureLow': 42.26,
                                      'temperatureLowTime': 1581188400,
                                      'apparentTemperatureHigh': 37.78,
                                      'apparentTemperatureHighTime': 1581170880,
                                      'apparentTemperatureLow': 34.46,
                                      'apparentTemperatureLowTime': 1581189360, 'dewPoint': 39,
                                      'humidity': 0.84, 'pressure': 1001, 'windSpeed': 17.67,
                                      'windGust': 47.71, 'windGustTime': 1581206400,
                                      'windBearing': 210, 'cloudCover': 0.67, 'uvIndex': 1,
                                      'uvIndexTime': 1581165900, 'visibility': 9.924,
                                      'ozone': 333.7, 'temperatureMin': 40.21,
                                      'temperatureMinTime': 1581152220, 'temperatureMax': 46.1,
                                      'temperatureMaxTime': 1581170820,
                                      'apparentTemperatureMin': 31.76,
                                      'apparentTemperatureMinTime': 1581152460,
                                      'apparentTemperatureMax': 39.53,
                                      'apparentTemperatureMaxTime': 1581120720},
                                     {'time': 1581206400,
                                      'summary': 'Light rain in the morning and afternoon.',
                                      'icon': 'rain', 'sunriseTime': 1581234840,
                                      'sunsetTime': 1581267780, 'moonPhase': 0.52,
                                      'precipIntensity': 0.0201, 'precipIntensityMax': 0.0403,
                                      'precipIntensityMaxTime': 1581249600,
                                      'precipProbability': 0.96, 'precipType': 'rain',
                                      'temperatureHigh': 53.17,
                                      'temperatureHighTime': 1581257160,
                                      'temperatureLow': 38.36,
                                      'temperatureLowTime': 1581321600,
                                      'apparentTemperatureHigh': 52.67,
                                      'apparentTemperatureHighTime': 1581257160,
                                      'apparentTemperatureLow': 28.51,
                                      'apparentTemperatureLowTime': 1581321600,
                                      'dewPoint': 43.83, 'humidity': 0.88, 'pressure': 974.9,
                                      'windSpeed': 23.66, 'windGust': 55.18,
                                      'windGustTime': 1581240300, 'windBearing': 225,
                                      'cloudCover': 0.83, 'uvIndex': 1,
                                      'uvIndexTime': 1581251040, 'visibility': 9.153,
                                      'ozone': 305.3, 'temperatureMin': 41.39,
                                      'temperatureMinTime': 1581292800,
                                      'temperatureMax': 53.17,
                                      'temperatureMaxTime': 1581257160,
                                      'apparentTemperatureMin': 30.33,
                                      'apparentTemperatureMinTime': 1581292800,
                                      'apparentTemperatureMax': 52.67,
                                      'apparentTemperatureMaxTime': 1581257160},
                                     {'time': 1581292800,
                                      'summary': 'Possible drizzle in the afternoon.',
                                      'icon': 'rain', 'sunriseTime': 1581321120,
                                      'sunsetTime': 1581354300, 'moonPhase': 0.56,
                                      'precipIntensity': 0.0038, 'precipIntensityMax': 0.0101,
                                      'precipIntensityMaxTime': 1581337020,
                                      'precipProbability': 0.59, 'precipType': 'rain',
                                      'temperatureHigh': 39.69,
                                      'temperatureHighTime': 1581318000,
                                      'temperatureLow': 36.73,
                                      'temperatureLowTime': 1581361200,
                                      'apparentTemperatureHigh': 28.87,
                                      'apparentTemperatureHighTime': 1581318000,
                                      'apparentTemperatureLow': 25.99,
                                      'apparentTemperatureLowTime': 1581390180, 'dewPoint': 34,
                                      'humidity': 0.82, 'pressure': 981.1, 'windSpeed': 24.61,
                                      'windGust': 46.95, 'windGustTime': 1581346500,
                                      'windBearing': 254, 'cloudCover': 0.71, 'uvIndex': 1,
                                      'uvIndexTime': 1581337440, 'visibility': 8.944,
                                      'ozone': 403.5, 'temperatureMin': 36.71,
                                      'temperatureMinTime': 1581359160,
                                      'temperatureMax': 42.38,
                                      'temperatureMaxTime': 1581292800,
                                      'apparentTemperatureMin': 26.39,
                                      'apparentTemperatureMinTime': 1581358740,
                                      'apparentTemperatureMax': 30.33,
                                      'apparentTemperatureMaxTime': 1581292800},
                                     {'time': 1581379200,
                                      'summary': 'Possible drizzle in the morning.',
                                      'icon': 'rain', 'sunriseTime': 1581407340,
                                      'sunsetTime': 1581440820, 'moonPhase': 0.6,
                                      'precipIntensity': 0.0024, 'precipIntensityMax': 0.009,
                                      'precipIntensityMaxTime': 1581390240,
                                      'precipProbability': 0.58, 'precipType': 'rain',
                                      'temperatureHigh': 41.42,
                                      'temperatureHighTime': 1581428340,
                                      'temperatureLow': 35.01,
                                      'temperatureLowTime': 1581494400,
                                      'apparentTemperatureHigh': 29.68,
                                      'apparentTemperatureHighTime': 1581429660,
                                      'apparentTemperatureLow': 25.35,
                                      'apparentTemperatureLowTime': 1581494400,
                                      'dewPoint': 33.86, 'humidity': 0.83, 'pressure': 991.5,
                                      'windSpeed': 25.85, 'windGust': 62.48,
                                      'windGustTime': 1581422220, 'windBearing': 254,
                                      'cloudCover': 0.74, 'uvIndex': 1,
                                      'uvIndexTime': 1581423840, 'visibility': 9.119,
                                      'ozone': 434.1, 'temperatureMin': 36.72,
                                      'temperatureMinTime': 1581465600,
                                      'temperatureMax': 41.42,
                                      'temperatureMaxTime': 1581428340,
                                      'apparentTemperatureMin': 25.99,
                                      'apparentTemperatureMinTime': 1581390180,
                                      'apparentTemperatureMax': 29.68,
                                      'apparentTemperatureMaxTime': 1581429660}]}, 'flags': {
        'sources': ['meteoalarm', 'cmc', 'gfs', 'icon', 'isd', 'madis',
                    'darksky', 'nearest-precip'],
        'meteoalarm-license': 'Based on data from EUMETNET - MeteoAlarm [https://www.meteoalarm.eu/]. Time delays between this website and the MeteoAlarm website are possible; for the most up to date information about alert levels as published by the participating National Meteorological Services please use the MeteoAlarm website.',
        'nearest-station': 6.861, 'units': 'us'}, 'offset': 0}

timemachine_success_response = {'latitude': 56.0712, 'longitude': -3.1743,
                                'timezone': 'Europe/London',
                                'currently': {'time': 255657600, 'temperature': 37.6,
                                              'apparentTemperature': 37.6, 'dewPoint': 37.06,
                                              'humidity': 0.98, 'pressure': 1017.7,
                                              'windSpeed': 0, 'cloudCover': 1, 'uvIndex': 0},
                                'hourly': {'data': [{'time': 255657600, 'temperature': 37.6,
                                                     'apparentTemperature': 37.6,
                                                     'dewPoint': 37.06, 'humidity': 0.98,
                                                     'pressure': 1017.7, 'windSpeed': 0,
                                                     'cloudCover': 1, 'uvIndex': 0},
                                                    {'time': 255661200, 'temperature': 35.74,
                                                     'apparentTemperature': 35.74,
                                                     'dewPoint': 35.59, 'humidity': 0.99,
                                                     'pressure': 1018.2, 'windSpeed': 0,
                                                     'cloudCover': 1, 'uvIndex': 0},
                                                    {'time': 255664800, 'temperature': 35.74,
                                                     'apparentTemperature': 35.74,
                                                     'dewPoint': 35.59, 'humidity': 0.99,
                                                     'pressure': 1018.5, 'windSpeed': 0,
                                                     'cloudCover': 1, 'uvIndex': 0},
                                                    {'time': 255668400, 'temperature': 35.74,
                                                     'apparentTemperature': 35.74,
                                                     'dewPoint': 35.59, 'humidity': 0.99,
                                                     'pressure': 1018.7, 'windSpeed': 0,
                                                     'cloudCover': 1, 'uvIndex': 0},
                                                    {'time': 255672000, 'temperature': 35.74,
                                                     'apparentTemperature': 35.74,
                                                     'dewPoint': 35.59, 'humidity': 0.99,
                                                     'pressure': 1018.8, 'windSpeed': 0,
                                                     'cloudCover': 0.69, 'uvIndex': 0},
                                                    {'time': 255675600, 'temperature': 35.74,
                                                     'apparentTemperature': 35.74,
                                                     'dewPoint': 35.59, 'humidity': 0.99,
                                                     'pressure': 1019.2, 'windSpeed': 0,
                                                     'cloudCover': 0.69, 'uvIndex': 0},
                                                    {'time': 255679200, 'temperature': 34.26,
                                                     'apparentTemperature': 34.26,
                                                     'dewPoint': 34.12, 'humidity': 0.99,
                                                     'pressure': 1019.2, 'windSpeed': 0,
                                                     'cloudCover': 0.59, 'uvIndex': 0},
                                                    {'time': 255682800, 'temperature': 32.83,
                                                     'apparentTemperature': 32.83,
                                                     'dewPoint': 32.68, 'humidity': 0.99,
                                                     'pressure': 1019.6, 'windSpeed': 0,
                                                     'cloudCover': 1, 'uvIndex': 0},
                                                    {'time': 255686400, 'temperature': 32.49,
                                                     'apparentTemperature': 32.49,
                                                     'dewPoint': 30.84, 'humidity': 0.94,
                                                     'pressure': 1019.9, 'windSpeed': 1.11,
                                                     'windBearing': 206, 'cloudCover': 0.88,
                                                     'uvIndex': 0},
                                                    {'time': 255690000, 'temperature': 34.61,
                                                     'apparentTemperature': 34.61,
                                                     'dewPoint': 33.78, 'humidity': 0.97,
                                                     'pressure': 1020.6, 'windSpeed': 1.23,
                                                     'windBearing': 191, 'cloudCover': 0.95,
                                                     'uvIndex': 0},
                                                    {'time': 255693600, 'temperature': 34.26,
                                                     'apparentTemperature': 34.26,
                                                     'dewPoint': 33.78, 'humidity': 0.98,
                                                     'pressure': 1021.3, 'windSpeed': 0,
                                                     'cloudCover': 0.94, 'uvIndex': 0},
                                                    {'time': 255697200, 'temperature': 35.74,
                                                     'apparentTemperature': 35.74,
                                                     'dewPoint': 35.59, 'humidity': 0.99,
                                                     'pressure': 1021.6, 'windSpeed': 0.52,
                                                     'windBearing': 0, 'cloudCover': 0.94,
                                                     'uvIndex': 1},
                                                    {'time': 255700800, 'temperature': 38.42,
                                                     'apparentTemperature': 38.42,
                                                     'dewPoint': 35.59, 'humidity': 0.89,
                                                     'pressure': 1022, 'windSpeed': 1.84,
                                                     'windBearing': 87, 'cloudCover': 0.98,
                                                     'uvIndex': 1},
                                                    {'time': 255704400, 'temperature': 39.03,
                                                     'apparentTemperature': 39.03,
                                                     'dewPoint': 38.88, 'humidity': 0.99,
                                                     'pressure': 1022.4, 'windSpeed': 2.24,
                                                     'windBearing': 122, 'cloudCover': 1,
                                                     'uvIndex': 1},
                                                    {'time': 255708000, 'temperature': 39.03,
                                                     'apparentTemperature': 34.02,
                                                     'dewPoint': 38.55, 'humidity': 0.98,
                                                     'pressure': 1022.3, 'windSpeed': 6.9,
                                                     'windBearing': 91, 'cloudCover': 1,
                                                     'uvIndex': 1},
                                                    {'time': 255711600, 'temperature': 39.53,
                                                     'apparentTemperature': 33.88,
                                                     'dewPoint': 36.36, 'humidity': 0.88,
                                                     'pressure': 1022.5, 'windSpeed': 8.26,
                                                     'windBearing': 127, 'cloudCover': 0.91,
                                                     'uvIndex': 0},
                                                    {'time': 255715200, 'temperature': 39.03,
                                                     'apparentTemperature': 34.14,
                                                     'dewPoint': 36.73, 'humidity': 0.91,
                                                     'pressure': 1022.9, 'windSpeed': 6.72,
                                                     'windBearing': 115, 'cloudCover': 1,
                                                     'uvIndex': 0},
                                                    {'time': 255718800, 'temperature': 39.03,
                                                     'apparentTemperature': 36.85,
                                                     'dewPoint': 36.73, 'humidity': 0.91,
                                                     'pressure': 1023.2, 'windSpeed': 3.36,
                                                     'windBearing': 120, 'cloudCover': 1,
                                                     'uvIndex': 0},
                                                    {'time': 255722400, 'temperature': 39.53,
                                                     'apparentTemperature': 34.93,
                                                     'dewPoint': 37.4, 'humidity': 0.92,
                                                     'pressure': 1023.3, 'windSpeed': 6.42,
                                                     'windBearing': 100, 'cloudCover': 1,
                                                     'uvIndex': 0},
                                                    {'time': 255726000, 'temperature': 39.03,
                                                     'apparentTemperature': 36.37,
                                                     'dewPoint': 35.26, 'humidity': 0.86,
                                                     'pressure': 1024, 'windSpeed': 3.81,
                                                     'windBearing': 112, 'cloudCover': 1,
                                                     'uvIndex': 0},
                                                    {'time': 255729600, 'temperature': 37.54,
                                                     'apparentTemperature': 31.92,
                                                     'dewPoint': 35.26, 'humidity': 0.91,
                                                     'pressure': 1024.5, 'windSpeed': 7.42,
                                                     'windBearing': 91, 'cloudCover': 1,
                                                     'uvIndex': 0},
                                                    {'time': 255733200, 'temperature': 37.71,
                                                     'apparentTemperature': 31.41,
                                                     'dewPoint': 33.78, 'humidity': 0.86,
                                                     'pressure': 1024.6, 'windSpeed': 8.74,
                                                     'windBearing': 113, 'cloudCover': 1,
                                                     'uvIndex': 0},
                                                    {'time': 255736800, 'temperature': 37.54,
                                                     'apparentTemperature': 32.46,
                                                     'dewPoint': 32.35, 'humidity': 0.81,
                                                     'pressure': 1024.9, 'windSpeed': 6.56,
                                                     'windBearing': 110, 'cloudCover': 1,
                                                     'uvIndex': 0},
                                                    {'time': 255740400, 'temperature': 36.07,
                                                     'apparentTemperature': 29.75,
                                                     'dewPoint': 32.35, 'humidity': 0.86,
                                                     'pressure': 1025.3, 'windSpeed': 8.11,
                                                     'windBearing': 91, 'cloudCover': 0.8,
                                                     'uvIndex': 0}]}, 'daily': {'data': [
        {'time': 255657600, 'sunriseTime': 255686280,
         'sunsetTime': 255718740, 'moonPhase': 0.01,
         'temperatureHigh': 40.03, 'temperatureHighTime': 255722400,
         'temperatureLow': 30.03, 'temperatureLowTime': 255770160,
         'apparentTemperatureHigh': 39.32,
         'apparentTemperatureHighTime': 255703380,
         'apparentTemperatureLow': 29.74,
         'apparentTemperatureLowTime': 255740520, 'dewPoint': 35.23,
         'humidity': 0.94, 'pressure': 1021.5, 'windSpeed': 3.02,
         'windBearing': 109, 'cloudCover': 0.93, 'uvIndex': 1,
         'uvIndexTime': 255702360, 'temperatureMin': 31.89,
         'temperatureMinTime': 255685440, 'temperatureMax': 40.03,
         'temperatureMaxTime': 255722400, 'apparentTemperatureMin': 29.75,
         'apparentTemperatureMinTime': 255740400,
         'apparentTemperatureMax': 39.32,
         'apparentTemperatureMaxTime': 255703380}]},
                                'flags': {'sources': ['cmc', 'gfs', 'icon', 'isd', 'madis'],
                                          'nearest-station': 6.861, 'units': 'us'},
                                'offset': 0}
