postcodesearch_success_response = [
    {'Version': 1, 'Key': '47724_PC', 'Type': 'PostalCode', 'Rank': 75, 'LocalizedName': 'Burntisland',
     'EnglishName': 'Burntisland', 'PrimaryPostalCode': 'KY3 9',
     'Region': {'ID': 'EUR', 'LocalizedName': 'Europe', 'EnglishName': 'Europe'},
     'Country': {'ID': 'GB', 'LocalizedName': 'United Kingdom', 'EnglishName': 'United Kingdom'},
     'AdministrativeArea': {'ID': 'FIF', 'LocalizedName': 'Fife', 'EnglishName': 'Fife', 'Level': 1,
                            'LocalizedType': 'Unitary Authority', 'EnglishType': 'Unitary Authority',
                            'CountryID': 'GB'},
     'TimeZone': {'Code': 'GMT', 'Name': 'Europe/London', 'GmtOffset': 0.0, 'IsDaylightSaving': False,
                  'NextOffsetChange': '2020-03-29T01:00:00Z'}, 'GeoPosition': {'Latitude': 56.069, 'Longitude': -3.195,
                                                                               'Elevation': {'Metric': {'Value': 62.0,
                                                                                                        'Unit': 'm',
                                                                                                        'UnitType': 5},
                                                                                             'Imperial': {
                                                                                                 'Value': 203.0,
                                                                                                 'Unit': 'ft',
                                                                                                 'UnitType': 0}}},
     'IsAlias': False, 'ParentCity': {'Key': '328180', 'LocalizedName': 'Burntisland', 'EnglishName': 'Burntisland'},
     'SupplementalAdminAreas': [{'Level': 0, 'LocalizedName': 'Scotland', 'EnglishName': 'Scotland'},
                                {'Level': 3, 'LocalizedName': 'Burntisland, Kinghorn and Western Kirkcaldy',
                                 'EnglishName': 'Burntisland, Kinghorn and Western Kirkcaldy'}],
     'DataSets': ['AirQualityCurrentConditions', 'AirQualityForecasts', 'Alerts', 'ForecastConfidence', 'MinuteCast',
                  'Radar']}]

textsearch_success_response = [{'Version': 1, 'Key': '3385695', 'Type': 'City', 'Rank': 85,
                                'LocalizedName': 'Kinghorn', 'EnglishName': 'Kinghorn',
                                'PrimaryPostalCode': 'L7B',
                                'Region': {'ID': 'NAM', 'LocalizedName': 'North America',
                                           'EnglishName': 'North America'},
                                'Country': {'ID': 'CA', 'LocalizedName': 'Canada',
                                            'EnglishName': 'Canada'},
                                'AdministrativeArea': {'ID': 'ON', 'LocalizedName': 'Ontario',
                                                       'EnglishName': 'Ontario', 'Level': 1,
                                                       'LocalizedType': 'Province',
                                                       'EnglishType': 'Province',
                                                       'CountryID': 'CA'},
                                'TimeZone': {'Code': 'EST', 'Name': 'America/Toronto',
                                             'GmtOffset': -5.0, 'IsDaylightSaving': False,
                                             'NextOffsetChange': '2020-03-08T07:00:00Z'},
                                'GeoPosition': {'Latitude': 43.921, 'Longitude': -79.555,
                                                'Elevation': {
                                                    'Metric': {'Value': 285.0, 'Unit': 'm',
                                                               'UnitType': 5},
                                                    'Imperial': {'Value': 934.0, 'Unit': 'ft',
                                                                 'UnitType': 0}}},
                                'IsAlias': False, 'SupplementalAdminAreas': [
        {'Level': 2, 'LocalizedName': 'York', 'EnglishName': 'York'}],
                                'DataSets': ['AirQualityCurrentConditions',
                                             'AirQualityForecasts', 'Alerts',
                                             'ForecastConfidence', 'MinuteCast', 'Radar']},
                               {'Version': 1, 'Key': '328200', 'Type': 'City', 'Rank': 85,
                                'LocalizedName': 'Kinghorn', 'EnglishName': 'Kinghorn',
                                'PrimaryPostalCode': 'KY3 9',
                                'Region': {'ID': 'EUR', 'LocalizedName': 'Europe',
                                           'EnglishName': 'Europe'},
                                'Country': {'ID': 'GB', 'LocalizedName': 'United Kingdom',
                                            'EnglishName': 'United Kingdom'},
                                'AdministrativeArea': {'ID': 'FIF', 'LocalizedName': 'Fife',
                                                       'EnglishName': 'Fife', 'Level': 1,
                                                       'LocalizedType': 'Unitary Authority',
                                                       'EnglishType': 'Unitary Authority',
                                                       'CountryID': 'GB'},
                                'TimeZone': {'Code': 'GMT', 'Name': 'Europe/London',
                                             'GmtOffset': 0.0, 'IsDaylightSaving': False,
                                             'NextOffsetChange': '2020-03-29T01:00:00Z'},
                                'GeoPosition': {'Latitude': 56.071, 'Longitude': -3.175,
                                                'Elevation': {
                                                    'Metric': {'Value': 6.0, 'Unit': 'm',
                                                               'UnitType': 5},
                                                    'Imperial': {'Value': 19.0, 'Unit': 'ft',
                                                                 'UnitType': 0}}},
                                'IsAlias': False, 'SupplementalAdminAreas': [
                                   {'Level': 0, 'LocalizedName': 'Scotland',
                                    'EnglishName': 'Scotland'}, {'Level': 3,
                                                                 'LocalizedName': 'Burntisland, Kinghorn and Western Kirkcaldy',
                                                                 'EnglishName': 'Burntisland, Kinghorn and Western Kirkcaldy'}],
                                'DataSets': ['AirQualityCurrentConditions',
                                             'AirQualityForecasts', 'Alerts',
                                             'ForecastConfidence', 'MinuteCast', 'Radar']}]

conditions_success_response = [
    {'LocalObservationDateTime': '2020-02-04T12:14:00-05:00', 'EpochTime': 1580836440, 'WeatherText': 'Cloudy',
     'WeatherIcon': 7, 'HasPrecipitation': False, 'PrecipitationType': None, 'IsDayTime': True,
     'Temperature': {'Metric': {'Value': -0.7, 'Unit': 'C', 'UnitType': 17},
                     'Imperial': {'Value': 31.0, 'Unit': 'F', 'UnitType': 18}},
     'MobileLink': 'http://m.accuweather.com/en/ca/kinghorn/l7b/current-weather/3385695?lang=en-us',
     'Link': 'http://www.accuweather.com/en/ca/kinghorn/l7b/current-weather/3385695?lang=en-us'}]
