postcode_valid_response = {
    'results': [{'address_components': [{'long_name': 'KY3 9UR', 'short_name': 'KY3 9UR', 'types': ['postal_code']},
                                        {'long_name': 'Glamis Road', 'short_name': 'Glamis Rd', 'types': ['route']},
                                        {'long_name': 'Kinghorn', 'short_name': 'Kinghorn',
                                         'types': ['locality', 'political']},
                                        {'long_name': 'Burntisland', 'short_name': 'Burntisland',
                                         'types': ['postal_town']}, {'long_name': 'Fife', 'short_name': 'Fife',
                                                                     'types': ['administrative_area_level_2',
                                                                               'political']},
                                        {'long_name': 'Scotland', 'short_name': 'Scotland',
                                         'types': ['administrative_area_level_1', 'political']},
                                        {'long_name': 'United Kingdom', 'short_name': 'GB',
                                         'types': ['country', 'political']}],
                 'formatted_address': 'Glamis Rd, Kinghorn, Burntisland KY3 9UR, UK', 'geometry': {
            'bounds': {'northeast': {'lat': 56.0724121, 'lng': -3.1744411},
                       'southwest': {'lat': 56.0716598, 'lng': -3.1757846}},
            'location': {'lat': 56.0719912, 'lng': -3.1750909}, 'location_type': 'APPROXIMATE',
            'viewport': {'northeast': {'lat': 56.0733849302915, 'lng': -3.173763869708498},
                         'southwest': {'lat': 56.0706869697085, 'lng': -3.176461830291502}}},
                 'place_id': 'ChIJT3l_Pwi2h0gRCp8egoK5hcU', 'types': ['postal_code']}], 'status': 'OK'}
